### ISSUE TITLE
free movement while flying in camera mode

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#101]
Hello, I just got my index base stations and controllers.  I was so anticipating getting to be able to move my head back and fourth to sneak in closer or maybe bob my head around to examine the models.  I can do that when it's not in any camera mode.  But once I choose a camera mode (or also a motion camera mode), the freedom to move around is gone.  Not sure if its a bug or not, so I just put it into a feature request.

Please allow us to still move our head side to side/back and fourth while flying around in camera mode.

**Comment by alloystorm** [comment]
Closing this now since I believe it's been address in the 0.8.1 or 0.8.2, feel free to raise again if anything is wrong.
