### ISSUE TITLE
Motion issue on 8.1

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#102]
Hi !!

First thing, thank you so much for the great features. The stocking/pantyhose effect is lit, it was a wonderful surprise.

I just noticed that every motions I load, are fine when the characters are close to start point center, then, as they move further, they lean/tilt as if their feet had bigger motion scale.
Please have a look at this !

Also, if you aren't working on it already, a feature to turn off or reduce MMD model's collision would be amazing, since some "skirt/hair" are vibrating like crazy on some models that aren't very optimal. Then even if we have some clipings, maybe dynamics would have smooth movements with collision off ?

Thanks again, love this update !!

**Comment by alloystorm** [comment]
I did notice something like that previously but wasn't able to reproduce it when trying to track it down. Do you have an example motion that is really obvious so it is easier for us to debug it?

**Comment by hboxgames** [comment]
Hi !
Here's one happening pretty much for me !
https://we.tl/t-lh32GsMFjx
Thanks !

**Comment by alloystorm** [comment]
This should be fixed in the latest builds. 

Please let me know if you are still having this issue after updating.

**Comment by hboxgames** [comment]
amazing, thanks !

**Comment by hboxgames** [comment]
This motion issue seems fixed for now !
