### ISSUE TITLE
Character and textures loading 

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#103]
Hi !!

Again, here are some major issues that apeared on this new version :
-only "left side" characters are loading when loading scene. All the ones that were on the screen right side of the list have disappeared.
-Stocking effect isn't saved. On scene or character loading, we have to set it up again
-Some Texture effect (such as on/off or color/gloss etc) aren't loading correctly when loading. Formerly set up characters are also kind of reseted on new version (textures were turned off to dress off for example, but then we have everything on)

Thanks !!

**Comment by alloystorm** [comment]
This should be fixed in the 0.8.2 release. Closing now but feel free to raise again if anything is not right.
