### ISSUE TITLE
FBX/VRC models

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#105]
Hi !

I would start by asking a question, more than just a request ..
Since DVVR is unity based, I was wondering if there is possibility to use unity-ready FBX models ??

I was about to buy some from gumroad and wanted to know before ..
And if not I wonder if it could be implemented, since you already did mix MMD and XPS which is incredible.

Thanks !

**Comment by alloystorm** [comment]
There is no out of the box solution for loading FBX model at runtime yet. 

What Unity provides is only available in the Unity Editor. So it's going to be hard to do. At this stage it is not our plans.
