### ISSUE TITLE
Scenes and Textures

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#106]
Hi !

I've asked about this before, but looks like it's coming over again ..
With the very latest version, all the texture customizations I made before are lost ? (such as un checking/unchecking or transparency mode etc)

Since it's the second time I was wondering if it would happen everytime, which wouldn't be worth recustomizing tons of models all over...
It'll be great if there's a way it can be updated without breaking all these changes, or a way to recover upon update.

Thanks !

ps. was wondering since a while, about turning **collision off** on MMD models like we can do on XPS models.. sometime it could look better when it's glitchy

**Comment by alloystorm** [comment]
Sorry, I promise we are going to be a lot more careful with changes like this in the future. 

About the MMD physics, we are planning to adding more physics control for MMD models in the next version, nothing solid yet but we'll see what we can do.
