### ISSUE TITLE
Set transparent as default for PNG.

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#109]
It wonder be nice it you could set transparent for PNG as defalut.

Standard -(https://user-images.githubusercontent.com/49305586/108629350-70d09400-742d-11eb-8b9f-13d33bd2249a.png)

Transparent -(https://user-images.githubusercontent.com/49305586/108629354-76c67500-742d-11eb-9099-c228ea6c3f81.png)

**Comment by alloystorm** [comment]
I had a crack at this but soon realized that this creates more trouble than benefit. A lot of models have multiple parts using the same PNG texture but only certain parts are meant to be transparent. 

I wonder what MMD uses to tell if a texture should be transparent... There is really nothing we can find in the model definition that says transparent or not.  

In the 0.9 release we've updated the code where we determine if a material should be transparent, it is a little bit smarter now that it recognises things like eyelashes and apply transparency by default. Will keep on improving
