### ISSUE TITLE
Feather Request

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#11]
(1) Add options to load more model.

(2) Add feather to load motion file. (some motion file don't have a audio file)

(3) Add feather when the dvvr automatic scanning the model and motion file without restart the dvvr (when the model and motion are add or remove from actors and motion folder)

(4) Add feather to move the camera with the mouse. (hold mouse R+drag to rotate the camera and L+drag left, right, up, down to move the camera and scroll wheel to zoom in and zoom out)

**Comment by alloystorm** [comment]
Thank you very much for the suggestions, will have a good look at them.
