### ISSUE TITLE
Lines tracking off pmx model

### ISSUE THREAD

**Issue by rewrisk** [alloystorm/dvvr#113]
After making some changes to a model, I found that when I loaded it in DVVR it had lines appearing intermittently ruining the immersion.

I had an edit of Mona i'd previously made with vagina and breast cones from Kangxi and added it to DVVR and it was great but there were improvements I wanted to make because there were gaps at some angles that bothered me. So I cut away the crotch area from Kangxi and adjusted it to fit the slightly different body shape of Mona weighted it then tested it in DVVR and it had these lines appearing?

Tried going through and cleaning everything up in PMXE and there were a bunch of things I corrected but the problem persists though the editor say's everything is fine now?

Is there any reason you would know of why this might be happening and how it could be fixed? The model was fine before I added to it but I don't understand why that would be a problem? Probably my favorite model so far to!

![MonaLines](https://user-images.githubusercontent.com/79775857/112358472-7cf98b00-8d24-11eb-9be4-9b313b8770e9.jpg)

**Desktop (please complete the following information):**
Streaming to my original quest headset from a windows 10 laptop with an 8Gb 3070 and 5800H 8core16thread cpu with 16GbRam using virtual desktop

**Additional context**

**Comment by alloystorm** [comment]
Is this still happening in 0.9.3? We make some change in physics & PMX model skeleton and it should work much better now.

**Comment by rewrisk** [comment]
Yeh, lines are not as obvious though. They appear darker.

**Comment by alloystorm** [comment]
Sorry for not being able to update this. 

I'm closing this now since it's been a while and there is not much we can do further without the model at hand. If the issue still exists, feel free to reopen the issue and attach the model file. Thanks for understanding.
