### ISSUE TITLE
Camera / Facial Motion

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#114]
Hi ! 

Thanks for the great stuff so far !

I had 2 little suggestions regarding camera and Facial motions.

- For the 2 types of auto cameras you have for now, it could be cool to have slightly more options around height/distance etc..
And mostly, a "character changing by beat" for example. When loading multiple dancers it's always focusing one and hard to switch.

- For facial/hand motions that are on a separate file, having a way to read them additionally ? Maybe I am just missing it and you already put something like that.

That's it keep up the great work 👍

**Comment by alloystorm** [comment]
Will be looking into these for the next release.

**Comment by alloystorm** [comment]
Delivered in 1.3.4
