### ISSUE TITLE
[DVVR 0.9] Motion is not playing.

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#115]
I just discover that some of the motion won't play.

**Comment by Terell2018** [comment]
Nevermind i got the motion play without the audio files by put the cache files from dvvr 0.8.83 into 0.9.1

**Comment by Terell2018** [comment]
Is there a way to play the motion without a audio files becauses some of motion i trying to play don't have a audio files.

**Comment by alloystorm** [comment]
Fixed in 0.9.3
