### ISSUE TITLE
Pro_win64_0.8.2_126 dont render textures.

### ISSUE THREAD

**Issue by KonokoMai** [alloystorm/dvvr#116]
The current release on itchi.io [Pro_win64_0.8.2_126.zip] has a problem rendering the textures on the right eye of the oculus quest 2 (only shows a black textured model). Left eye works fine and the models works fine too on the mocumocudance.

Oculus quest 2 wireless via virtual desktop wifi6
I7 7700
Rx 580 8gb
16gb ram
2x ssd 1tb.

**Comment by alloystorm** [comment]
Hi, just wanna confirm with you that is it still happening in the latest 0.9.2 release?

**Comment by KonokoMai** [comment]
I updated to the 0.9.1_155 (Im a itch.io buyer so I cant download de 0.9.2
yet) and with this version I cant load any model. Loading
Backgrounds/Scenes works fine. But I cant load any model that works on
previous versions. (I didnt modify the content folder at all, the content
folder is outside of the DVVR folder as was recommended).

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by alloystorm** [comment]
Thanks for the report. 

Are you able to locate the log file and send it to us so we can investigate further? 

The log file can usually be found in C:\Users\[Your User Name]\AppData\LocalLow\VR Storm Lab\DanceViewerVR HD\
There should be 2 files, Player.log and Player-prev.log. If you can send those files to us, we should be able to see what error is causing the model to not load. Thanks.

**Comment by alloystorm** [comment]
Hi, version 0.9.2 has just been released on itch.io, can you upgrade and see if the problem still exists?
