### ISSUE TITLE
LW loads motion while HW does not

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#118]
https://drive.google.com/file/d/10AVl0UKYtG4PghjaV4BjlPl-x7luXNuN/view?usp=sharing

so this same motion can be loaded by the LW version, while the HW cannot.  Before the update on 7APR2021, both LW and HW can load this motion just fine.

**Comment by alloystorm** [comment]
Forgot to update you, but the motion seems working fine when I test it. Can you confirm if this is still happening with 0.9.2?

**Comment by chengsta** [comment]
Thanks for the reply.  It loads now in HW, but now the actors only do the 'T' pose and nothing else.

**Comment by alloystorm** [comment]
Does this still happen in 0.9.3

**Comment by chengsta** [comment]
its fixed now, thanks!
