### ISSUE TITLE
Can't interact with the menu using Valve Index controllers

### ISSUE THREAD

**Issue by axarien** [alloystorm/dvvr#12]
I can't get my controller to interact with the menu since version 0.3.2. I've tried fresh installs and cleared the registry. The other controls seem to work, I can open the menu with the B button, move around with the joystick, etc.

I've had the same issue before version 0.2.4, but now it's back with 0.3.2.
I've only tested the HD versions because the LW versions won't start in VR mode. (I have a Valve Index HMD)

**Comment by axarien** [comment]
Still the same issue with 0.4.0.

**Comment by alloystorm** [comment]
Sorry for overlooking this issue, thought this was an old post... 

We are looking into this but since we don't have an Index HMD it can take some time. Sorry for the inconvenience.

**Comment by alloystorm** [comment]
Uploaded a test build in the shared content folder. Could you try if it solves the problem for you? 

If not, there will be a "vrnodes.txt" file generated in the executable folder after you run it. If you can send us the content of that file, it will help us further debug the issue. Thanks a lot!

**Comment by alloystorm** [comment]
Forgot the mention the test build is version 0.4.1a

**Comment by axarien** [comment]
Works perfectly, thank you!

Here is the full content of vrnodes.txt if you need it for the future:
`Index - Head
34F484D44
Index Head
IndexHMD

OpenVR Controller(Knuckles Left) - Left
45B052762
Index LeftHand
KnucklesLeft

OpenVR Controller(Knuckles Right) - Right
5159770AC
Index RightHand
KnucklesRight

Valve SR Imp S/N LHB-7C217CA8
7B369C9B8
Index TrackingReference
ViveBaseStation

Valve SR Imp S/N LHB-F1BD0139
7BDC3C088
Index TrackingReference
ViveBaseStation`
