### ISSUE TITLE
Example of bugged models + minor bugs + suggestions

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#120]
Hi !

Thanks for the awesome content as always !
- Here are again a selection of models that doesn't seem to load correctly :
https://we.tl/t-E1Xc9enHVT
There are more but it's often a series of models so tried to find one or two of each series !

- And also, motions seems to be working generally better in the 0.9_145 version, especially when it comes to using the new cernter adjustment you added recently. Just to flag out.

-A suggestion about the custom cameras , I think it is a great idea to allow ignoring rotation, but I think you might want to have an option to ignore "only Z rotation", the one that correspond to the "tilt" of the camera. The 2 other axes are needed to be in the right direction, but this one only makes it more VR-ill I think. 

Thanks and keep up the great stuff !

**Comment by alloystorm** [comment]
Hi, thanks for the examples. 
For the XPS models in your examples, you'll need to use the bone mapper to map its bones to the expected structure. You can find a demo video here: https://youtu.be/WeIYqGNJKdg

**Comment by hboxgames** [comment]
Aah thanks, I'll check that !

**Comment by hboxgames** [comment]
Hi ! 
Just to flag back, some of the XPS models that are totally still did indeed need to map the bones, but Azur lane models for example, were loaded in a very cursed rotation it seems.

Also, when using the bone mapper, I usually can't manage to get the eye contact work.

Thanks !

**Comment by alloystorm** [comment]
The problem with the PMX models in your example is a known issue that's been puzzling us for a long time. But we have a good news that we finally figured out what's going on. Will have a fix in the next release. 

Here's a screenshot of the work in progress fix: 
![takao](https://user-images.githubusercontent.com/51807035/118433763-0de65480-b71f-11eb-959b-c3d0a1596453.PNG)

**Comment by hboxgames** [comment]
You rock !

**Comment by alloystorm** [comment]
Fixed in 0.9.3
