### ISSUE TITLE
Outfit(Pantyhose) bugging on the latest version

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#121]
Hi !

Just a quick message since I noticed that on most of my models, the pantyhose setting I put were wrecked and now I know why.
Actually the fact that we now see all edges is great, since it allows to put band patterns C:

But one buggy change is that when you scale the character, it doesn't follow. And since I have many characters with different scaling I'd rather wait this to be fixed than changing settings ! (and therefore redo again later)

Thanks !!

**Comment by alloystorm** [comment]
Fixed in 0.9.3
