### ISSUE TITLE
Music beat is offseted at default

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#124]
Hi !

Thanks again for the great updates !

So I think it's a very simple error, but the music and motion were kinda offseted while playing.
I looked into settings and saw that everytime I play, it sets back to  1/3 or 2/3 beat something which seems to be default.
When I change it to 1 and refresh the song it matches.

That's it, nothing critical but would be a good fix if it's not just me !

**Comment by hboxgames** [comment]
Oh, and I always thought a sorting of "recently added" content would be cool !

**Comment by alloystorm** [comment]
Is the music offset still happening in 1.0.1? 

"Recently added" is a great idea but we don't currently track when an item is added to the library and the file updated time won't be reliable, so I guess it's going to take some time for that to happen.

**Comment by hboxgames** [comment]
I don't think this issue is still happening !! Thanks for the fix !
