### ISSUE TITLE
Offset between normal Pro version and Pro HD version

### ISSUE THREAD

**Issue by Kristof3131995** [alloystorm/dvvr#127]
**Describe the bug**
When making a scene in the normal Pro version of DanceXR and saving it. Then opening it in HD Pro version the characters are hugely off compared to the normal version. Im using version 1.0.0.229 for normal and 1.0.0.230 for HD

**To Reproduce**
Make a new scene with 2 characters, save it. Load it into the HD version.

**Expected behavior**
They should stay where they are.

**Desktop (please complete the following information):**
 - OS: W 10 Pro

**Comment by alloystorm** [comment]
Thanks for the report. 
We'll look into it.

**Comment by Kristof3131995** [comment]
> Thanks for the report.
> We'll look into it.
Figured it out what it was but I think it might need fixing anyways. When switching between the version even scenes the formation does not switch with the apropriate scene or is saved. So if you have like on scene 1 Circle formation and second scene should have Zero formation it will still have the activated formation of the previous scene - Circle. 
That is whats causing it. 
Solution is everything should be saved in a scene from offsets to formation to lightning to rotations everything if possible.

**Comment by alloystorm** [comment]
Thank you so much, will try to address this in the next release.

**Comment by alloystorm** [comment]
Fixed in 1.1
