### ISSUE TITLE
Moving actors in z axis, allow camera y axis rotation, displacing the vr camera backwards, and keyboard rebinding

### ISSUE THREAD

**Issue by GodfreyZ** [alloystorm/dvvr#128]
Hello, I would like to request 4 features:

1. To move actors on the z axis plane, up and down, in order to place actors above or below objects like tables in a stage.

2. To allow the camera to have y axis rotation in normal and vr mode (aka being able to look down towards ground or up towards ceiling through controller/keyboard rotation

3. To allow rebinding the controls on a keyboard to have more customized control. Being able to use the mouse in virtual reality would also be a plus, similar to how mocumocudance worked.

4. The vr camera also feels like its slightly in front of the actual eye position, so when leaning into objects/actors, it ends up clipping into them even though I feel my position to be still far away enough from the actors/objects and not inside of them. Attached is a crude drawing describing this issue.
<img width="468" alt="camera distance" src="https://user-images.githubusercontent.com/4412556/125438420-08bfffe5-4fe2-4a20-b08f-cf22b6aa66cb.png">

Thank you very much!

**Comment by alloystorm** [comment]
Thank you for the suggestions and the drawing. We'll look into these.

**Comment by alloystorm** [comment]
Most of these are delivered in 1.0.1 release. Closing this issue now and feel free to let us know if anything is not working as expected.
