### ISSUE TITLE
XPS model fair & cloth stiff issue

### ISSUE THREAD

**Issue by xps2020** [alloystorm/dvvr#129]
With the version 1.01 HD Pro, XPS model fair, cloth and outfit are very stiff like sticks, how to solve the iusses? If this is need additional map, how to should do that?

**Comment by alloystorm** [comment]
By default XPS does not have physics enabled. You'll need to use the physics tab to enable physics simulation on certain parts of the body by selecting appropriate bones. 
However the current solution is not perfect, it mostly only works on simple models without too much clothing & hair parts. Will continue to improve on that in the future.
