### ISSUE TITLE
Permanent gloss.

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#13]
Models are glossy.  gloss slider doesn't work.  You have to go into the textures and turn it down manually, but then when you exit and hit play, it's back to full gloss.

**Comment by alloystorm** [comment]
I tested this and it seems working fine. 

With the "Gloss" slider, is the toggle in front of it ticked? 
Also, you can try removing the config json file for the model to reset its config values. It can be found in the model folder and has the same filename but with .json extension.
