### ISSUE TITLE
Broken Spine issue

### ISSUE THREAD

**Issue by JoJCeeC1998** [alloystorm/dvvr#133]
some xna models seem to have a broken spine. was wondering if anyone knew how to fix this issue
![DanceXR_P4sgXuRNYv](https://user-images.githubusercontent.com/64820130/130011801-6805939f-5881-457b-b2bf-019cbcb9fe70.png)

**Comment by alloystorm** [comment]
Do you have a link to the model? Will have a look.

**Comment by JoJCeeC1998** [comment]
link to the model https://www.patreon.com/posts/54549751

**Comment by alloystorm** [comment]
Tested it. This model now works slightly better in version 1.1 thanks to the updates in the skeleton control but there is still some issue around the waist. Will investigate further.
