### ISSUE TITLE
what is Motion Smoothing -> Physics suppose to do?

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#135]
If you activate Motion Smoothing-> Physics some bones react strange (probably not what they are suppose to do).

**To Reproduce**
Go to “Motion Smoothing” of your Caracter and enable “Physics”.
Then Play a song.
Strange things will happen (best with another character next to it (with the option off) as reference).

**Expected behavior**
I have no Idea what this button is suppose to do.

https://user-images.githubusercontent.com/85415360/130821459-b1f6564e-71f3-4d9c-9f6a-4f182e875213.mp4

It even continues after the song is stopped (last 14 sec of vid.).

https://user-images.githubusercontent.com/85415360/130821606-e7ed261b-ae19-4f83-a9e6-3ecff87fc0da.mp4

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome] (why?)
 - game Version [1.0.0.229]

[Player.log](https://github.com/alloystorm/dvvr/files/7048205/Player.log)

**Comment by alloystorm** [comment]
Motion smoothing reduces sudden changes between keyframes. The physics mode in there is an early attempt that uses physics based method to perform the smoothing instead of linear method. That part of code hasn't been touched for a long time so if it doesn't work as expected you can turn it off.
