### ISSUE TITLE
Formation:Cirkle cize

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#137]
Would it be possible to increase the max circle formation size? The max size is a bit to small for some motions especially if you want to turn the dancers 180°.
And it would be better if you could set a Radius instead of X and Y. Because now the circle isn’t in the center of the stage.

![image](https://user-images.githubusercontent.com/85415360/130966640-488631ab-dd26-477a-894c-471121e2ab44.png)

**Comment by alloystorm** [comment]
Sorry didn't have chance working on this yet. Will update this part in the next version.

**Comment by alloystorm** [comment]
Refined circle formation settings, and increased range. 
fixed in 1.1.3
