### ISSUE TITLE
Flat shading with Outfit effect

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#145]
Hi !

Thanks for the great stuff as always !
Although it is a pain to re-do every material settings one by one, I want to go forward hoping it won't be resetted in the future.

So while trying out, here are the issues I have noticed so far (and I'll update it I find out more) : 
- The general lighting system changed, and not able anymore to have a ambient plain bright space without the dirty occlusion. Since it is generally dark, pantyhose/outfit function is more likely to be darkened (white isn't as white as before etc)
- It's linked with the issue above, but the flat material option is just awesome btw. BUT, it doesn't take in account the pantyhose/outfit so that part would stay dark alone, since as I said above, the ambient light is kinda weak and I don't use physical lights in the scenes.
- (EDIT) playing with the settings, I found a way to get a pretty satisfying light setting.. but, the lightness different between the "flat material" and pantyhose/out fit is kinda still a thing for bright colors.
- flat material for character, and stage + some material/blendshape check/unchecking etc ... aren't saving. I know you're working on it, but it's not only about SAVE/LOAD function. It would be great that it autosave like before when we make any changes on latest loaded models and load it back later.
- The random character shuffle feature is a BOSS, but it would be so cool to be able to load only favorites. There are many uninteresting elements that can shuffle right now such as accessories pmx and several draft versions of same model etc
- + "Hair" material is transparent by default, like we can see through and it's looking weird with most unrealistic models. So we have to go manually and put them all to Opaque. It would be great to be able to change how hair shader works more easily
- + Panyhose/outfit is wrapping in a weird way now. and the edges on the side of the body is pinched !
- + For me, the camera no rotation setting is still not working !
- + We still can't load the facial animation on top of body animation when they are separate
- + The "apply to group" in the material doesn't apply the tint adjustment 
- +  I don't know why the material priority changed, but it is pretty hard to work with the new priority : If a blendshape blocks a material, there is no way to make it visible (we could simply open the settings and turn up the opacity before) So sometime, there is no way to have 2 different materials at the same time because of the blendshape. Material settings should have priority above blendshape ?
-Any transparent materials can't blend to each others, they kinda glitch like if they wanted to switch on to another
-Blendshapes aren't saving/working quite correctly. I feel like when a blendshape is not FULLY ON or OFF, like inbetween value, it's ignored on load

I'll make updates in the thread if I find out something else !

Good luck and thanks for the great features !

**Comment by alloystorm** [comment]
After 1.1.2 update I think most of the issues have been address. I try to summarize the ones that are still outstanding:

1. Flat shading with Outfit doesn't work as expected
2. Camera rotation issue
3. Facial motion in a separate VMD (feature request)

The other 2 have their separate issue already so I'll retain this thread for the Outfit flat shading only.

**Comment by hboxgames** [comment]
OH yeah, thanks for the summary !

**Comment by alloystorm** [comment]
Fixed in 1.1.3
