### ISSUE TITLE
Crash when hitting B running in VR

### ISSUE THREAD

**Issue by superlime** [alloystorm/dvvr#146]
**Describe the bug**
Launching 1.1.1 HD Pro, app seems to start fine and loads into the environment.  Controller renders as expected and reflects movement in real space.  However, app crashes immediately after hitting B.

**To Reproduce**
1. Launch app
2. Wait for it to finish loading
3. Hit B on controller
4. Observe crash back to SteamVR portal

**Expected behavior**
Not crashing.  ;)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - VR: SteamVR 1.19.7 (another user observed same behavior with 1.20.3)
 - HMD: Index
 - Controller: Knuckles

**Additional context**
LMK if there's additional logs or info anywhere you'd like me to collect.  :)

**Comment by alloystorm** [comment]
Can you test version 1.1.2 and see if the problem still exist? 

Previously there was a problem when you don't have motion in your content library and you hit the next motion button. This has been fixed in 1.1.2 and I wonder if this is the root course of your crash issue.

**Comment by superlime** [comment]
Sorry for slow reply on this.  Definitely still hitting the problem with 1.1.2.  Have a pointer to docs or anything on what logs you'd like me to pull?  Happy to grab them, just not sure what you need.  :)

**Comment by superlime** [comment]
@alloystorm still hitting this.  can you give guidance on what logs you need?
