### ISSUE TITLE
Remove Scale Limits on Actor, Stage, and Camera Height

### ISSUE THREAD

**Issue by AlienPolygon** [alloystorm/dvvr#147]
Hello, please allow us to enter a number without arbitrary restriction on scale settings as well as camera height settings. If I were able to make the change myself, I would.

**Comment by alloystorm** [comment]
Actor scale range has been increased in 1.1.2

**Comment by alloystorm** [comment]
Will increase stage and camera height setting range next.

**Comment by alloystorm** [comment]
Fixed in 1.1.3
