### ISSUE TITLE
Two Versions develop for MMD and XPS

### ISSUE THREAD

**Issue by xps2020** [alloystorm/dvvr#151]
Thanks for the great software, and update, and improvement!!

It seems that Ver.1.01 is very friendly for XPS. 
Ver.1.1 is good for MMD but not good for XPS. 
I have a lot XSP models working well in 1.01 but even not loading in 1.1 
UI is changed to a simpler texture operation and XPS clothes moving is not smooth as 1.01 due to physical engine changed (I guess). 

So would you develop two versions, one for MMD like 1.1, and another one for XPS like 1.01?

**Comment by alloystorm** [comment]
We had a review of the code changes in that part but didn't find any major differrences between 1.0.1 and 1.1. 

Can you share a model with us so we can load it in both versions and maybe we can figure out what's wrong or at least suggest a set of setting values that work better. Thanks.

**Comment by alloystorm** [comment]
Made some change for this in 1.1.2. 

Reduced collider size and updated default values, it should now work similar to previous versions. Have a try and let us know if it helps. Thanks.

**Comment by alloystorm** [comment]
Closing this for now, feel free to reopen if it is still not working as expected.
