### ISSUE TITLE
Blendshape vs Material Alpha

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#154]
Hi !

Thanks for the great features as always !

I mentionned this before in the BIG thread of issues ... Then I wanted to point out this one more in detail with some images.

So first thing, I remember the way it was working before : Even if something was hidden by Blendshape, it was simply "alpha to 0" in material settings, so we could force it back up to show the material.

Now, if a blendshape hide something or is hidden by default, there is no way to get it back visible.

Here is a character with her clothes
![Screenshot_3](https://user-images.githubusercontent.com/76269190/139837294-d74b1396-d924-45eb-adb1-2f16d6a115c6.png)

And here is without her clothes
![Screenshot_4](https://user-images.githubusercontent.com/76269190/139837338-7c707314-f0c6-45e6-9f51-8b69c40610de.png)

I wanted this mecanism back because sometime blendshape sliders simply UNDRESS totally, and I want to keep some elelments like shoes so it was annoying.

But with this character, there isn't even any blendshape to switch her, or show her nipples and vagina. It's just hidden, that's it. In version "1.0.1.265" I think this was working great by alpha leading the visibility.

Here is the visual of that old version. As you can see, the outfit pantyhose is also working way better, new one is broken somehow.
![Screenshot_6](https://user-images.githubusercontent.com/76269190/139838475-56787303-5930-4b00-8d99-c0e2e66c5aa1.png)

Maybe the analyse I'm doing is somewhat false, and you'd find a better solution to this. So let me send you the concerned model !

https://we.tl/t-p95fYfdmEy

Thank you !!

**Comment by alloystorm** [comment]
Thanks a lot for your description and the model. 

I had a look and the model looks alright to me, her cloths are renderred correctly. 

Let me explain the alpha settings a bit further. 

Previously there was only one alpha value. And morphs, material settings and optional items were all fighting to control the same value. This led to unpredictable results. 

From the last version the alpha value is split into 3. One that you can control in the material group, one for the morph and optionals, and last one is in the individual material settings. These 3 alpha values are multiplied together and the result is used as the actual alpha value applied to the material. This is to allow individual control of transparency in different places. 

However this also means if you turn any of the 3 to 0, it will always be invisible no matter what the other 2 values are. This can be confusing sometimes... 

Can you check if you have either the group alpha or the material alpha set to 0? By default they should all be 1.

**Comment by hboxgames** [comment]
Oh hi !

Maybe i didn't explain clearly enough what I am trying to achieve !
So my first image is just to show how the model is shown with clothes in latest version.
The second one is the one problematic, since nipples and vagina are hidden in some materials and there is no way to make them visible !

Last image was what I was able to achieve in one of the old versions,and what I'd like to make. Using no morph, just by using visibility and alpha of materials, I could choose the part of the clothes I want to show as well as making the "nude body"visible at the same time.

So from what you are saying, the fact that any of those 3 is set to 0 to make it invisible is the problem point. Since it could be blocked by morph or something else whereas I would like to have full control to show stuff in material settings.

**Comment by alloystorm** [comment]
I see your point. 

I guess we can change the formula to this:
finalAlpha = groupAlpha * morphAlpha + adjustAlpha
The range of adjustAlpha will be -1 to 1, with default value 0
So by default the result of groupAlpha x morphAlpha controls transparency. 
And on top of that you still have the freedoom to increase transparency by setting adjustAlpha above 0, or decrease it by setting adjustAlpha below 0.

**Comment by alloystorm** [comment]
The above mentioned formula is implemented in build 373.

**Comment by alloystorm** [comment]
Closing issue now, feel free to reopen if it is not working as expected.
