### ISSUE TITLE
Crash when hitting button B on Valve Index Knuckle controller

### ISSUE THREAD

**Issue by alloystorm** [alloystorm/dvvr#159]

**Comment by alloystorm** [comment]
Initial assesment is that this maybe an issue with OpenXR plugin and / or the Unity 2021.2beta version we are currently using. Since the crash does not originate from application code. 

There is a major problem blocking us from upgrading to latest production version of 2021.2, once that issue is fixed we'll upgrade and hopefully this issue will resolve itself.

**Comment by alloystorm** [comment]
Since we don't have Valve Index at hand so can't verify this, but the Unity upgrade is done in the 1.2.2 release and hopefully this issue is solved in that release. 

Can someone confirm if the crash is still happening?

**Comment by IngenVR** [comment]
Hi!
Thanks for the development.
I tried it with DanceXR HD Pro _ win 64 _ 1.2.2.480 and it did not crash in my Valve Index and PC environment.
