### ISSUE TITLE
When SSR is ON there is a ghosting issue between the models and the surfaces. Only a chrome model seems to be fine.

### ISSUE THREAD

**Issue by Nyexxi** [alloystorm/dvvr#160]
When SSR is ON there is a ghosting issue between the models and the surfaces. Only a chrome model seems to be fine.
It happens in any surfaces or stages.

Attached image
![Screenshot1](https://user-images.githubusercontent.com/17002027/145272168-1b36b75e-c9f0-4652-8a0b-15912322a21d.jpg)

**Comment by alloystorm** [comment]
This is defect that comes with screen space reflection. Will try to open up more settings to fine tune the reflection effect in the next version but to eliminated this defect completely you'll need to switch to either the probe reflection or raytracing.

**Comment by alloystorm** [comment]
Added more setting to fine tune the reflection in 1.2.0

**Comment by Nyexxi** [comment]
Nice. I am checking them now. Thanks for the update.
