### ISSUE TITLE
More shotcut with Keyboard and the bigger flex menu is requird

### ISSUE THREAD

**Issue by xps2020** [alloystorm/dvvr#162]
If my understanding is right, the shortcut was able to set with a joystick, hope it could extend to keyboards. 

Also, more functions need shortcuts to be covered such as "setting of models", "lights", "Setting of the stage"   and others

Last, about the menu, is it too small for 4k full screen? hope it could be bigger and flexible, better just near the models, not be always on the corner side.

**Comment by alloystorm** [comment]
Will make menus scrollable and increase height.

**Comment by alloystorm** [comment]
Fixed in 1.2.2
