### ISSUE TITLE
Menu about assign different motions to different models

### ISSUE THREAD

**Issue by xps2020** [alloystorm/dvvr#163]
When need to assign different motion files to different models. just feel about the whole menu shall be easier to operate, not have to go with each model's menu to find the right one, it can be done from the music/motion menu to assign different models. 

When it needs to assign all models to the same motion again, it should be a menu to "ALL models" instead of changing from each model's menu.

**Comment by alloystorm** [comment]
This will be avaialble in 1.3.0

**Comment by alloystorm** [comment]
Published a preview video last night and you can see the new motion menu in action.
