### ISSUE TITLE
Feature request: Third color for “Outfits”

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#165]
It would be really nice to be able to put A third color on the clothing between the other 2 that already exist just like in the immage(whitch is possible becouse of a bug (https://github.com/alloystorm/dvvr/issues/164#issue-1088851200))
An sort of changeable fade between the colors would also we nice so you can also have smooth transition between the colors. Also the line with of the 3. Color should be changeable just as the width of the transition.

![image](https://user-images.githubusercontent.com/85415360/147421341-6e59d282-4051-4a7c-8a88-8943dedafd09.png)

![image](https://user-images.githubusercontent.com/85415360/147421783-124075d3-6b7e-4cff-ac95-54ca31158f1f.png)

**Comment by alloystorm** [comment]
Hi, do you mean achieve color gradient effect or do you want the color to change over time?

**Comment by tobbi64** [comment]
An color gradient effect.

![image](https://user-images.githubusercontent.com/85415360/151710559-bd5b1784-1fc0-4d1c-b178-7dc5112e3345.png)

An Third collor On the border between the first and second collor (with changeable width). And a color gradient with changeable width.

**Comment by alloystorm** [comment]
This is being worked on for the next release. Stay tuned for more details.

**Comment by tobbi64** [comment]
Thank you it looks really good. 

Would it be possible to add a link function so that multiple characters use the same outfit and if you change it by one of the characters it also changes the others? This would also be nice with other options (Dildo, Bike). Because if you have 10 models and the should all have the same outfit/dildo/… and you change it, you have to copy it to all the other models which takes quite some time.
So it would be really nice if you could link Specific parts of the characters together.
