### ISSUE TITLE
Some model "tilting" in a weard way

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#166]
Hi !

Thanks for the great features as always ! Can't wait for the next update.

By the way, I have noticed this issues which, if I remember right, existed long while ago.
So mostly for some "shorter" models, but sometime randomly, some models have legs moving further than their body, which results on having them "Tilted" like they want to streched all around the movement direction.

Keep up the great work !!

**Comment by alloystorm** [comment]
If you could provide an example that would be great. 

I do remember there was an issue with scaling wasn't set correctly between the skeleton and the model. But I thought this was fixed some versions ago.

**Comment by hboxgames** [comment]
I roughly remember this was something you wetn through as well ! So I was surprised it came up again with some of the latest versions .. like 3 versions ago maybe
https://we.tl/t-lH1cJbpBa8

Here is a video of example, basically any "shorter" models have the issue harder, but taller models also have

**Comment by alloystorm** [comment]
Fixed in 1.2.1
