### ISSUE TITLE
Black out when looking at some materials/models ?

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#167]
Hi !

Thanks for the great feature again !

This time it is a bug that was also on the last version it seems. But not in some other old ones.

Some models, when looking toward them, make the screen just black out like if it was a horror game. Pretty scary actually !
https://we.tl/t-4J5TrEdUC2

Here is an example of a series that does that

Hope you can find out what's wrong !

Good luck and keep up the great stuff !

**Comment by alloystorm** [comment]
This is caused by "NaN" errors due to certain incorrect values in the model. 

Previously we have "Stop NaN" option turned on which will workaround this problem automatically but it comes with a little bit performance penalty. In the 1.2.0 release we turned if off by default but you can find the option in "Settings -> Options -> Workarounds" and turn it on if you have models that cause black screens. You can leave it on at all times if performance is not an issue.

**Comment by hboxgames** [comment]
> This is caused by "NaN" errors due to certain incorrect values in the model.
> 
> Previously we have "Stop NaN" option turned on which will workaround this problem automatically but it comes with a little bit performance penalty. In the 1.2.0 release we turned if off by default but you can find the option in "Settings -> Options -> Workarounds" and turn it on if you have models that cause black screens. You can leave it on at all times if performance is not an issue.
Oh I see ! Thanks for the fix !

**Comment by hboxgames** [comment]
Hi !
Just reopening the issue since it is connected.. Actually the option for the "workaround" solved the blackout indeed.

But these series of models aren't working correctly anyway in terms of materials. Though they were totally normal numerous versions before.

With the last model I sent you, the model was having issue with "transparent" material not showing etc. But most materials works with transparent material best as a major part. I actually didn't even understand why it was so broken.

And for this one here, in the same series of models, the "pantyhose outfit" would wrap in a very weird way and make some odd patterns.

https://we.tl/t-b82uEtA806

Hope you can find out what's wrong !

Keep up the great work //

**Comment by alloystorm** [comment]
Hi, are you able to post a screenshot showing what you mean by "transparent material not showing"? I had a look at the model and it looks alright to me... maybe just because I don't know what it should look like...

**Comment by hboxgames** [comment]
Of course, here you go !
https://we.tl/t-e6GKIBGhNt

so basically, some things doesn't show first.. and no way to get them showing unless I put to "opaque". But opaque material is limited, AND always doesn't show at load so I gotta go in editor and check /uncheck so they show ... Well a little mess

And you can see the problem with the outfit as well there !

Thanks !
