### ISSUE TITLE
Stage display limit issues.

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#169]
When using a large stage, objects in the distance are not displayed correctly.
First image is from HD Creator win64 1.2.1.452.
The same problem seems to occur in older versions.
Second image is from PmxEditor.
![screenshot-220202-235658_1](https://user-images.githubusercontent.com/58618176/152685398-fc19b4e7-4614-4115-bd93-3b5c10658e7a.jpg)
![6841684686464](https://user-images.githubusercontent.com/58618176/152685405-f09de207-8dad-42fb-b6c9-2ef4632be7ec.jpg)

The point where the compressed objects overlap is broken when the viewpoint moves.

https://user-images.githubusercontent.com/58618176/152686686-0229d782-2d92-4983-816c-1a889e2472bc.mp4

**Comment by alloystorm** [comment]
Will be fixed in the next release

**Comment by alloystorm** [comment]
Fixed in 1.2.2

**Comment by IngenVR** [comment]
Thanks for the fix! It's working fine!
