### ISSUE TITLE
In the long dress pmx model, the dress always  through  the legs out

### ISSUE THREAD

**Issue by beavermarine** [alloystorm/dvvr#174]
In the long dress pmx model, the dress always  through  the legs out(especially with the wide motion). 
I`ve tryed with changing gravity or "step per second" and it`s useless for the problem.
Btw, may I suggest if you could please add another lighting rending mode(anime style, like MikuMikuDance)? That must be popular with lots of people.

**Comment by alloystorm** [comment]
In general the Unity physics engine is less stable than bullet physics used in MMD. For complex PMX models the result can be quite different. Plus the way physics are setup can be very different from model to model. So there is no one size fit all solution for this but we can look into individual models to see if there's a setting that can make it work better. 

If you can send us an example of your models and we'll be able to have a look.
