### ISSUE TITLE
Outfit all changed, and previous versions

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#175]
Hi !

Thanks for the great updates so far

so actually, I kinda love the new feature on outfits to put those patterns and everything. Looks pretty great !
One problem is that it broke every settings on my saved characters, so I'll have to adjust them back one by one again. I would have been great if the feature was just added on top without breaking but well, I guess it's like that. 
Also, the patterns are ON by default and can't be OFF ? What I had to do if I don't want them, is to lower the thickness of the lines. Am I missing some options to easily turn off ?

Lastly, since I have some earlier version with everything working fine and saved, I tried to open. And all previous versions are Broken now ! I'm just having a blury sky, stuck hands and that's it. Do you know why this is happening ?

PS. deleting config did actually make it possible to open older versions once .. but I dont understand why the new version affect this at all ?

Thanks !

**Comment by alloystorm** [comment]
The option to set pattern off is implemented in 1.3.2, Select "none" from the pattern options. 

I totally understand the frustration when updates break things you saved before. But for a complex functionality like "Outfit" the shaders, programs and saved settings have to all work together to make it work. To maintain backwards compatibility is very hard. I think it should have reached a relatively stable state with 1.3.2 release and if next time we are making breaking changes to it we should put it in a seperate feature. Kinda like what we did for auto dance and auto dance 2. 

In terms of data compatibility, from time to time we need to add new data to support new features. Sometimes this can break compatibility and it is often very hard to discover and debug this kind of issues. We should be more careful in this after learning quite a few lessons...
