### ISSUE TITLE
Dance motion issue

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#176]
I was wondering why one part of the dance motion moves differently from MMD.

The image below shows the dance motion at around 1m32sec.
In MMD, the left leg is up, but in DanceXR, the left leg is not.
![0055](https://user-images.githubusercontent.com/58618176/170823568-71981c5a-cff0-466d-999d-f932d10d529f.jpg)

I checked and it seems that the "left leg IK master" and "right leg IK master" of the bone used in this dance motion are not converted in DanceXR.
![00011](https://user-images.githubusercontent.com/58618176/170824370-724d2d4d-996a-4f6f-8460-60303c0c3a94.jpg)

I moved the left leg IK master to the initial position as a test and got the same pose as in DanceXR.
![00111](https://user-images.githubusercontent.com/58618176/170823978-e3d3dcc6-64d2-470e-89f4-4c7b692607d4.jpg)

Is it possible to add the foot IK master bone to the conversion?
I will send you a link to the dance motion file from ptreon's message.
Please check it out.

**Comment by alloystorm** [comment]
I checked the motion you sent me but it doesn't look the same as the one
you are showing above.

But I get the idea from your description. It seems the "leg IK master" is
parent of "left IK" and some motion use that to control the position of the
foot. Currently that "IK master" bone is not mapped in DanceXR.

I'll address this but it is a bit late for this release now. Will
definitely make this work in the next one.

If possible can you check again if the motion you are using is
"Gimme×Gimme"? It would be good to have that motion for verification once
we have a fix for it. You can just zip the VMD file and it should be small
enough for emailing.

**Comment by alloystorm** [comment]
Fixed in 1.3.3
