### ISSUE TITLE
Feature request:Re-adopt auto-update of stage materials.

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#177]
I like to light up the stage.

https://user-images.githubusercontent.com/58618176/171996858-1010cd2b-0e35-4e5c-9187-9657955a6683.mp4

In version 1.3.2, it is no longer possible to make the stage material glow.
This seems to be because the auto-update setting in the Glow section, which was present in version 1.3.1, has been removed.
![1111111111111](https://user-images.githubusercontent.com/58618176/171997155-98f30f8b-11eb-4388-bac0-55bc57cb49e8.jpg)

Please re-add the auto-update setting.
If this is difficult, I request another way to make it glow.

**Comment by alloystorm** [comment]
Fixed in version 1.3.3
