### ISSUE TITLE
multiple motions not loading

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#179]
I am unable to load different motions for example guy position and girl position for sex

**Comment by alloystorm** [comment]
From what I see in my tests earlier, 
* Load 2 models
* Assign sex motion male and female to them respectively
* The motion works but they are not aligned to each other
Is that the problem you are describing? 

If so, yes we know about that issue. 
There is a workaround for now, just click on the actor icon and select "Formation" -> "Reset".
We'll fix it in the next release.

**Comment by Chrisc78** [comment]
No I am talking about other motions I downloaded from Lewd Fraggy, you can't load two different motions at the same time for male and female motions.
