### ISSUE TITLE
Model blushing or has wierd disease?

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#180]
<img width="260" alt="new version" src="https://user-images.githubusercontent.com/107079307/172727311-02d78949-06dd-48df-a055-c9770b18b850.png">

This is what Blushing look like for the last few versions.

<img width="340" alt="old version" src="https://user-images.githubusercontent.com/107079307/172727546-8e56f439-ac64-477d-8add-fd5112d9ddcf.png">

This is what Blushing used to look like

**Comment by alloystorm** [comment]
Hi that's due to "dithering transparency" is turned on by default. 

This mode eliminates all the layer sorting issues but it does come with the above defect. You can turn it off in material settings if you model is mostly opaque.
