### ISSUE TITLE
Some texture colors not showing

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#184]
<img width="543" alt="Screenshot 2022-06-11 154922" src="https://user-images.githubusercontent.com/107079307/173202997-39fc5837-e125-4c16-b2c7-a9c55e325f4f.png">
<img width="554" alt="Screenshot 2022-06-11 160132" src="https://user-images.githubusercontent.com/107079307/173203124-e4adb366-9a8f-4925-badc-ff911ddd3585.png">

In the pmx editor you can see the Hair and Tiara colors are set internally.

<img width="307" alt="Screenshot 2022-06-11 155405" src="https://user-images.githubusercontent.com/107079307/173203209-d372b34e-1cad-4221-94dd-a454140cb2b1.png">

In DanceXR the Tiara shows the color but the hair is white. and her Blushing looks like she has a disease.

**Comment by alloystorm** [comment]
What's the name of the model? 
This might be related the "WAY" model issue we discussed in discord. It would be good to have the model to verify the fix.

**Comment by Chrisc78** [comment]
In the email I sent it was Sailor Mars and Sailor Venus both with white hair.

**Comment by Chrisc78** [comment]
While your looking at them look at Sailor Jupiter, somthing is not loading right with her Rose Earings

**Comment by Chrisc78** [comment]
If you want some more good samples for this look at these free models.
https://fantia.jp/fanclubs/23328/posts?tag=ModelDL

**Comment by alloystorm** [comment]
This will be fixed in the July release.

**Comment by alloystorm** [comment]
Fixed in version 1.3.3
