### ISSUE TITLE
View VRoid Characters

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#186]
I found an app on my phone called Doll Dancer that uses PMX files and vroid files.
I think the ability to view VRoid characters in VR with DanceXR would be a huge asset to the app.
https://hub.vroid.com/en/tags/R18
Most of these characters you can download 

I just noticed the other VRM request

**Comment by Chrisc78** [comment]
I found this program to convert vrm to pmx. https://bowlroll.net/file/267190
 it works really good except you have to use another program to set the physics that I can't figure out how to use. https://bowlroll.net/file/267191

**Comment by alloystorm** [comment]
Thanks for the links. We will need to do some research to see how much effort this is going to require.

**Comment by Chrisc78** [comment]
After I use the vrm to pmx software I mentioned I can choose to turn off pmx physics in DanceXR and use the Physics setting that were made for xps models.
 
<img width="424" alt="Screenshot 2022-12-11 151131" src="https://user-images.githubusercontent.com/107079307/206927467-b4c4d646-082e-416f-9d4a-459d073d0643.png">

**Comment by Chrisc78** [comment]
This request is duplicated.
 So I closed the request. https://github.com/alloystorm/dvvr/issues/150
