### ISSUE TITLE
Feature Request: Load two motions files at same time

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#187]
I find once in a while when looking for motions that there are sometimes two files, one motion file for the dance and the other for the mouth movements.

**Comment by alloystorm** [comment]
Right. This is actually on our list for some time, but it is still in the UX design phase since going from single selection to multiple selection requires quite a bit logic change. It doesn't look like this is going to arrive in July but will definately be a priority for August release.
