### ISSUE TITLE
When tagging something, all the tags that appear should be in alphabetical order

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#194]
the tagging system works great.  So it's not really a bug, so I put it in feature request.  Right now, when tagging something, all of the tags you created appears in the order of the date they were created.  I wish to be able to tag faster by having them appear in alphabetical order instead.

When loading by tags, they do appear in alphabetical order so no problem on the loading part though.

**Comment by alloystorm** [comment]
This is in the 1.4.3 update.
