### ISSUE TITLE
Physics broken in new released Steam version (HD 1.3.3.608)

### ISSUE THREAD

**Issue by ProSniperSinon** [alloystorm/dvvr#195]
**Describe the bug**
Physics broken for many models in new released Steam version (HD 1.3.3.608)

**To Reproduce**
1. Update to latest Steam ver.
2. Load model (e.g. https://www.deviantart.com/freya-vhal/art/DL-Luka-Alien-Set-890960280)
3. See chest, popping in a freaky way, other models may have hair blowing up (e.g. like a hair blowdryer)

**Expected behavior**
Physics for the model should be less aggressive. 
I've downloaded a demo of the previous ver. 1.3.2.573 and the physics was perfect on that platform.

**Screenshots**
https://files.catbox.moe/i1f0i4.mp4

**Desktop (please complete the following information):**
 - OS: Win 10x64
 - Version HD 1.3.3.608

**Additional context**

**Comment by ProSniperSinon** [comment]
Just some additional info:
Happens in both VR and desktop mode
I've also deleted the config.json file and it still persists
Physics bug happens in either "dancing" or "idle" mode

**Comment by alloystorm** [comment]
Thanks for the report. 

We had an initial look and it seems to be related to the mass of physics objects. In version 1.3.2 and before we've been ignoring the mass value in PMX definition and everything is default to 1. From 1.3.3 we are setting the mass to the correct value specified in the PMX file and this can resolve issues for certain models. It appears that this also created new problems for models that was previously working fine. 

Luckily we added "Min Mass" and "Max Mass" settings that act as a boundary for the mass value. You can actually set the "Min Mass" to 1 to restore the behaviour of 1.3.2. We verified that this can resolve the issue for the model in your link. 

We will try to find a better solution for the next release but for now we think that you can use this "Min Mass" trick to fix most of the models that has similar problems.

**Comment by ProSniperSinon** [comment]
Thank you Alloystorm and Chris for the response. I can confirm that your workaround by putting Min Mass to 1 resolves the issue with some of the affected models.
I'm not too familiar with the older versions since I only brought the software recently. But believe me I was freaking out when I loaded in that morning with that new update, haha.

The handful of models that have this bug seems to be models with parts/pieces imported from other games and then reused for MMD. I can't confirm that to be 100% but it seems to be a theme of it.
It could be bad programming on the end of the creator but indeed both 'buggy physics models' and working physics models load up fine in a normal copy of MMD so there must be something in that software that's causing both scenarios to work fine there.

At the end of the day, it's more of a compatibility issue and the less workarounds we can do for most models would be best.

**Comment by Chrisc78** [comment]
I would just automatically adjust the Min Mass setting to 1 for every model, instead I would find the perfect setting for each model.

**Comment by alloystorm** [comment]
Closing this for now as there is not much more we can do at the moment. The new version 1.3.4 increased default Min Mass value so should work a bit better than 1.3.3. 
Be asured that this won't be the final state of the physics system. There will always be futher improvements with each release.
