### ISSUE TITLE
Slight Shader issues

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#198]
Hi !

Thanks for all the great features so far 

Here are a few shader issues I am experiencing, the first one is about transparency

Most transparency, instead of being smooth, works like some grain. Here is an example 
![Screenshot_1](https://user-images.githubusercontent.com/76269190/180337979-e4a9a9fd-4003-401f-902d-68150bcaa2a9.png)

Next is how face is separate in terms of shader, which is really a mistery. Most MMD models were reacting this way
This is pretty easy to figure out when I am on a "ambient only" light environment.

Basically, the face and the body are both in "Skin" shader. So they should react the same ?
Here is the first screen before I tick anything tricky.
![Screenshot_3](https://user-images.githubusercontent.com/76269190/180337918-7f1f7a36-7a25-494c-a8c7-4de4a3368e47.png)

Then, when I tick the simple shader, only the face reacts to it. The body don't ! weird ..
![Screenshot_4](https://user-images.githubusercontent.com/76269190/180337927-88ac76bf-0cdc-4aab-8790-9c6360e5b7f6.png)

Or, if I activate the Outfit, they react both but differently. The face would eventually brighter or something.
The fact that the shader somehow changes when outfit is activated is weird too. But it was already the case before and I guess you know that. Right now I wanted to point out that the face and body are reacting differently on most models which is surprising!
![Screenshot_5](https://user-images.githubusercontent.com/76269190/180337933-1745a015-95d1-4374-b502-8373443bdc14.png)

That's all ! Thanks !

**Comment by hboxgames** [comment]
Nevermind the grainy transparency one, it was the "dithering" option causing that !

**Comment by alloystorm** [comment]
We are aware that dithering is not ideal but in many cases it is the best default option for now since many models appear inside out without proper alpha sorting. There will be further updates if we find a better solution.
