### ISSUE TITLE
Glowing not working anymore

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#199]
**Describe the bug**
We used to be able to make material/objects glow, and set a glow intensity as well as color.  But now that option seems to be gone for most of the materials in settings.  It's been that way for the last few iterations of dxr, but it just wasn't as important as other issues so it wasn't reported.

**To Reproduce**
1. Go to settings
2. go to 'materials'
3. Try to get things like eyes/lamps/clothes to glow.

**Expected behavior**
objects/materials should glow, and glow the color that you chose.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by alloystorm** [comment]
Fixed in 1.3.4.635
