### ISSUE TITLE
Stages folder

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#20]
Where do i put stages folder in because when i put stages folder inside the content folder it not show.

**Comment by alloystorm** [comment]
The folder structure should be like this:

![Capture](https://user-images.githubusercontent.com/51807035/72514741-ff75f780-38a2-11ea-938d-33084ab537b1.PNG)

**Comment by alloystorm** [comment]
Also you can find example in our content package. Let me know if you are still having issue.

**Comment by Terell2018** [comment]
I just trying it but it still not showing up.

**Comment by alloystorm** [comment]
Which version are you running? 
The custom stage feature is currently only in the private builds.

**Comment by chengsta** [comment]
you must name the folders EXACTLY as shown.  NO CAPS

**Comment by Terell2018** [comment]
i am uses dvvr 0.4.4 public build.

**Comment by Terell2018** [comment]
Maybe i just wait till release in public.

**Comment by alloystorm** [comment]
Closing this since it is not a bug :D
