### ISSUE TITLE
Skin Shader and Outfit

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#200]
Hi !

The updates are great and you are upgrading many nice features !

I had a question about the way "Skin shader" works. It's pretty beautiful how it works with backlights and sweat textures etc.
But then I am using the "pantyhose" outfit a lot, which covers part of the skin. As soon as I activate it, the skin shader doesn't react as a skin anymore. I was wondering why that is, and if there is a way to make them work together ?

Keep up the good work !

**Comment by alloystorm** [comment]
This is due to skin shader uses a different rendering mode that does not support metallic look which outfit shader requires. At the moment it is not possible to support both at the same time.
