### ISSUE TITLE
Feature request: Linking Character Settings

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#201]
Would it be possible to add a link function so that multiple characters use the same outfit and if you change it by one of the characters it also changes the others?
This would also be nice with other options (Dildo, Bike, Accessorys). 
Because if you have 10 models and the should all have the same outfit/dildo/… and you change it, you have to copy it to all the other models which takes quite some time.
So it would be really nice if you could link Specific parts of the characters together. (This should be possible if they all have the same body proportions.)

**Comment by alloystorm** [comment]
This is available in the 1.4.3 update.
