### ISSUE TITLE
Feature request:  Accessory motion data

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#203]
**Is your feature request related to a problem? Please describe.**
Someone already mentioned morphs on accessories.  However I'd like to go one step further and have accessories use .vmd motions.  Some of the accessories have sliders to open/close/transform them, and I would like them to be able to move/spin as well during certain parts of the dancing.

**Describe the solution you'd like**
Give the ability to load motions onto accessories.

**Comment by alloystorm** [comment]
Aiming to deliver this in 1.3.7
