### ISSUE TITLE
Feature request: auto translate

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#205]
Sometimes its very hard to find something because of the language (in particular morphs).
So it would be great if it could be automatically translated (to Englich)(either with an reference sheet like MMD tools for blender or just send it to google to translate).

**Comment by alloystorm** [comment]
This has been on our radar but the challenge is translations themselves and to find a good way to maintain the dictionary. We will be thinking about that but this is relatively lower priority for now.

**Comment by tobbi64** [comment]
I don’t know if this is possible but just as an Idea.
Send every text to google to translate it, and save it in an exel file.
Every word that isn’t in the exe file gets translated and gets added.
Then the dictionary is created automatically.

**Comment by alloystorm** [comment]
There is now "auto translated" morph names in 1.4.1. 

These are word by word replaced from Japanese to English so they are far from proper translation but it should give you a rough idea of what the morphs are about.

**Comment by tobbi64** [comment]
thx that will be of great help

**Comment by tobbi64** [comment]
Is it possible to add words to the translation table?

**Comment by tobbi64** [comment]
Or even better. There is an export button witch exports every word it doesn’t know. Then you can translate them and add them to the translations table.
