### ISSUE TITLE
Opening model/motion menu causes the app to freeze for a few seconds 1.3.1-1.3.4

### ISSUE THREAD

**Issue by raivaru** [alloystorm/dvvr#207]
Problem has gotten worse in version 1.3.4

**Short description:**

(Probably) When you have a lot of files/folders in motion/actor folders, opening model/motion menu causes the app to freeze for a few seconds. It happens everytime you open **motion/model menu** that has the Load/Replace sub-menu. 

**Longer description of the problem:**

When you have a lot of model/motion files in the content folder, the program freezes for multiple seconds when opening the **model menu** by either selecting the **model** or clicking the **model icon** in the **main UI**. 

Same problem also happens when opening the **motion menu** using the **main UI**. 

The problem is also present in versions 1.3.1-1.3.3 but not as bad. In version 1.3.0 and older there's no freezing.

In previous version with the problem, I could still somewhat circumvent the problem with the **model menu** by having two **models** in the **scene** and opening the **model menu** by selecting the **model**.

I suspect the problem is probably happening because of the Load/Replace sub-menu when a user has a lot of motions/models in the content folder.

In the previous versions when you had two models the Load/Replace menu was missing from the **model menu** when you opened it by selecting a **model** from the scene. The freezing only happened when you opened the model/motion menu from the main UI.

I also tried fresh install and deleting cache.jsons and settings folder from the content folder but that did nothing.

**Comment by alloystorm** [comment]
Thank you very much for your report and analysis. 

I think you are probably right, when opening the menu the items needs to be created and if you have a lot of models in a relatively flat structure it can cause a bit delay... 

We will try to optimize this in the next release. 

For now maybe you can also try grouping the models in separate sub folders so that there are not too many items in the same level.

**Comment by raivaru** [comment]
I have sorted the models to a certain extent. They're  sorted by the file extension(mmd/xps), by title, by character (if there's alot of them), by type (not r18. r18). Motions to a lesser extent, but there's should be a lot less of those anyway.

Hope you can fix this. This wasn't a problem before. Even in 1.3.0 with the newer UI(I tested with it yesterday, and there were no freezing)

**Comment by alloystorm** [comment]
Fixed in 1.3.5
