### ISSUE TITLE
I got an error when using the version on steam 

### ISSUE THREAD

**Issue by jemjom933** [alloystorm/dvvr#208]
Normally an app downloads data before you can start it , but when i click install no data is downloaded and when i click laucher it says missing data , I have reinstalled steam and changed the region is not work :steammocking:

IMG : [https://ibb.co/fvSPdbc](https://steamcommunity.com/linkfilter/?url=https://ibb.co/fvSPdbc)

IMG : [https://ibb.co/6BDWW3k](https://steamcommunity.com/linkfilter/?url=https://ibb.co/6BDWW3k)

P/s: I bought a key from another site and activated it on steam

**Comment by alloystorm** [comment]
Also which region are you in? Since DanceXR is rated adult only on Steam,
it is not available in regions like China. If you happen to be in one of
those places, Steam might be preventing you from downloading this game.

**Comment by alloystorm** [comment]
Haven't got response from the OP, assuming this is due to the adult game ban in China. Feel free to reopen if otherwise.

**Comment by alloystorm** [comment]
Can you try right clicking on DanceXR from your game list, select
"Properties..."
[image: image.png]
Then from the BETAS tab, choose either of the options and see if it works?
[image: image.png]
