### ISSUE TITLE
Support for Meta's upcoming Quest Pro headset

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#209]
I plan on ordering the headset as soon as it goes on sale in the next two months, even if it costs $2000

**Comment by alloystorm** [comment]
Yes we will support Quest Pro. 

Looking forward to color passthrough and eye tracking. 
We have implemented passthrough, hand tracking and foveated rendering in 1.3.5 and the result is very promising. With foveated rendering performance is greatly increased. With eye tracking it should be even better.
