### ISSUE TITLE
1.3.5 First Problems

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#210]
Hi !

Thanks for the great updates fixing the Outfit features and everything.

Meanwhile, Again ! All of the materials informations are completely Broken this time.
Plus, the way it's reading out the "additional objects" checkboxes seems pretty broken too.

Overall, material options are so broke it's hard to put a finger where and how exactly, I would almost suggest rewinding once and see how to improve it was working pretty well beforehand. Like things being set to "others" was breaking some stuffs that works fine in transparent, so we only had to pass them onto transparent although I didn't really get why things get onto "others" which only bothers. Now, sometime both are buggy and putting them on transparent don't solve.

I really wanna test this version further because I appreaciate the outfit feature a lot, but Loosing ALL the material settings once again and having it all broken anyway makes it pretty harsh

**Comment by Chrisc78** [comment]
Do you have the last update installed 1.3.5.**672**?

**Comment by hboxgames** [comment]
Oh there was a fix ? Will try !
