### ISSUE TITLE
Bug report: Motion Overwrite -> Rocking Motion -> Back forth. not working right

### ISSUE THREAD

**Issue by tobbi64** [alloystorm/dvvr#211]
**Describe the bug**
Under Motion Overwrite -> Rocking Motion -> Back forth
“Back and forth” moves the “Dildo” up and down instead of the hips forward and backward.

https://user-images.githubusercontent.com/85415360/188323895-452b8352-4163-4d81-9299-5e3c3a2efa8c.mp4

**Expected behavior**
I expect the hips to move forward and backward.

**Desktop (please complete the following information):**
 - OS: win 10
- Version 1.3.4.637

**Comment by Chrisc78** [comment]
<img width="223" alt="Screenshot 2022-09-05 165112" src="https://user-images.githubusercontent.com/107079307/188511451-8a087312-7b1f-4749-aaf5-4cc70e0d837b.png">

If the two controls circled in red are off the model does not rock only the dildo moves. I don't have a problem if you increase ether one of them.

**Comment by Chrisc78** [comment]
I didn't know there was a dildo under rocking motion, I also would like this fixed.

**Comment by Chrisc78** [comment]
I found something that works really well, you can use both procedural dances with motion override, You can put the model in almost any position. I'm going to try them but all procedural motions should work well.

**Comment by tobbi64** [comment]
My Idear went more in this direction

![image](https://user-images.githubusercontent.com/85415360/188944252-9dc4bb11-9a5a-49bb-8417-cf5f9c888aa9.png)

**Comment by Chrisc78** [comment]
https://user-images.githubusercontent.com/107079307/188991178-db873668-71b6-4a4b-bc33-ca511138ecc6.mp4

I want that back and forth to control the model and not the dildo, but is this kinda what you want her to do?

**Comment by tobbi64** [comment]
Exactly

**Comment by Chrisc78** [comment]
You also can you a second motion to control the face movement and sound.  
<img width="631" alt="Screenshot 2022-09-07 185543" src="https://user-images.githubusercontent.com/107079307/188997525-4cb6a784-bf8e-40bf-a978-8ad38899a49f.png">

**Comment by alloystorm** [comment]
Thanks for the screenshots and analysis. 

Looking into this.

**Comment by alloystorm** [comment]
Actually the "back forth" setting controls the movement between the actor and the object being ridden. When you have dildo turned on, this is effectively how deep the dildo goes, since the dildo is attached to the object. 

That's a poor choice of naming. Will change it to something else and add an actual front and back motion in there.

**Comment by Chrisc78** [comment]
When you create a back amd forth motion for the hips can you create a back and forth motion for the head?

**Comment by alloystorm** [comment]
Delivered in 1.3.6
Will explore the head movement in a separate story.
