### ISSUE TITLE
cosmetic cleanup needed in 1.3.6.700

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#213]
<img width="203" alt="Screenshot 2022-09-05 161243" src="https://user-images.githubusercontent.com/107079307/188510415-762c94a5-a42e-4f0e-9cc4-61657a146fb1.png">
<img width="224" alt="Screenshot 2022-09-05 161223" src="https://user-images.githubusercontent.com/107079307/188510423-d24a5783-6bdd-4f94-8eab-d503438f17a0.png">
<img width="222" alt="Screenshot 2022-09-05 161038" src="https://user-images.githubusercontent.com/107079307/188510430-5460cbdd-ffca-4604-8e18-75b72b8b4c0b.png">

In the last image the Actor Floor control is duplicated the one circled in red does nothing. the first to images just shows things that take space.

**Comment by alloystorm** [comment]
Thanks, will address in next release.
