### ISSUE TITLE
Collision problem in PMX model

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#214]
I think the body penetrates clothing easily in 1.3.3 and later versions.
collision have any problems?
Because of this phenomenon I can not move from version 1.3.2.573

![hdcreator_1 3 5 673](https://user-images.githubusercontent.com/58618176/188879055-1eedc28b-addf-43a2-a2fe-d72f90d80381.jpg)
Thanks for the great development!

**Comment by alloystorm** [comment]
The latest build 674 should have improvements in that part.

**Comment by IngenVR** [comment]
Thanks for fixing it!!
I will try the new version.

**Comment by alloystorm** [comment]
The next update will have a proper collision model that we think is very close to MMD's. Stay tuned!

**Comment by IngenVR** [comment]
WOW!
Can't wait!
Your developments are always so exciting!
Thank you.  :)

**Comment by alloystorm** [comment]
Version 1.3.6 is released. Collision objects should all behaviour correctly now.
