### ISSUE TITLE
Feature Request: Motion Overwrite -> Override Legs  -> Move Knees left/Right, Rotate Knees, and Ankles

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#216]
<img width="502" alt="Screenshot 2022-09-10 090016" src="https://user-images.githubusercontent.com/107079307/189484853-428ca8ac-7051-4de7-818b-a857128e5d72.png">
<img width="417" alt="Screenshot 2022-09-10 090155" src="https://user-images.githubusercontent.com/107079307/189484858-d74092f5-9f61-42ab-a080-683790fef13d.png">
<img width="205" alt="Screenshot 2022-09-10 090421" src="https://user-images.githubusercontent.com/107079307/189484862-2f6857ca-fc51-4df2-a321-09702c037fa9.png">

I know I'm asking for a lot but if we could get these that would be awesome.
Not having the ability to move models knees apart without moving feet prevents a lot of posing positions. The Left/Right that is there is for feet, I want to move each knee separately. I would also like to rotate each leg left/right and rotate each ankle left/right, up/down and if you do this since your at it the ability to move feet separately left/right, forward/back, up/down.

The following is my dream list of sliders for the legs
**2 sliders one for each knee, move each knee separately together/apart
2 sliders one for each leg, rotate leg left/right
4 sliders two for each ankle, rotate foot left/right, and up/down
6 sliders 3 for each foot, move both feet separately left/right, forward/back, and up/down.**

**Comment by Chrisc78** [comment]
If you download this motion every position is what I am trying to do but if I want to change the pose a little from the poses in the motion, I can't. https://ecchi.iwara.tv/videos/1z6ggsbx65u3lrljk

**Comment by aeltcxx** [comment]
I  need this feature too，please.

**Comment by Chrisc78** [comment]
Nice work on the motion override for the legs it is exactly what I wanted. you should fix the Arms and hands override to be easily controlled the same way.
