### ISSUE TITLE
Bug Report: Scale changes disporportionally for different model areas

### ISSUE THREAD

**Issue by GodfreyZ** [alloystorm/dvvr#217]
**Describe the bug**
Changing character scale disporportionally changes different model parts. For example, when reducing scale of a model, hat/hair pieces are less impacted and end up being much much bigger.

**To Reproduce**
1. Move the slider to change scale for a model

**Expected behavior**
The model should shrink/enlarge with all parts of the model proportionally changing.

**Screenshots**
https://ibb.co/X3h9qS3
As seen in this picture, when the scale has been reduced from 1.00 to about 0.300, the hat,hair,chest,back cape are extremely large compared to the rest of the model. (the inverse happens when scale is increased). This occurs to every model that gets imported, not just the example in the screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - DanceXR HD 1.3.4.635

**Additional context**

**Comment by alloystorm** [comment]
This has been fixed in 1.3.5
