### ISSUE TITLE
Desktop mode bug

### ISSUE THREAD

**Issue by MMMatchArt** [alloystorm/dvvr#219]
Software launching in VR mode no matter what option i choose at startup, even using the desktop only batch file launches in VR

https://imgur.com/a/4KZC0xN

Win 10

**Comment by alloystorm** [comment]
Please try opening the installation folder and remove both "config.json" and "license.txt", and launch the program again.

You can find the installation folder by right clicking on DanceXR from your Steam library, select "Properties", then "Local Files" and "Browse"

**Comment by alloystorm** [comment]
And if you don't mind can you send us the original license.txt file before you delete it? So we can analyse what caused this problem and avoid it from happening in the future. Thanks alot!

**Comment by MMMatchArt** [comment]
Original license file is empty

[license.txt](https://github.com/alloystorm/dvvr/files/9741711/license.txt)

**Comment by chengsta** [comment]
it happens to me too if I leave steam VR and Oculus program running, or pitool if I am using the pimax headset.  So just turn off steamvr, and turn off your oculus/vr program, then desktop mode should run fine.
