### ISSUE TITLE
Leg IK Bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#22]
i discover a bugs that leg ik not working on some motion.

**Comment by alloystorm** [comment]
Any example?

**Comment by Terell2018** [comment]
it happened on some motion left leg and right leg and both leg.

**Comment by alloystorm** [comment]
Can you send us a link to the motion file so we can have a look?

**Comment by Terell2018** [comment]
i think i can post a image but i am not sure to post it. because the motion i use was R-18 motion. here the 2 link for motion and model. and the motion use sin sack and izumi shimizu and some motion don't have a audio file.

Link: https://mega.nz/#F!bNtBySZJ!OhOWVrnE9XCa2x4MmzJkYQ

Link: https://www.mediafire.com/folder/bvyhwdun9870w/Releases

**Comment by Terell2018** [comment]
Those motion are R-18 and some motion don't have the audio. and the problem with the leg ik are:
-Blowjob
-Bath house service
-Couch cowgirl
-Dominating FJ
-Massage blowjob
-Nice rear view
-Nice rear view
-Sex on the floor
-Table sex from behind
-Table sex from behind
-Table sex missionary
-Thigh service
-What is this hard thing

Motion link: https://mega.nz/#F!bNtBySZJ!OhOWVrnE9XCa2x4MmzJkYQ
Model link: https://www.mediafire.com/folder/bvyhwdun9870w/Releases

**Comment by Terell2018** [comment]
MMD - https://user-images.githubusercontent.com/49305586/74444904-83d87d80-4e43-11ea-8936-92d0ca347a08.png

DVVR - https://user-images.githubusercontent.com/49305586/74444766-555aa280-4e43-11ea-9ddb-a256064386f7.png

**Comment by Terell2018** [comment]
Disable lag uncheck - https://user-images.githubusercontent.com/49305586/74446054-57bdfc00-4e45-11ea-8922-1e40556f671c.png

Disable lag check - https://user-images.githubusercontent.com/49305586/74446101-67d5db80-4e45-11ea-9b81-34ad7612a2ed.png

Leg IK not working on some motion event check and uncheck disable leg ik is not working event.

**Comment by alloystorm** [comment]
Figured it out. We will add an option to force IK on to solve the issue. 

The reason it happens is that in those motions the IK bones are not moving at all (by design) and the current logic turns IK off in this scenario.

**Comment by alloystorm** [comment]
Also, the next version will be able to play motion without audio files.
