### ISSUE TITLE
Two issues - outfit and Texture

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#220]
Hi

Issue 1 :

I've tested the latest versions, and since you have added the "others" texture, it has got very annoying basically. 

Here is why

Most textures were assigned to "transparent" before. Which allowed us to have something NOT transparent if it didn't have transparency, if it DID, then we wouldn't have black or white patches everywhere.

Now since you've added this "others", a Whole lot of textures are automatically assigned to Others, and have no transparency which we have to manually set, which can be like 40-50 textures to set manually per character....
Did this Others really bring something useful ? It it did, then it would be great to have a way so that textures are by default rather in "transparent" and not "other"
From simple things like Highlights and blushes.. to frills on dresses.. it is a nightmare to switch them all back.

Issue 2 :

It is pretty cool that we can have that personalized patterns back on outfits ! Thanks for that.
By the way, I have noticed something weird and interesting. 
When you load multiple characters, and try to have patterns on each of them, it gets glitchy.
Some will just loose their patterns, others will get new ones and mix from on to another etc. Maybe something to do to stabilize this ?

That is it !

Thanks !!

**Comment by alloystorm** [comment]
The "Others" category is designed for quickly changing material settings that are not recognised categories like skin, hair, eyes and lips. By default it is off which means it won't override anything. Being in the "Others" category does not break the transparency setting. If the material is supposed to be transparent it should remain that way even when it is in the "Other" category. Previously there's a bit problem in the UI that made changing transparency difficult. This will be addressed in the next release and the "Others" category settings will have transparency setting as well so you can change all materials' transparency in one place. 

About the outfit issue we are still looking into it.

**Comment by hboxgames** [comment]
Hi ! 
Thanks  for the reply !
I understand what you mean, then I bet there were some issues about the shader itself, since it did have a difference with the "transparent" shader.
Now that you say that, sometime **Others** shader had transparency, like for highlights etc, then sometime it was necessary to change it to **Transparent** in order to have transparency.
Actually **Transparent** seemed pretty polyvalent for any kind of not recognised stuff. Wouldn't it be more useful to put them by default, and leave  **Others** as a customisable ?
For example, if none of the materials are put in others, it would be pretty useful to manually switch every metalic parts to  **Others** Manually and give them metal texture all at once.

Either way, being able to change transparency on  **Others** will be useful too I guess ! Looking forward !

Thanks !!
