### ISSUE TITLE
Feature Request: idle mode options

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#221]
1. An option to stop the model from moving side to side, this is needed to create motions with motion override.
2. An option to play .WAV files when the model is in idle mode,  with an option to repeat the audio in a loop or just play once, for motion override again.
3. The ability to use a Second motion with either Idle Mode or Motion Override for face motions only, Eyes, lips, Tongue, and Eye Brows

**Comment by alloystorm** [comment]
Most of these will be available in the next release except the wav audio part.

**Comment by Chrisc78** [comment]
I think I should be able to load audio with the Second motion.
