### ISSUE TITLE
Bug with Second Motion

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#222]
This is mostly for sex motions, If I load a motion for the main motion and use motion override to get the model to change the models posture. If I use a Second Motion to control the face motions Eyes, Lips, Tongue, Eye brows it changes the models posture I used motion override for.

If possible I think Second Motion should only look at the face motions Eyes, Lips, Tongue, and Eye brows and ignore everything else.

**Comment by alloystorm** [comment]
This can be a bit tricky but I'm guessing you can also try swaping the 2 motions since the second motion is applied after the first, it can override motion from the first if it also controls the same bone. But if you swap the 2 then it might work as you wished.

**Comment by Chrisc78** [comment]
If only I can find good motions that only control the face

**Comment by Chrisc78** [comment]
Being able to select the bones each motion controls is perfect, I didn't really try it yet though.

**Comment by Chrisc78** [comment]
This is way better then I ever imagined, I can just turn off bone movement for motions altogether and only use Morphs which is exactly what I wanted.
