### ISSUE TITLE
Feature Request: More detailed Dust settings.

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#224]
I would like additional settings for Dust.

1:The amount of dust.
2:Direction of dust movement.
3:Glow up the dust.
4:Adjustment of the color of the glow.
5:Change the shape. Snow, fallen leaves, crystals, etc.

**Comment by Chrisc78** [comment]
Falling Snow would be cool it should be like rain so you can change the intensity, blowing direction and size of the snow

**Comment by alloystorm** [comment]
1.4.2 particle system
