### ISSUE TITLE
Feature Request: Scroll Bar for menus in VR.

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#226]
Any menu that has more then a certain number of items gets a scroll Bar to view more.

**Comment by chengsta** [comment]
I'd like to add an option to the scrollbar:  location memory.  I have a super long list of models and motions.  And when i switch, it starts all the way back from the top, and i have to scroll for a very long time, and it sucks.

**Comment by Chrisc78** [comment]
The issue I was having is now fixed, a scroll bar is no longer needed.
