### ISSUE TITLE
Accessory position save/load button

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#227]
**Is your feature request related to a problem? Please describe.**
When I try to load a action motion for my accessory, it deletes/forgets the original position I had it at.  So when I remove/change accessories it goes back to 0000 and it is a pain to reposition it every single time.  
**Describe the solution you'd like**
Please put in a 'save position for this accessory' button in the accessories tab.  And also have a 'load accessory position' button as well.  And have it autoloaded whenever you switch to that accessory.

**Comment by alloystorm** [comment]
Restoring accessory position / rotation should be fixed in 1.4.1
