### ISSUE TITLE
Outfit options

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#228]
Hi !!

Thank you for the great features, excepting the collisions that are still pretty glitchy on mmd models, it's getting really cool !
I saw that you added an option to use bone by bone system for mmd models, I should test it out !

Right now I was just wondering if we can go forward and improve the look of the Outfits

**1 -**  pretty simple : if we could add back a lost feature on outfit that is the "glow". Adding it in the material does nothing now, whereas it made it brighter before. It is pretty useful to get the coloring I want, especiallu when using white surface on top of simple shaded characters for example :)  I don't know why it was lost since it was active versions before.

**2 -** I was thinking that it would be awesome to have improving options about the sheerness of the highlights on the outfit shader.
What would make a material sheer, it could be some simple bump texture like this
![8QyOANkEVR0eJypoS1RHG6PH](https://user-images.githubusercontent.com/76269190/201658186-fc4b8566-f199-455c-8269-f816e75515a4.jpeg)
![97456153_p0_master1200](https://user-images.githubusercontent.com/76269190/201658190-af0c6208-2a41-4347-9bd6-9df62e974d8b.jpg)
![99160951_p0_master1200](https://user-images.githubusercontent.com/76269190/201658195-e6c632b9-6b0b-427b-b050-4c147543136a.jpg)

And/or horizontally scattered highlights like this

![07q7o520c3iv5slualikbzuwc14z](https://user-images.githubusercontent.com/76269190/201658351-d3d679d4-aaab-44ae-bd13-aaf7f8251599.jpeg)
![93428979_p0_master1200](https://user-images.githubusercontent.com/76269190/201658356-c3c9a341-934e-425f-8784-2b7c73c80a40.jpg)
![98398517_p0_master1200](https://user-images.githubusercontent.com/76269190/201658359-47ef596f-9e29-430d-acd5-7d07c6c6b31a.jpg)

I thought it could make them look really cool and customizable !

I explored quite a bit in the different options but I don't think these were achievable with the actual version. Let me know if I'm wrong !

Thanks again looking forward for the next version !

**Comment by alloystorm** [comment]
Thanks for the reference photos. We'll do some research and further improve this feature.
