### ISSUE TITLE
Ability to name saved scenarios

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#23]
This isn't urgent, but what I would like to see is the ability to rename, or even put tags on scenarios as you save them.  Sure, you could go straight to the folder and just rename it there, but if you're saving dozens of scenarios all at once, you won't know what's what.  The automatic naming is just terrible.  For example in MMD, if you save a scenario, a popup will ask where you want to save it, and you can rename it right then and there.  

Normally I don't save scenarios, but your new update made it necessary to save time with multiple actors.  It's quicker to just pull up a scenario with multiple actors and motions already loaded, and in the right position.  It takes me roughly 5-10 minutes to start a 3-person motion dance motion, and I would like to just save it once I'm done with the scenario rather than start all over.  thanks and sorry for the rant.

**Comment by alloystorm** [comment]
Yes I agree that it is a bit annoying. We try to avoid text input since the virtual keyboard is clumsy to use in VR but it seems it has to be done anyway. Will add keyboard input in the future.
