### ISSUE TITLE
shuffle button problem

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#230]
Hi !

Thank you for the great features so far :)

I was trying out the "random character" button recently, and noticed it was looking buggy.

Months ago, I asked you how to make this work and you told me that for example, if I load a character from "favorites" or a specific folder, or Tag, the "random character" button will automaticly search for something inside randomly. which made it possible to shuffle only among favorites for example.

Right now it looked like it's either loading from everything existing, or only a specific folder. Not sure.. but apparently not working for favorites and tags anymore.

could you have a look and check about this ?

Thanks !!

**Comment by alloystorm** [comment]
This appears to be working fine for me, what are the exact steps you did and why do you think the shuffled model is not from the selected list? 

It should still function the way before, once you select a model from a folder, everything from that folder becomes the "list". Shuffle and next/prev function will only select model from that list. You can actually view the list in the List menu. 

One way to verify this is to keep the "List" menu open while you hit the shuffle button, you'll see the selected model in blue.

**Comment by hboxgames** [comment]
Hi !

The specific workflow that didn't work for me, is to load something from "favorite" or a specific "tag" inside the browser, than shuffling.
Then before, it would only load favorite or tagged ones, but now I could notice that it wasn't working because the loaded models were either not favorite or tagged like the first loaded one !

**Comment by hboxgames** [comment]
Oh ok I found a simple workaround, so loading from the browser won't work to make a "list". I have to load from the small dropdown menu then use that to suffle. Not a big issue :)

Meanwhile, I was testing motions that were staggy before and I feel like it improved so much !!
Also, unlocking 0 limit or something on the dynamics made hair much less gitchy too :)

I just noticed that "skin" material was randomly being applied or not on models (like the thickness and sweat could be applied on the face but not the body for example) but maybe it's a temporary bug and you're on it ?

Thanks anyway !!
