### ISSUE TITLE
BVH loadin forever

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#231]
Hi !

I know this feature is kinda put aside for now, because it seemes pretty tricky to get it workable for many types of BVH although the ones you tested and similar ones were working pretty well !

so I acquired recently a nice bank of BVH motions and wanted to test out on the latest version, but it wasn't really working anymore !
I wonder if it was a mistake of mine or a bug, simply you desactivated the feature ? Right now when I try to load a BVH (even those that worked before) it's just loading forever. could you have a look at that ?

Thanks in advance !

**Comment by alloystorm** [comment]
We'll look into this. We haven't made any change to BVH motion part but there was a content scanner change that may affect how the motions are organized. Not sure if that's the reason. 

If possible can you send us one or two motions that can't load and we may be able to figure out why.

**Comment by alloystorm** [comment]
Should work better now in 1.4.0
