### ISSUE TITLE
Mac version or Web version (SaaS subscription) feature plan suggestion

### ISSUE THREAD

**Issue by AlexNorth365** [alloystorm/dvvr#232]
Dear there,

DanceXR is a great product, very, very much looking forward to the Mac version. 

After all, there are a lot of Mac users, or you can exit the Web version, so that it can be done in a SaaS manner, and monthly and annual subscriptions are a good business model.

**Comment by alloystorm** [comment]
Hi, we already have a mac version avaialble. If you purchase from Steam, you'll be able to download the native mac build on a mac. M1 Pro is recommended.

**Comment by AlexNorth365** [comment]
Dear there, 

Is the version on steam Creator Edition or Pro? Because you have many versions, I will ask you for advice. Looking forward for your response, thank you!  Because I hope to buy the version with the highest configuration and the most full functions.

**Comment by alloystorm** [comment]
It is the Pro version.

Creator edition is not available on mac yet. Still having some issues to
iron out.
