### ISSUE TITLE
Adding Camera Passthrough on PC, Android, and XR2 Platforms (Quest)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#233]
**Add Passthrough**
Why well MocuMocue Dance VR has it but, it doesn't work with many different newer cameras outside of Valve Index, and HTC Vive.

Deo VR now also has a passthrough masking option for helping to green screen out in-video content for better irl world transparency overlay visibility.

Example for Leap Motion:
**Adding Passthrough using Leap Motion Camera(s)**
UltraLeap/Leap Motion's hand tracking cameras are stereo infrared devices so the images received from them are not in color. In addition if the device(s) is not mounted at eye level then the perspective would be off slightly which could be slightly disorientating if using this for VR passthrough.
 
However, this is a fairly straightforward Stereo IR camera and you can access the camera images directly if you wish, please see their documentation [here ](https://docs.ultraleap.com/tracking-api/leapc-guide/images.html)for guidance on accessing these via their LeapC API, there is also an [example ](https://docs.ultraleap.com/tracking-api/examples/images-example.html)to help you to get started with this.

**Additional context**
I was thinking that this could be useful for demonstrating more use cases for the DanceXR app outside of just VR to also AR, MR, and XR.
Though mainly for that 3D hologram effect impression of being right in front of you and seeming so lifelike, that you can't believe your eyes!

Resources:

**Documentation**
https://docs.ultraleap.com/tracking-api/leapc-guide/images.html

**Example of LeapC API working**
https://docs.ultraleap.com/tracking-api/examples/images-example.html

**Comment by alloystorm** [comment]
Passthrough is available in the Quest version. 
We'll keep an eye on the technical solution for this on other platforms.

**Comment by alloystorm** [comment]
For those platforms that does passthrough by replacing certain solid color, like ALXR, the current version should already work. 

Swtich sky to color mode, and choose a solid color as background, for example like black. Then turn off ground, you should now get a solid color background that can be recognised by the platform to use for passthrough.
