### ISSUE TITLE
"Outfit" layer overrides Skin Wetness effect

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#234]
"Outfit" layer overrides Skin Wetness effect
When using any "Outfit" (Pro feature) the Skin Wetness effect is no longer displayed, until "Outfit" is toggled OFF.

**Expected behavior**
Being able to show Skin Wetness while using the "Outfit" Stockings selection.

Issue occurs in:
Dance XR 1.3.8.773 HQ Pipeline for PC

**Comment by alloystorm** [comment]
Outfit and skin use different shader modes and they are not compatible with each other, so that's not possible to do at the moment.

**Comment by alloystorm** [comment]
This is now possible in 1.4.2, but skin shader mode can't work with matellic so you still won't get metallic look on skin materials with Outfit on.
