### ISSUE TITLE
No Silent Motion Looping & Pause Issue

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#235]
**Describe the bug**
When playing a motion that has an Audio track then switching to .BVH or probably any motion that doesn't have an audio track the LOOP function doesn't function properly it just stops looping until manually "Play" is toggled on again, then Looping function works as intended.

**Expected behavior**
To continue looping, even when loading a motion without audio.

Reproduce Effect:
When playing a motion that has an Audio track then switching to .BVH or probably any motion that doesn't have an audio track the LOOP function doesn't function properly it just stops looping until manually "Play" is toggled on again, then Looping function works as intended.

*Then switch the Audio track every other test.
Reproducible Steps
1-Load Audio Motion
2-Load Motion (Has No Audio)
3-LOOP function should halt now
4-Click "Play", normal until...
5-Repeat, this time use a different Audio Motion (different Audio file)
6- Voila the problem happens again

Version:
1.3.8.773 HD Pro Pipeline

**Comment by alloystorm** [comment]
We weren't able to reproduce this in the 1.4.3 release. Please have a try and feel free to raise again if issue persists.
