### ISSUE TITLE
Options - More Environment Options for "Dust"

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#236]
**Describe the solution you'd like**
A way to use the "Dust" effect feature to do other particle effects like:
-Snowflakes
-Lotus Blossoms
-Sakura Petals
-Rose Petals
-Autumn Leaves
-"Ashfall" or Falling Ash (From Volcano Eruptions)

-"Making it Rain" (Money everywhere)
Having loads of money raining down.
(Raining Money | Blender 2.93 tutorial) by Balu Prime - AEST
https://www.youtube.com/watch?v=R2LGfTnYgoo
(how to make rain money falling in blender) by TopChannel1on1
https://www.youtube.com/watch?v=2WjDi96CHN8

-"Prop/Accessory" Rain (Heavy Rain Like its Raining Cats and Dogs, in this case 3D .PMX, .XPS, or .OBJ props/character Ragdolls)
-Crystal Prism Stars (Various randomized shapes)
Google: "crystal prisms shapes" (Google Images) The variety is the idea here.

-Coconut showers
Probably workable now with the "Prop" system since it allows Physics, I think Soft Body Physics.
-Meteorite Showers
(Super Mario Galaxy #1 Prologue Level)
https://youtube.com/watch?v=duWVRNigg6c&si=EnSIkaIECMiOmarE&t=51
(4K ✦Meteor Shower✦ Animation ⒶⒶ 60fps Motion Background 2160p AA VFX)
https://www.youtube.com/watch?v=VzmLIHEDbVI

-Diamond Dust [https://en.wikipedia.org/wiki/Diamond_dust](url)
-Actual Diamond 3D object (A girl's "best friend" or Sonic's 3D Emerald model) effect. or like (Sims 4 "Plumbob" icon).
-3D Kawaii Hearts/ Valentine Hearts

More Examples:
-Falling Confetti (With a blasting from source effect)
-Party Balloons
-Prop Rain (3D Models rain from the sky, possibly with Physics still intact)
-Concert Light Sticks (Kpop/Jpop Light Batons)

**Describe alternatives you've considered**
Making the "Dust" effect have parameters and settings similar to how "Outfit" works now, or simply have it read files stored in the Content Folder as "Rain Effects" or something similar (with a better name...)

**Additional context**
A randomizer for "individual" snowflake color would be nice also.

Maybe see about including the ability to have those "particle" effects able to interact with the physics engine in someway such as wind direction & body collision. Including Snow piling up into snow drifts.

**Comment by alloystorm** [comment]
New particle system in 1.4.2 should satisfy most of these.
