### ISSUE TITLE
"About" Section Missing

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#237]
**Is your feature request related to a problem? Please describe.**
New users, or really anyone interested is most likely not aware of this Github or other sources of information related to this project, due to a lack of a "About" section within the app.

**Describe the solution you'd like**
Add a "About" section within the app, so if issues pop-up users can be directed where they can seek further assistance.

**Describe alternatives you've considered**
Making a basic "About DanceXR" tab somewhere in DanceXR options/Settings menus.
Example: Windows Notepad has a tab called "Help" that at the bottom of it is "About Notepad" that opens a windows that mentions a few things, though none are really that helpful to Microsoft's credit.

**Additional context**
Consider adding or listing a few links to the DVVR Github or Patreon there so people who found it on Itch.io can find the other pages.

**Comment by alloystorm** [comment]
Good idea!

**Comment by alloystorm** [comment]
Added help section with links to the website in 2024.4
