### ISSUE TITLE
Feature Request: Motion Overwrite -> Fix Arm & Hand Override -> Elbow movement

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#238]
Its impossible to for the arms to get in any certain pose, We need a X, Y, & Z slider to control the position of the elbows.

**Comment by alloystorm** [comment]
In 1.4.2 release there is a new option in motion override to control the elbow bend axis, also the IK algorithm is updated to improve the bend direction. Let us know if it suits your need.

**Comment by Chrisc78** [comment]
Yes, this works perfect
