### ISSUE TITLE
Cannot click back in menu on WMR.

### ISSUE THREAD

**Issue by qmczar** [alloystorm/dvvr#24]
**Describe the bug**
The menu does not work correctly in Versions 4.4, 4.3, and 4.2 on Windows Mixed Reality. I can click into a menu, but the back arrow does not work at all. The check marks are also difficult to check and uncheck. The issue seems related. The menus work perfectly fine in version 4.1.

**To Reproduce**
1. Use Windows Mixed Reality. 
2. Open the menu.
3. Go to any sub menu.
4. Try to click a check box. (Doesn't work.)
5. Try to click the menu back button. (Doesn't work.)

**Expected behavior**
The buttons should work normally.

**Desktop (please complete the following information):**
 - Windows 10 1903
 - Samsung Odyssey Plus
 - Version 4.4, 4.3, 4.2 all don't work.

**Comment by alloystorm** [comment]
Thanks, will look into it.

**Comment by alloystorm** [comment]
Fixed in 0.5.1

**Comment by alloystorm** [comment]
Closing this as fixed. If any other issue arises, feel free to create another.
