### ISSUE TITLE
.BVHs motions are in the Ground (height) & T-Pose & A-Pose are missing

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#240]
**.BVHs motions appear in the floor**
Loading any .BVH motion file causes any model to suddenly appear in the floor instead of on the floor.

--Also when loading .BVHs the setting that allows switching between A-Pose & T-Pose is missing from menus.

**To Reproduce**
1. Load any .BVH motion and voila models suddenly appear in the floor.
2. Also suddenly A-Pose & T-Pose motion switching is gone from menus while a .BVH motion is active those options appear back if using a regular .VMD or MikuMiku Dance motion file.

**Expected behavior**
A clear and concise description of what you expected, for models not to suddenly appear in the floor and A-Pose & T-Pose settings not to disappear.

**Screenshots**
Not available, though on request .BVHs files can be provided.

**Desktop Details:**
 - OS: Windows 10
Most recent itch.io version, the update that brings Soft Body Physics support.

**Comment by alloystorm** [comment]
If you can send us the BVH motion you are having problem with, it would be great. 

Also BVH does not require A/T pose conversion, BVH comes with a standard pose so there is no need to use the pose conversion functionality for VMD. If you need to adjust model arm pose you can find the setting in the model motion config.

**Comment by alloystorm** [comment]
Thanks for uploading the motion. We'll look into it.

**Comment by alloystorm** [comment]
A bit lost track on this one. Is this still an issue or can we close it now?

**Comment by alloystorm** [comment]
Thanks! We are looking into it. Will get back to you before the July release.

**Comment by alloystorm** [comment]
Will be fixed in 1.4.6
