### ISSUE TITLE
New issue 1.4.1.851 with alpha materials or trasparent materials. LW VR version controllers not working.

### ISSUE THREAD

**Issue by Nyexxi** [alloystorm/dvvr#241]
1. The materials of the models with textures using alpha elements don't work as they should. Using them as opaque is the only option available now. In the previous 1.4.1.850 version this behavor was not an issue.

Tested in LW and HD versions.

2. Another issue found in the LW VR version, using Quest 2.
The controllers doesn't work, only the keyboard is funtional making it impossible to access the menu options. I tried a regular Xbox controller as well, only working the camera movement.

The HD VR version works perfect.

**Comment by alloystorm** [comment]
I can't seem to reproduce that transparency issue, could you attach your model so we can look into it?

**Comment by alloystorm** [comment]
Also you can try "reset all settings" and see if that fixes it. Sometimes saved configuration from older version can break things.

**Comment by Nyexxi** [comment]
Yes, I tried to reset everything but no luck, it is specially noticiable in materials like tattoos I'll link you a couple of models on my tstorage. You can check as well in both models the "winter bra" option and see how it looks. https://tstorage.info/n55ympjkp3j4 https://tstorage.info/d4pukwdrec26 

What about the controllers in LW VR mode, did you check it or was included in the "reset all settings" advice? If so I tried as well and it didn't work. 

Could you upload again or attach me the previous 1.4.1.850 or 1.4.1.849 versions. I deleted them and I'd like to see if I can reproduce these issues there, because in those previous versions I didn't have, at least the transparencies issue, I didn't check the LW VR mode so I don't really know.

**Comment by alloystorm** [comment]
Thanks for the models. We have it fixed and the new build 853 is uploaded on Patreon.

**Comment by Nyexxi** [comment]
I just checked the new version and the transparencies are fixed, thank you! But, I still can't make the controllers work in the LW VR mode version, while in the HD VR mode it works just fine. Is this a bug or is something from my side?

**Comment by alloystorm** [comment]
We are looking into it but we can only do minimum changes for 1.4.1 at this stage so the fix will be in the next release.

**Comment by Nyexxi** [comment]
OK I understand, I will close this then.
