### ISSUE TITLE
Bug - Massive List of Stages, App ignores "Stages" Folder structure

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#242]
Version: DanceXR 1.4.1.853 HD Pipeline (End of February itch.io version)

Bug:
Giant list of stages appears now, no longer are stages organized in their respective folders. Just a giant list.

Expected Behavior:
My self organized stages folders structure gets ignored and instead simply shows a giant list of all stages detected by DanceXR instead. The expected behavior would be for the stages to be displayed in folders and have a helpful search function as had been around in older DanceXR builds.

How to reproduce:
Go to Stage button then "look" to load any stage, and realize they are all shown as one giant list instead of nestled neatly into whatever folders each stage is actually in.
Simply try to load any stages already imported in DanceXR's Content Library.

Possible Solutions:
-Add back the way they were displayed before with motions being shown within the folders that they were stored in.
-Add a search feature, that "search" function is also missing from here too.

**Comment by alloystorm** [comment]
Stage folder strucutre is back in 1.4.2
