### ISSUE TITLE
Shared Presets Save and Config.JSON files (Between App Revisions and Updates)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#245]
**Is your feature request related to a problem? Please describe.**
When using models and features on the same revision number but different Unity Pipelines (HD vs Low) various saved configurations and presets aren't shared between each other (HD vs Low Pipelines) and when updating to newer versions those settings aren't easily ported forward. This just adds so much more complexity when dealing with pain in the butt Bonemapper configurations (some models avoid actual readable bones with names), and Physics settings "Breast" spheres placement and Soft Body settings.

**Describe the solution you'd like**
Shared Presets Save and Config.JSON files stored or backed up in a central location when updating to the latest version, this hopefully would enable not having to make "new" saved presets between the same version revision (Unity HD Pipeline and Unity Low Pipeline?)
A additional benefit of this is that it enables easier testing of model settings and presets between same software revision numbers and possibly when testing software revision updates and how they might fudge up working models and features. So, better troubleshooting.

**Describe alternatives you've considered**
1- In-App import Presets or Config.JSON feature.
2- Central location for a common settings area between update version, (itch.io users)
3- Small README.txt file with locations of Presets, Config.JSON, or whatever is needed to migrate settings files forward.

**Additional context**
N/A

**Comment by alloystorm** [comment]
Deliverred in 1.5.1
