### ISSUE TITLE
Jaggy Spiky Models, Invisibility, and Bonemapper Option Missing

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#246]
**Describe the bug**
1-Jaggy Spiky Models - A few models are showing horribly disfigured faces and sometimes limbs.
2-Invisibility - One model, Mila, is showing up as invisible but, not listed as being loaded, while the prior model loaded is still there and able to be interacted with instead of Mila being interactable.
3-Bonemapper Option Missing -  Quite a few models that load won't show the Bonemapper option and on the latest version DanceXR 1.4.1.853 (Late February 2023 via itch.io) no longer allows configuring how Bonemapper handles all models even models that previously worked as intended.

**To Reproduce**
Load any of the models listed below and the noted behavior should occur.

**Expected behavior**
For the models in question not to look like haunted house horror shows, hopefully. Including Mila's invisibility act. Or the Bonemapper option to configure each model's bones not being present anymore (The manual selection area). 

-------------------------------------------------------------
**Examples**

[NSFW] - "TEAM FORTRESS 2 - (New) FemScout"    [by Mylladinx]
Issue: Ultra **Jaggy/Spiky Face**, same for entire torso, and pelvic regions.
https://www.deviantart.com/mylladinx/art/TEAM-FORTRESS-2-New-FemScout-784487864

[SFW]  - "FFVII (Remake) - Aerith Age 7 (Hirowarego)_XPS"   [by Kanbara914]
Issue: Face is "**jaggy**" or **ultra spiky**, also missing Bonemapper's ability to configure bone mappings.
https://www.deviantart.com/kanbara914/art/FFVII-Remake-Aerith-Age-7-Hirowarego-XPS-844695562

[NSFW] - "Mila SportySexy mod for XPS"   [by RonDoe]
Issue: The model has a strange issue where it "loads" but, is not considered loaded by DanceXR and the model remains **invisible** but, if you enable Breast Physics and set "Visualize" the area where her bosom should naturally be does show that she is loaded. I was only able to set up "visualize" on a prior DanceXR version.
https://www.deviantart.com/rondoe/art/Mila-SportySexy-mod-for-XPS-609388901

[NSFW] - "Chun Li Battle Bikini Model Request" by Cablex452
Issue: The "bra_diffuse", "bikjni_diffuse", and nether regions area are jaggy/spikey. 
https://www.deviantart.com/cablex452/art/Chun-Li-Battle-Bikini-Model-Request-394547831

[SFW] - "Lei Fang -Chun Li" by DragonLord720
Issue: Under/in her right armpit a spiked beam or stick is just there.
https://www.deviantart.com/dragonlord720/art/Lei-Fang-Chun-Li-604715926

[SFW] -  "Kateryne" by [by OBAOLADE123] & [by WarfareMachine] (Both Deviantart)
Issue: Bonemapper option just missing from the menu.
https://www.deviantart.com/obaolade123/art/Kateryne-855308602
Additionally lots of models from either WarfareMachine or OBAOLADE123 do not show the Bonemapper option to rig(?) them for use in DanceXR.

---------------------------------------------------------------
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  DanceXR 1.4.1.853 (Late February 2023 via itch.io)

=======================================
**Bonus Area, the (Unlikely Zone)**
Just some extra models to look at, if you have the time:

Kabal Mystic, and [OBAOLADE123 & WarfareMachine], have basically what seems like all their models incompatible with DanceXR's Bonemapper for some reason. Just a heads up. 

[Probably SFW] - "(XPS Meshmod) Secretary Tawna (DOWNLOAD)" [by UndieWorld64]
Issue: "The model poses fine,but her arms and shoulder bones are a bit glitchy. Her hand bones are also glitchy too. So I wouldn't load with any pose or animation data,so just pose manually. Great for collections though."
Obviously that means it might not be easily fixable in DanceXR unless DanceXR ends up with support for weird edge cases like this.
https://www.deviantart.com/undieworld64/art/XPS-Meshmod-Secretary-Tawna-DOWNLOAD-872218352

[SFW] - "(MMD Model)KM Style Tails And Tailsko Update"  [by josugomezofficialnew] & [Kabal Mystic]
Issue: Bonemapper option is missing here too.
https://www.deviantart.com/josugomezofficialnew/art/MMD-Model-KM-Style-Tails-And-Tailsko-Updated-910751822

**Comment by alloystorm** [comment]
We still need to investigate this further but there will be a workaround provided in 1.4.2. 

For the spiky models you'll need to select a root bone for the mesh, we'll post a video shortly.

**Comment by alloystorm** [comment]
Forget about the "workaround" I mentioned. We figured out what's wrong. 

Some of the vertices have bone weights that don't add up to 1. We'll need to check for the condition and scale the weights to make sure they add up to 1. 

All of these models will be working as expected in 1.4.2.

**Comment by alloystorm** [comment]
1.4.2 is released. Please let us know if it solves the issue.
