### ISSUE TITLE
Some bugs or missing features I saw while checking the new versions HD 1.4.2.869 / LW 1.4.2.868

### ISSUE THREAD

**Issue by Nyexxi** [alloystorm/dvvr#248]
Some bugs or missing features I saw while checking the new versions HD 1.4.2.869 / LW 1.4.2.868.

1. The glow effect for materials doesn't work in any version. The only glow effect option working is for the beats visualizer.
2. In the config actor section for motions, the Mirror (VMD Only) and the Direct Drive for PMX models don't work as expected. This was an issue as well in the previous version and It wasn't present, at least, in version 1.3.6.700.
3. The VR mode for LW 1.4.2.868 has the same issue I previously pointed out about the controllers not working, making it impossible to operate in the menus. This is specific for this mode and version, the HD VR mode is perfect.

I checked everything with both my own config file and with the default settings.

PS: Amazing stuff with the new skins maps and particle system.

**Comment by Chrisc78** [comment]
also .BVHs motions the feet are broken.

![Screenshot 2023-03-04 185221](https://user-images.githubusercontent.com/107079307/222934240-807f9f2a-647a-4477-ab4b-8c5a1ce050fe.jpeg)

**Comment by alloystorm** [comment]
Thank you.

A new build with the fixes for the above issues will be uploaded soon.

**Comment by alloystorm** [comment]
Build 870 is now available. Fixed all 3 of the issues above. The BVH feet issue will be looked at too but might not be in this release.

**Comment by Benz10wheel** [comment]
I found that some motion(vmd) that worked fine previously also have feet problem in new version.  Well mostly when character lift their feet, squat down and etc.
