### ISSUE TITLE
Settings/Features that don't work in 1.4.2.870

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#249]
![Screenshot 2023-03-06 181143](https://user-images.githubusercontent.com/107079307/223278649-8f890e7c-ad41-44ad-b4d3-b5a61aadf7e9.jpeg)
![Screenshot 2023-03-06 181435](https://user-images.githubusercontent.com/107079307/223278658-efb702cd-350a-42ea-982b-66fffaccad8f.jpeg)
![Screenshot 2023-03-06 183254](https://user-images.githubusercontent.com/107079307/223280768-64c0ff93-1919-444d-be45-1aa2e5ffb7f3.jpeg)

**Comment by Benz10wheel** [comment]
I did some test on HD 1.4.2.870 
Micro Move doesn't work.(1st Picture)
Twist correction, Upper Arm, Lower Arm, Leg sliders are working on my models.(2nd picture)
Loop Duration not sure what it actually does but seem to affect physic somehow.(3rd Picture)
Show standard Pose will work if you tick the T Pose option.(3rd Picture)

**Comment by Chrisc78** [comment]
Does Upper Arm, Lower Arm, Leg sliders control xps models because they do nothing to my pmx models

**Comment by Chrisc78** [comment]
The upper and lower arm and leg twist correction barely works on a few models, I think it should work as good as the elbow axis control.

**Comment by Benz10wheel** [comment]
I probably won't look much different when model stand in standard position but when they squad, sit, stretch arm over the head hen it will have more noticeable effect.

**Comment by alloystorm** [comment]
Had a revisit on the arm twist correction, let us know if you think it works a bit better now.

**Comment by Chrisc78** [comment]
The lower arm twist and leg twist works great, the upper arm doesn't move much and does not move on some models. the Micro movement in lifelike is the only other setting in this post that is still broken.

**Comment by Chrisc78** [comment]
Most has been solved so I'm closing it.
