### ISSUE TITLE
Material and Shape Setting

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#25]
I just notice that some material and shape setting doesn't work. and i try each model it seen like it have nothing to do with the model.

I slider the material setting 0.00 to 1.00 (doesn't work)
I slider the shape setting 0.00 to 1.00 (doesn't work)

**Comment by alloystorm** [comment]
It seems alright from our end... Can you give us 1 example?

**Comment by Terell2018** [comment]
Some of material and shape setting not working with some model.

**Comment by alloystorm** [comment]
Will keep an eye on this but it would be nice if you can send us an example. Thanks
