### ISSUE TITLE
Feature Request: Manual Transparency 

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#251]
Beside the Transparency settings "Auto" "Force Transparency" and "Force Opaque" their should be another " Manual Transparency" with a slider underneath so you can set the right amount.

Also move "Transparent Prepass" from being a global setting to a setting for each model or under Troubleshooting the ability to turn it off for that model or stage.

**Comment by Benz10wheel** [comment]
You already can adjust the transparency amount with 2 options both came with its slider
'Alpha Adjustment' - Adjust the transparency of the material as a whole, this affect everything
'Alpha Clip' - Adjust the threshold by looking in to the .png file for the cut off for not render that pixel, so if a pixel in png have lower transparency(alpha) value than Alpha clip it won't get rendered.

![image](https://user-images.githubusercontent.com/127311516/223720612-44ee8b45-8b34-43b0-b1d9-8145356116f0.png)

**Comment by Benz10wheel** [comment]
From what I see in the picture I can tell that Miku's sleeve texture should have a transparent texture in the .png file, So when you have the mode as Opaque, what the program does is it ignore the transparency value from png. When you turn on the transparent mode it use the value from png alpha/transparent. Just think of Qpaque and Transparency as on/off switch there are no slider in-between then. 

However there is a solution to what I assume you want to do. Open the png for Miku sleeve/cloth, then make the texture fully opaque by duplicating the layer and flatten them. Now when you use the transparent mode it will start with full alpha/transparency and you can use Alpha Adjustment.

For Force Transparency/Force Opaque there are global setting and individual material settings, The Individual setting will overwrite the global setting.

Global: Auto = Default mode assign material with texture that have transparent value as tranparency and none as opaque
Global: Transparent = turn every material in to transparent mode, can look buggy and does not produce reflection in Screen Space Reflection
Global: Opaque = turn every material opaque, make thing that should be transparent by default look strange most noticeable are blushes texture, expressions on character face.

Individual Auto: default mode will use the global setting Auto/Transparent/Opaque
Individual Transparent: Force just this material to have transparency
Individual Opaque: Force this material to be opaque regardless if it has transpancy in the texture.

**Comment by Benz10wheel** [comment]
![image](https://user-images.githubusercontent.com/127311516/223744027-1c02f261-97ae-4956-8a3b-8139b06a6e20.png)
Global setting
![image](https://user-images.githubusercontent.com/127311516/223744215-77420a0c-020e-41bc-9eb4-8844c5f83e70.png)
individual setting
