### ISSUE TITLE
Feature Request: Physics Override for boobs and hair.

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#252]
The ability to instead of ignoring pmx physics completely to just ignore areas like Boobs, Hair, and maybe skirt then use the XPS physics to set your own for those areas.

The area I really want better control is for my pmx models boobs but I want to leave the physics alone for everything else.

**Comment by alloystorm** [comment]
This is tricky for PMX because the file structure does not tell you which physics object is which. It's just a plain list of hundreds of rigidbodies and joints without any hint about what they are for. That's the only reason we haven't got a more granular PMX physics settings.

**Comment by alloystorm** [comment]
You can now modify pmx physics in groups, available in 2024.4.
