### ISSUE TITLE
Feature Request: Virtual Sound Speaker/Source

### ISSUE THREAD

**Issue by Benz10wheel** [alloystorm/dvvr#254]
The Problem:
Not really a problem but all musics are pretty much blast into your VR headset earphone. Wouldn't it be nice to have positional sound source that improved your VR experience?

The Solution:
Pretty much allow the virtual sound position inside the program so you can have music from farway, behind, bi-directional and etc.
Now you can immersively create sound setting presets for Live Concert Hall, Studio, Home Theatre, bathroom echo and etc.

**Comment by alloystorm** [comment]
Spatial audio will be avaialble in 1.4.9
