### ISSUE TITLE
Feature request:  Multiple playlists 

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#258]
The autoplay doesn't care whether or not there is 1 or more actors on the screen.  So it will also automatically play motions for 3 people even if there is only 1 actor.

Solution requested:  I would like a saveable/loadable playlist.  That way if i have 2 actors on screen, I could be able to just load a playlist with motions for 2 actors on them, or make a playlist for only bunny girls etc.

I'm not sure what the playlist really does honestly.  even when i check certain tags when playing, it seems to just play something that isn't tagged either.  so a savable/loadable playlist would definitely let me know exactly what i'm getting.

**Comment by Benz10wheel** [comment]
This feature already can be achieved now with tagging for the song/motion. Make tag for motions with multiple models like 
![image](https://user-images.githubusercontent.com/127311516/233326485-c740a39a-62a6-4792-9888-a92e17a2da7d.png)
then once loaded that way it will only loop between the motion with that tag
![image](https://user-images.githubusercontent.com/127311516/233326999-77f43b23-3f30-4fe3-822b-d1551be63a83.png)

**Comment by Benz10wheel** [comment]
![image](https://user-images.githubusercontent.com/127311516/233327761-1e93af1e-409a-4d25-950c-18b8a05d26bf.png)
loop list option

**Comment by alloystorm** [comment]
You are able to save playlists for later use but the save function is broken in the latest build, will fix.
