### ISSUE TITLE
Feature request:  Brighter ambient lighting, and ambient light color options

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#259]
Sometimes the lighting in dxr just isn't bright enough, it seems a bit dark.  You can brighten/darken ambient lighting to a certain degree, but it's not enough.  To fix that, I use added lighting, but that gives a hit to the FPS.  And if I make added lighting too bright, the exposure makes everything white instead of brighter, and one side only gets brighter while the other side gets darker.  I'd like to see everything as equally bright.

If possible, I would like to scale the ambient lighting to be even brighter, and give it different shades of color options.

**Comment by alloystorm** [comment]
You can try the "Exposure Compensation" in the "Auto Exposure" settings. That works even when you have auto exposured turned off. 
So if you want it brighter without adding light, simply increse the "Compensation" value. 
You can also increase "Sky Ambient" if it is not maxed out already...
