### ISSUE TITLE
MP3 playability

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#26]
Hello, this isn't a big issue at all.  No rush necessary.  But one thing that has always annoyed me is that MMD can only do WAV files.  Which are big files.  It would be great if DVVR can someday play mp3's or ogg's or whatever file format other than WAV.  thanks for listening!

**Comment by alloystorm** [comment]
We very much like that as well but at the moment MP3 is still not supported by Unity out of the box. We'll keep looking for other options.
