### ISSUE TITLE
Update made 90 percent of my xps models unusable.

### ISSUE THREAD

**Issue by Fernmable33** [alloystorm/dvvr#260]
**Describe the bug**
I have been using DVVR/Dance XR for years and never had any issues with any of my models. All of a sudden after the new updates almost 90 percent of my models don't work anymore. Half of my models load halfway through the floor with the yellow rotating circle nowhere near their feet. The bonemapper is broken. All models are unable to move or animate. The new bonemapping seems to be the culprit. It's no longer properly mapping things out and attempting to automatically map bones does nothing, manually attempting just crashes program every single time. The HipMaster bone seens to be causing all the issues. For some reason it no longer recognizes or adds a bone to HipMaster. Whenever I try to manually add the bone it just crashes the program every single time. Basically all my saved work and dozens of models are unusable and have the same problem. There are a small handful that for some reason have not been effected. I have some photos I will provide. 

**To Reproduce**
1. Add xps model. 
2. Attempt to add animation and nothing works. 
3. Attempt to manual fix bones either crashes program or causes the legs of model to look mangled and broken.

**Screenshots**
![two](https://user-images.githubusercontent.com/129998262/230204970-286bb793-b55a-4933-87db-5c758869006c.jpg)
![crashed](https://user-images.githubusercontent.com/129998262/230205046-2d647a31-e22e-4744-9688-f25e5a3ee903.jpg)
![crashed again](https://user-images.githubusercontent.com/129998262/230205061-2c719f77-c772-4adb-bc15-02312d920d0e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version latest

**Comment by alloystorm** [comment]
I'm sorry that the bone mapper no longer works in the old UI. 
Please don't use the bottom right button to launch the UI in your screenshots. You can change mapping right in the menu as shown in this video: https://www.youtube.com/watch?v=g0VAfBHauXw

**Comment by Fernmable33** [comment]
The new UI doesn't work either. Same exact thing happens whenever I try to map the hip master. Here is a picture of it crashing when im using the new UI.  You can see I tried using thew new UI.

![crashed again](https://user-images.githubusercontent.com/129998262/230412776-62499b46-3fc6-41ad-aaec-0d5fdec45c8c.png)

**Comment by Fernmable33** [comment]
I have solved the problem by uninstalling it on steam and reinstalling it under stable version. This seems to have fixed the issues instantly. The none beta version and the public beta both are broken and don't work. The stable beta release works just fine.

**Comment by alloystorm** [comment]
OK, the HipMaster bone is a different story.
The current version doesn't check for existing mapping so when you assign HipMaster it can result a circular parenting relationship. This will be fixed in the next release, 1.4.4+
You can also try removing the actor setting file, effectively clearing all existing mappings and try assign mapping again. There's a chance that this might work.

**Comment by alloystorm** [comment]
Please have a try in the new 1.4.4 version and let us know if there's any further issue.
