### ISSUE TITLE
Feature Request for Outfit 

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#261]
![Screenshot 2023-04-18 191411](https://user-images.githubusercontent.com/107079307/232924951-d4950d02-d5db-4adb-a61b-0178ccba87c5.jpg)
The ability if possible to turn off outfit to show on the arms.

![Screenshot 2023-04-18 191255](https://user-images.githubusercontent.com/107079307/232925230-9f901807-fadc-4e3f-a5af-203a1c536ee2.jpg)
Like the part of the outfit I turned into a bra I would like to raise the lower part of the stockings to look like shorts or underwear

Another feature that would be cool is the ability to use a .png picture of a pattern for the outfit.

**Comment by Chrisc78** [comment]
New Idea: Body Stickers

Using the same Idea as the Outfit how about Body Sticker of a Heart, Star, and other shapes that you can move around the body and change colors and patterns. also be able to add more then one.

**Comment by alloystorm** [comment]
We've got something even better. Take a look at this https://youtu.be/chHk9--cUYE
