### ISSUE TITLE
Feature Change Request: Breast Shake 

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#262]
I think shaking the entire model to jiggle the boobs looks dumb as hell. Instead you could have two motions one for Jumping up and down and another for twisting the upper body from side to side.

It would be much better woth a more normal jiggle. **This would be very helpful when setting physics. **

**Comment by alloystorm** [comment]
Actually do you see that "Motion Pattern" slider? Move it to the left and you get only up-down motion and to the right you get only left-right motion.

**Comment by Chrisc78** [comment]
Can you at least create a motion for setting the physics, like jumping up and down that we can adjust the settings like other Procedural motions.

**Comment by Chrisc78** [comment]
The new changes works perfect
