### ISSUE TITLE
Depth of Field - Exclusion Zone

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#263]
**Depth of Field seems kinda meh in VR, it just feels much less targeted, the effect seems to be very broad**

**Describe the solution you'd like**
Please consider adding the ability to specifically Include AND Exclude items or models within DanceXR from the Area of Effect for Depth of Field's influence. Also, to allow the "Spectators" designator setting to allow it to be applied Depth of Field so actors are out of focus intentionally if wanted.

**Additional context**
Generally the Depth of Field effect currently (in VR anyways) is too encompassing unless at a specific distance and makes everything blurry including models at certain distances.

Additionally Depth of Field seems really CPU or GPU intensive with nothing in the scene, maybe that can be improved somehow?

**Comment by alloystorm** [comment]
DOF is pretty much unusable in VR due to performance.

**Comment by alloystorm** [comment]
DOF effect was set to high quality by default and now it is set to medium which should have much less performance impact than before.
