### ISSUE TITLE
GPU Physics Simulation Option

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#264]
**Is your feature request related to a problem? Please describe.**
DanceXR physics seem to be heavily CPU dependent, this seems to be causing lower FPS numbers on weaker CPUs as compared against if the calculations were done on GPUs.

**Describe the solution you'd like**
Adding a support for physics to be calculated by GPU, and additionally a in-app choice to select between CPU or GPU physics engine.

**Describe alternatives you've considered**
Physics Engine powered by:
-CPU Only
-GPU Only
-CPU & GPU combo mode

**Additional context**
If possible it _may_ have some benefit. Additionally this would include MMD native model physics, Soft Body, the sometimes overly complex skirt physics among other physics.

**Comment by alloystorm** [comment]
This is mostly beyond our control unfortunately. But the new Unity physics engine is likely to perform better than the old one. However it's totally different and require a lot of rework. I can't say for sure when is that going to be availble in our releases.
