### ISSUE TITLE
Ray-Tracing + Path-Tracing, Purchasable (itch.io Version)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#265]
**Is your feature request related to a problem? Please describe.**
Currently the original version of DanceXR bought from itch.io does not include the Ray-Tracing feature.

**Describe the solution you'd like**
Add a way to upgrade itch.io DanceXR version(s) to include Ray-Tracing and possibly Path-Tracing as well.

**Describe alternatives you've considered**
Asking nicely, please.

**Additional context**
It would be nice to also include the ability to have DanceXR also add Path-Tracing (Higher Fidelity Ray-Tracing), even though it might not run as smoothly on Android and XR2 devices.

**Comment by alloystorm** [comment]
This is now avaialble on itch.io
https://stormlab.itch.io/dancexr-raytracing
