### ISSUE TITLE
Support for Separated Texture Folders, Shubaruu Nested Additional Texture folders

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#267]
**Is your feature request related to a problem? Please describe.**
Currently within DanceXR using additional textures stored in seperate folders is not possible.

**Describe the solution you'd like**
A way to use the additional texture folders with DanceXR's new Wardrobe Dressing System, and adding the ability to add more custom slots.

**Describe alternatives you've considered**

**Additional context**
For: "DOAXVV Honoka Cardamom" by Shuubaru
Being able to use materials in the same upper folder,  on models located in subfolders... "Cardamom" (Yellow) or changing the color scheme to "Clove" or "Nutmeg" would be one purpose, another would be using the included textures "Face blush", "Tan Lines", "Wet Textures" on each of the different hair style separated models, which are also each in a separate folder would also be nice.
Each additional texture is located within a different folder and properly labeled but, DanceXR is not setup to do anything with that at the moment, I guess?

Example:
![DOAXVV Honoka Cardamom by Shuubaru - Screenshot 2023-04-27 212431](https://user-images.githubusercontent.com/31259717/235050070-7568f12c-3bfc-4d2a-b559-37a3f6056743.jpg)

Source:
https://www.deviantart.com/shuubaru/art/DOAXVV-Honoka-Cardamom-DL-788565378

**Comment by alloystorm** [comment]
Try zip it into a zip package. It's going to search for all files in the package for alternative textures, rather than only subfolders in directories. 

This is because we have to limit the search range otherwise it can be endless. Imagine it goes to its parent folder then then there's 1000 other models in there...

**Comment by alloystorm** [comment]
Thanks. We'll look into that naming issue and think about sharing alternative textures across different packages.

**Comment by alloystorm** [comment]
If you have access to 1.4.4, can you try refresh the library and see if the xps model names inside zip are still just "xps"? We did some test and it seems 1.4.4 should be able to handle this properly.

**Comment by alloystorm** [comment]
Let us know if 1.4.5 works as expected.
