### ISSUE TITLE
Model Bonemapper issue - KabalMystic Models

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#269]
**Describe the bug**
KabalMystic models converted to MMD and XPS still do not work because they still can't be setup with Bonemapper since Bonemapper does not appear in the options menu when those models are loaded.

**To Reproduce**
Load any KabalMystic MMD Ported model, usually one ported By josugomezofficialnew
Next look for Bonemapper, the option is simply missing.

Generally just load any WarfareMachine or KabalMystic model that has be ported to MMD and Bonemapper doesn't work--because it no longer shows up within those models settings menus.

**Expected behavior**
For Bonemapper to at least appear so Bonemapper setup can be attempted, even if it may fail.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Models such as the following:
KabalMystic or KM (MMD) models

(MMD Model)KM BOOsette Updated
By josugomezofficialnew
https://www.deviantart.com/josugomezofficialnew/art/MMD-Model-KM-BOOsette-Updated-926802336
Note: Using some mouth morphs with Teeth or oddly flatting nipple morphs causes that Mila Spiky polygon issue to be present.

(MMD Model)KM Bowsette Updated By josugomezofficialnew
https://www.deviantart.com/josugomezofficialnew/art/MMD-Model-KM-Bowsette-Updated-926802333
Note: KM Bowsette has a weird texture overlapping issue a flickering effect is caused by it.

(MMD Models)Lopunny by josugomezofficialnew
(A port of WarfareMachine's "BUNNY PACK 2022 V1.7 (Holly Zanzibar + Lop + Lopunny+Vaponny)"
SFMLAB: 
https://sfmlab.com/project/33534/
MMD Port:
https://www.deviantart.com/josugomezofficialnew/art/MMD-Models-Lopunny-957899466
Note: Lopunny MMD port has weird issues in the breast department on the left breast when using the "BreastSizeSUIT" at 100% the left breast has a weird hole thing that appears, and when using the "BreastSmall_BreastNnipplePerk" at 100% the top tufts of hair on her legs becomes polygon jaggy like that Mila SportySexy and FemScout model juust not quite as bad. Also, the NSFW version jaggies and other model artifacts that appear when using various Breast morphs. less so with BreastSUIT morphs.

**Comment by alloystorm** [comment]
Had a look at these models, and they are missing "Center" and "Torso2" bones. 

In this case the bone mapper won't really help because they will not animate correctly. The bone mapper can map one bone to another but can't creating missing bones. 

The bone mapper is only available for XPS models. MMD models have no need for it because they have a set of standard bone names. The most likely reason that a MMD model won't load is because it's missing required bones. In that case the bone mapper isn't going to help anyways.

**Comment by alloystorm** [comment]
We have removed the requirement for center and torso2 bones in 1.4.7. It will try to create those bones based on bones that are available. This will not be very accurate but should allow the models to animate.
