### ISSUE TITLE
crazy hair

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#27]
hair starts out fine.  but load any dance, and hit play...her hair will go crazy and fly everywhere at 1000mph.  Here is the model https://drive.google.com/open?id=1wVwbVUbZXLq3e5Ege-P6qbNdDTneXOlA

thanks!

**Comment by alloystorm** [comment]
Will increase the default joint strength in the next version. You can also adjust this from the UI in the actor settins -> options -> joints, increase "Linear Spring"

**Comment by chengsta** [comment]
oh I didn't know about that linear spring thing, that fixed it!
