### ISSUE TITLE
VR Time Clock & UI Time Clock - Improvements

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#270]
**Describe the bug**
VR Time Clock that appears on back of right hand is not very helpful it shows nothing useful, it is not obvious whether AM or PM, and it also shows FPS possibly?? Not in numbers for some reason, making it difficult to tell what the FPS being gotten actually is.

**To Reproduce**
1. Look at in-game clock/FPS thing on back of hand,
2. Suffer... and guess what Time & FPS is.

**Expected Behaviour:**
To see a clean and concise easy to read clock watchface, and FPS counter that uses numbers (and possibly still use that gauge meter also for indicating POOR, MININUM, GREAT FPS numbers based on what Targeted FPS is selected as a target goal.
Also, please add a Time Clock with "Military Time" (ex. "Zulu Time" 01:00 - 24:00) and AM/PM (12hr) as options.

**Additional context**
Easy to read gauges and clocks are cool and useful. (Pointless comment...)

**Comment by alloystorm** [comment]
We can think about that. 

The reason we are using a analogue clock is because drawing that in the shader is much easier than rendering text.

**Comment by alloystorm** [comment]
Will use a simple digit format in 1.4.8
