### ISSUE TITLE
Feature request:Designation of background color by RGB value, unaffected by light

### ISSUE THREAD

**Issue by uldnas** [alloystorm/dvvr#273]
**Is your feature request related to a problem? Please describe.**
I want to do an operation like removing the background with chromakey, but it is difficult to make the background the color I want.
Also, the light of the background color changes the color of the character.

**Describe the solution you'd like**
I would like the ability to specify a background color by RGB value, independent of light.

**Additional context**
If it is still possible in the current situation, I would like to know how to do it.

**Comment by alloystorm** [comment]
So do you mean pure color background? 

At the moment you can choose the "Gradient" mode in sky settings and turn "Background" slider to 1. But in that mode you can only choose a color temporature to change the background color, not any color you want. It should be pretty straight forward to extend that to support any color of your choice if that is what you wanted.

**Comment by uldnas** [comment]
Yes, I meant that I want a pure color background.

**Comment by alloystorm** [comment]
This is available in 1.4.6

**Comment by uldnas** [comment]
Thank you very much! I will try.
