### ISSUE TITLE
Loading Certain Zipped Files Is Infinite Never Finishes

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#274]
**Describe the bug**
A folder full of models loads correctly but, when put into a .Zip file to allow DanceXR to show the .XPS names properly instead attempting to load any model from within the .Zip causes an infinite loading loop---never finishes even after hours.

**Expected behavior**
To load like every other model or model with a .Zip file.

Version: 1.4.5.924 & older 1.4.4

**Additional context**
Strangely the model in question also has a really strange red skin tone color.
Link to Model: 
https://www.deviantart.com/xpsmaniac/art/Anesthesia-xps-meshmod-827221721
The model(s) too large to upload.

**Comment by alloystorm** [comment]
Appears to be working fine in the latest version. 
Not sure what's going on with the skin color though.

**Comment by alloystorm** [comment]
closing this for now and feel free reopen another for the red skin issue. But I think that's most likely a problem with the model.
