### ISSUE TITLE
Most File Names Appear as: "Xps", "Generic Item", or the Actual File Name

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#275]
**Describe the bug**
Most File Names Appear as: "Xps", "Generic Item", or the Actual File Name.
Version: Dance XR HQ Pro - 1.4.5.945

**To Reproduce**
1. Start DanceXR
2. Let DanceXR finish scanning for files and such
3. Attempt to select any files or models and the names appear as pointed out.

**Expected behavior**
For names to either show the above folder name or the actual model name from the .xps, .x, (Generic Item), or .ASCII, .PMX, or other file name... sometimes when loading a model DanceXR "reads" the file name and "displays" it within the loading UI item and briefly shows some models actual name.

**Screenshots**
![Gibberish Names (DanceXR not displaying read File Names) Screenshot 2023-06-29 175743](https://github.com/alloystorm/dvvr/assets/31259717/b336ccbf-0e37-4869-ab93-c953a0dc1bc0)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
----NA----

**Comment by alloystorm** [comment]
This is addressed in 1.4.7
