### ISSUE TITLE
Ability to Slow down Cycle (Beats) for Time of day, Etc.

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#278]
Sunlight's Time of day, Ecliptic Angle, and maybe Orientation's Auto Cycle (Beats) should have the ability to slow down more or even able to enter a customized value.

<img width="688" alt="Screenshot 2023-08-06 050823" src="https://github.com/alloystorm/dvvr/assets/107079307/a4495a4d-ec06-4842-a944-09b18bca6ccd">

**Comment by alloystorm** [comment]
This is avaialble in 1.4.8. 
The cycle is now unlimited and you can enter any value you like.

**Comment by Chrisc78** [comment]
It seems to only be able to slow down so far regardless of what value you enter.

**Comment by alloystorm** [comment]
I tested changing cycle to 512 for orientation of the sunlight, it works fine. It's moving very slow. 
Can you confirm and let me know which setting are you having problem with?

**Comment by Chrisc78** [comment]
I will try again, I don't think I really tried it much this version.

**Comment by Chrisc78** [comment]
I was wrong it is fixed.
