### ISSUE TITLE
无法操作人任何选项

### ISSUE THREAD

**Issue by yae-rabbit** [alloystorm/dvvr#279]
**Describe the bug**
![image](https://github.com/alloystorm/dvvr/assets/38056588/568659df-59c5-4919-ad94-0e33933b29e1)
![image](https://github.com/alloystorm/dvvr/assets/38056588/1c8a28bc-5bc0-4e49-9938-fc0253795b6d)

**To Reproduce**
b播放视频的时候忽然卡住了，重启软件后任何选项不起作用

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alloystorm** [comment]
It would be nice if you can attach your log file so we can analyse further. 

Where to find the log here: https://vrstormlab.com/dancexr/troubleshooting

**Comment by alloystorm** [comment]
Usually this can be resolved by clearing your configurations (by removing the config.json file). But it would be nice to figure out what's causing it. For that we need the log file.
