### ISSUE TITLE
Bonemapper Editing Fingers Gradual Slowdown (Massive FPS Hit)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#280]
**Describe the bug**
When manually setting up a model's Bonemapper config from within DanceXR as I added the correct pairings for each individual finger the program was getting slower and slower (Not noticeable at first but, then VERY noticeable) very very low FPS... so this required me to manually force the model to "reload" then after it finished loading in, everything was back to regular speed.

**Expected behavior**
Not get slower just assigning finger bones.

DanceXR Version: 1.4.6.989

**Comment by alloystorm** [comment]
Can you check if this is still the case in 1.4.7? 

I can't seem to reproduce the issue in the current version.
