### ISSUE TITLE
Saving settings for Lighting, Ground, Sky, Controller, etc in external json files

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#281]
I would like to be able to Save settings for Lighting, Ground, Sky, Controller, etc in external json files, then when I switch programs like between Creators to HD Pro builds I can just load the previous saved settings for just the lighting, or conrollers, etc instead of trying to remember all the values. Similar to how saving scenes work except it only saves targeted values then when you load previous saved values in inputs them back into the Config.json file

**Comment by Chrisc78** [comment]
Best feature ever, now we need to be able to same models Materials settings as presets.

**Comment by alloystorm** [comment]
More detail to come.

**Comment by Chrisc78** [comment]
I should have posted this from the start.
![Screenshot 2023-12-30 045115](https://github.com/alloystorm/dvvr/assets/107079307/c327f39e-5d2f-4b48-a1be-18f6acb6cdc9)
