### ISSUE TITLE
Add "Night Time" Sky preset

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#282]
<img width="688" alt="Screenshot 2023-09-04 080253" src="https://github.com/alloystorm/dvvr/assets/107079307/d2c8bd92-8bc8-4ddc-b065-87bf2fba9bd3">
^The lights in sky are Point Lights
<img width="687" alt="Screenshot 2023-09-04 080337" src="https://github.com/alloystorm/dvvr/assets/107079307/7d29a2bc-3289-4948-8646-90a738f1f75e">

The "Night Time" preset should have the lighting from the "Indoor" preset  but also be able to add Stars to the sky.

**Comment by alloystorm** [comment]
This is not possible because the "indoor" preset uses pure color background so it does not work with the stary sky which uses the precedural sky.
