### ISSUE TITLE
Outfit paint/save Bug

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#283]
Hi !

I flagged this on discord but wanted to give you a real ticket about it.
Loading the presets or character's saved settings automatically breaks the painted effect and make a glitch to me.
You said it works for you so here is some screenshots to breakdown the problem.

Here is the effect I use, just a band I created to allow a simple pantyhose mark on the surface (paint edge):
![Screenshot_15](https://github.com/alloystorm/dvvr/assets/76269190/0b77638d-9d11-4dc4-976b-dd82e6626765)

Then, when I load back the character or the preset, it break and become this. 
![Screenshot_14](https://github.com/alloystorm/dvvr/assets/76269190/b07d382f-4df2-4eed-908a-66364ee75ebf)
I have to use clear canvas and paint back everytime.

Thanks for the great work tho !

**Comment by alloystorm** [comment]
I see what you mean now. 

The preset does not save the picture your draw, it only saves the parameters. 

However you can save the drawing, then select the newly saved picture from the dropdown, then save a preset, that way the preset will save the picture index so the next time you load it, your saved picture will be loaded as well.
