### ISSUE TITLE
60fps motions

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#284]
Hi !

I made a separate issue for this thing I found a while ago :
https://we.tl/t-xr76lN5IA0

It's a motion in 60fps, so it loads in slow-motion when we use it on the app.
I was thinking that, as a solution, you could either implement the fuction to read 60fps motions, or skip 1 frame out of 2 instead ?
Anyway, think about it !

on MMD, it looks like they use this to make it work : https://github.com/minmode/MikuMikuDance-60fps

**Comment by alloystorm** [comment]
<img width="599" alt="Screenshot 2023-09-29 at 4 45 08 pm" src="https://github.com/alloystorm/dvvr/assets/51807035/87d4ff6e-4441-40bb-a594-0aebcb255554">

Setting motion speed to 2 should work. Let me know if it doesn't.
