### ISSUE TITLE
Problems in Panoramic Sky Map

### ISSUE THREAD

**Issue by HandriawanKun** [alloystorm/dvvr#285]
The sky map that I added doesn't appear, I downloaded the sky map from the Poly Heaven website in HDR & JPG format. But you can only add JPG format, I use DanceXR Android version 1.4.9.1008.
How do I fix it? I looked for a tutorial on YouTube but the video is 2 years old and with a different version of DanceXR.

**Comment by alloystorm** [comment]
HDR skymap is supported since 1.4.5

The Android content manager app might not be able to recognize it but if
you copy the HDR file into the content\texture\sky folder it should work.
