### ISSUE TITLE
Return the XRay from 1.4.8

### ISSUE THREAD

**Issue by TretanJonas** [alloystorm/dvvr#287]
previous request from me was "can XRay have an seperate Anchor offset" is not possible?. if really not possible i like to return the XRay from 1.4.8.

idk did Dev already made an attempt to make the Previous Request, is seem didn't go as i wanted/expected. cancel the previous request
(this just my Personal use XRay)

**Comment by TretanJonas** [comment]
https://github.com/alloystorm/dvvr/assets/38006312/551e884a-ad92-4c4d-bead-ac2e7a3ee3b4


https://github.com/alloystorm/dvvr/assets/38006312/badc0447-f4a9-43ec-b151-530398b18cd6


https://github.com/alloystorm/dvvr/assets/38006312/af732d87-9247-4aa8-a08d-1b53a701f091

**Comment by Chrisc78** [comment]
The dildo xray does not glow as bright as it should but only for the built in pole, if you use a dildo you added to the accessories directory the xray looks good..

**Comment by Chrisc78** [comment]
The xray of the pole is fixed in 1.5
