### ISSUE TITLE
Missing Recently Added .Zips

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#289]
**Describe the bug**
None of the 3 models will show up in DanceXR's list of models AND when navigating to the Content Folder of the models see that the models (.zip)s are missing altogether BUT do exist on the HDD.

**To Reproduce**
1. Search for any of those models OR use DanceXR's folder browser list to attempt to locate the models.
2. Realize no models are appearing in any list anywhere.
3. Realize there is a problem and give up until the next DanceXR release.

**Expected behavior**
For models to appear and possibly load as well.

**Desktop:**
 - OS: Windows
 - Version 1.4.9.1087

**Additional context**
These are the models, they all simply don't appear at all in either the search results or are not being recognized by DanceXR.
All models are SFW, just Detective Conan/Case Closed MMD Models.
[[FAVE]newcomer_kazuha_toyama_kirsten_thomas_(IZUMI Lookalike)__dl_by_thebizarrekazeko.zip](https://github.com/alloystorm/dvvr/files/13241626/FAVE.newcomer_kazuha_toyama_kirsten_thomas_.IZUMI.Lookalike.__dl_by_thebizarrekazeko.zip)
[[FAVE]newcomer_ran_mouri_rachel_moore___dl_by_thebizarrekazeko.zip](https://github.com/alloystorm/dvvr/files/13241627/FAVE.newcomer_ran_mouri_rachel_moore___dl_by_thebizarrekazeko.zip)
[[FAVE]newcomer_sonoko_suzuki_serena_sebastian___dl_by_thebizarrekazeko.zip](https://github.com/alloystorm/dvvr/files/13241628/FAVE.newcomer_sonoko_suzuki_serena_sebastian___dl_by_thebizarrekazeko.zip)

**Comment by alloystorm** [comment]
Had a look and these are PMDs, which we don't support... 
I guess it's possible to convert them into PMX with PMXEditor.
