### ISSUE TITLE
HDR (Possible) Incompatibility (Windows 11)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#292]
**Describe the bug**
Having Windows HDR setting turned on and playing DanceXR, while attempting to use OCULUS/Meta app's VR Desktop window viewer causes a massive flickering effect to happen every time the mouse cursor (or Oculus Controllers "Cursor) is moved over the virtual desktop screen viewer, when the desktop mouse cursor is at a standstill the flickering does not happen.

**Expected behavior**
No flickering.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by alloystorm** [comment]
So does the flickering happen on the virtual screen in the headset or on your monitor screen?

**Comment by alloystorm** [comment]
Will have to keep an eye on this one. 

The next update will support HDR output for Windows desktop but I'm not sure what's it gonna do for VR.
