### ISSUE TITLE
DanceXR doesn't read "Mat-Name" as entered in PMXEditor

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#293]
**Describe the bug**
DanceXR doesn't read "Mat-Name" as entered in PMXEditor it seems to group by shared "Tetxture" or "Tex" image name. Instead it seems to exclusively just want Japanese names translated... It might be a parity issue, I wasn't able to find the missing Japanese to English names.

**Expected behavior**
Not to see loads of Material0-10+ material texture names, after Materials were manually given updated names within PMX Editor EN v2.0 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version : DanceXR 1.4.9

**Additional context**
See the NEWER  .PMX files, please ignore older .PMDs files.
[[FAVE]newcomer_ran_mouri_rachel_moore___dl_by_thebizarrekazeko.zip](https://github.com/alloystorm/dvvr/files/13287125/FAVE.newcomer_ran_mouri_rachel_moore___dl_by_thebizarrekazeko.zip)
[[FAVE]newcomer_sonoko_suzuki_serena_sebastian___dl_by_thebizarrekazeko.zip](https://github.com/alloystorm/dvvr/files/13287127/FAVE.newcomer_sonoko_suzuki_serena_sebastian___dl_by_thebizarrekazeko.zip)

**Comment by alloystorm** [comment]
This is because most models don't have the English version of names populated so internally we are ignoring the English name field and only using the translated Japanese name.
