### ISSUE TITLE
Loops still aren't seamless using Ping-Pong (Due to Physics Restarting at Loop Beginning)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#294]
**Describe the bug**
"Seamless" Looping is not possible right now, since regardless PingPong, Clamp, Loop or whatever does not allow the "jump" back to the beginning without having the Physics Reset or "New Start" that begins even for trying to "seamlessly" loop a motion such as a Boomerang Video Trend or the PingPong (Loop Setting)

**To Reproduce**
Try to loop any motion (seamless) or proper Motion LOOP like a walk cycle and witness that stutter in between the "End" and "Start" even for again Loop Cycle motions.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: DanceXR 1.4.9

File for Testing:
[Spin-G8F.zip](https://github.com/alloystorm/dvvr/files/13288555/Spin-G8F.zip)
[Street Walks.zip](https://github.com/alloystorm/dvvr/files/13288563/Street.Walks.zip)

**Comment by alloystorm** [comment]
Is this fixed in 1.5.1? 

It seems pingpong mode is smooth to me. 
Loop mode by nature will "jump" a bit unless the start and end are absolutely identical.
