### ISSUE TITLE
Website Typo

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#296]
**Describe the bug**
Typo for obedient.

"For example you can change a proud and arrogant character to be **obidient** by just describing them as "“**Obidient** and eager to please”"."

**obidient** by just describing them as “**Obidient** and eager to please”."

**Expected behavior**
 obedient by just describing them as “Obedient and eager to please”

**Additional context**
Just a funny typo.

Webpage:
https://vrstormlab.com/dancexr/ai_chat

**Comment by alloystorm** [comment]
Fixed
