### ISSUE TITLE
Yagakoro - Special Support for MMD Crowd Things?

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#297]
**Is your feature request related to a problem? Please describe.**

Uh.. well a way to make it easier to use these crowd props, for example the Camera Crew MMD files are a group of people that somehow still works as a group of copycats background dancers.... its odd. The 2D Paper thin crowd props have an issue well, a few... mainly the textures when in DanceXR overlap and flicker in between each other in an obnoxious way, and that the model is so vast and large that its center is not easily moved into a useable position since DanceXR limits how far a model can be moved....    Just try finding the center (control circle center) of the "Paper Crowd Pack" (Miku & Friends Crowd prop) after using any of the crowd location motions its very hard, more so because you can't select the crowd only its point of origin.

**Describe the solution you'd like**
Ability to select a model from the listed loaded models and have that allow positioning controllers to appear allowing position by that way.
A preventative measure to deal with models that have to textures that are sandwiched together to no longer flicker, I'm not to sure actually

Related to something else: Maybe a feature can be added to allow two motions to be merged at least in DanceXR's memory for a session, since the Remix Motion 2nd slot doesn't seem to do that.

**Links**

A Bunch o' Crowds Props + a Camera Crew
https://www.deviantart.com/yagakoro/art/Animated-Paper-Crowd-MMD-Accessory-DL-692028877
https://www.deviantart.com/yagakoro/art/MMD-Accessory-DL-Animated-Crowd-2-738217117
https://www.deviantart.com/yagakoro/art/DL-Camera-Crew-456374251
https://www.deviantart.com/yagakoro/art/Paper-Crowd-Pack-339609307
https://www.deviantart.com/yagakoro/art/Imas-Crowd-365980736

Also, another simpler Camera Crew (NPC Pokemon Reporter & Cameraman)
Note: A case where allowing Bonemapper for MMD files could possibly solve the lack of motion compatibility, since for whatever reason their heads move... just strangely. (I know they aren't set up properly or fully.)
https://www.deviantart.com/miku90/art/MMD-Pokemon-BDSP-NPC-Model-Pack-10-DL-899293979

**Comment by alloystorm** [comment]
Part of this is addressed in 1.5.1. Transparency wasn't correctly set for stage and prop models. 
You should no longer see black area around people. If still do try reset all settings.
