### ISSUE TITLE
Lights - Treat a Texture/Material as a Light Emitter (Material Light Sources)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#298]
**Is your feature request related to a problem? Please describe.**
Lights - Treat a Texture/Material as a Light Emitter (Material Light Sources)
Another way to explain this is just the MMD stage SAB64 MMD Neon Colossuem that I included with this Feature Request had many battle arena spotlights... but, they all have the same issue MMD stages have with this,  in DanceXR there seems to be no way to turn the materials that look like spotlight beams into an actual spotlight or generic light source...

**Describe the solution you'd like**
Ability to change a texture/material on a stage to a Light Source or into a Light or Spotlight. 3D cone "light" into a DanceXR Light emitter source.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions... well I tried having the MMD stage spotlights of the arena have their "GLOW" set above 0 value, yet that has a another issue with how varied lighting conditions GREATLY effect how overblown the "GLOW" effect will be in bad/odd/weird/normal lighting conditions especially with Auto Exposure for lighting activated.

**Additional context**
The MMD Stage:
SAB64's MMD Port - Pokemon Battle Revolution's Neon Colosseum stage:
[_mmd_stage__neon_colosseum_download_by_sab64.zip](https://github.com/alloystorm/dvvr/files/13462833/_mmd_stage__neon_colosseum_download_by_sab64.zip)

Additionally this stage is a good one for showing even spotlight, stage lighting floor effects, and the other lighting used on and around the stage edge:
https://www.deviantart.com/philippe-n-12/art/MMD-DT-Change-Me-Stage-DOWNLOAD-745139383

**Comment by alloystorm** [comment]
Currently there is no way to turn "fake" light beams into real lights. But if you are talking about using texture map as light source you can try using the area light and load an image as "cookie map".
