### ISSUE TITLE
Body Motion Limits & Flexibility (Increase or Solution Wanted)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#299]
**Describe the bug**
The limits of "how flexible" models can be is limiting the usability of some motions. So, naturally a few motions cause strange body deforming effects.

**To Reproduce**
1. Load a motion that exceeds "reasonable" limits.
2. See the odd end result.

**Expected behavior**
Maybe find some way to allow "Limiter Off" settings on a per motion setting or auto-setting for detected exceeded limits motion data??

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.4.9

**Additional context**
One of the motions to test flexibility, the Ballerina one is NSFW.
[TESTING FILES (Flexibility Test).zip](https://github.com/alloystorm/dvvr/files/13494609/TESTING.FILES.Flexibility.Test.zip)
To be fair the O' motion is a bit extreme in the spine area, and ballerina is a very high kick bend.

This is what the "MMD Side Splits motion DL" is supposed to look similar to:
https://www.deviantart.com/d15k/art/MMD-Side-Splits-motion-DL-832815302

TrueBones (Gumroad FREEBIE) is the source of the Ballerina Motion, from their:

(EVERYTHING "FREE" at TRUEBONES. USE NEW CODE!, includes DISCORD SUPPORT!) $0 Pack.
(S*x pack freebie)
https://truebones.gumroad.com/l/gnwcyc

**Comment by alloystorm** [comment]
Having a bit problem unzipping the files, can you try 7z format?

**Comment by alloystorm** [comment]
Thanks for the file.

Just as I suspected, this is due to center position mismatch. In the motion settings, you can turn on "Center Position Conversion" and change the "Center Position" slider below it to around 0.7 and it should work as expected.
