### ISSUE TITLE
VR controllers not working.

### ISSUE THREAD

**Issue by crimzind** [alloystorm/dvvr#3]
I have both Vive Wands and Index controllers. Can't get either to interact with the menu. The B button on the index will open/close the menu. On the Index or Vive controllers clicking the track pad just flashes a "Motion:" bar then "Loading" and then it disappears.

Wouldn't be too bad if the mouse/keyboard could still be used to set stuff up via the PC and viewed in the HMD still, but no UI can be used in the program while VR is in use.

Also, there's no option to launch in or out of VR. In order to launch without VR, I have to remove/rename the VR plugins.

**Comment by alloystorm** [comment]
Have you tried the "Trigger" buttons when the laser pointer is on the menu? According to the spec they should be the buttons that work. 

We'll look into how to better support Vive controllers but since we don't have a Viva at hand, we might need to make test builds and ask people to test them until we find the right combination. It could take some time.

As of launch without VR, ATM what we are doing is to unplug the headset and it should fallback to desktop mode. Unity doesn't really give us a lot of options here. In the future, we might create a separate binary for desktop only mode.

**Comment by alloystorm** [comment]
Could you let us know if the Trigger button works on the menu? 

I checked again and confirmed that it is set to use Trigger in the Vive plugin so technically the trigger button should work.

**Comment by crimzind** [comment]
I tried both the Vive and Index controllers. Tried triggers, A and B buttons, track pads, grip buttons, stick clicks, nothing is interacting the UI when target with the laser.

**Comment by alloystorm** [comment]
[lwrp0.2.3.zip](https://github.com/alloystorm/dvvr/files/3537755/lwrp0.2.3.zip)
Made a few changes, could you check if this build works for you?

**Comment by crimzind** [comment]
I'm wondering if it's looking for Left/right specifics? I turned on the Right Index controller, it did nothing but point. I turned on the Vive controller. It did nothing. I turned the Vive controller off, turned on the Left Index controller. It will toggle the menu. The B button on the Left Index controller will toggle the menu now, but no other buttons seem to do anything, and neither Left or Right (or the Vive controller I tried) interactive with the menu.

**Comment by alloystorm** [comment]
We'll look into the Vive input utility which is what we use for UI input and see if we can find anything there. Will also checkout the new unity input system. It could take some time.

**Comment by alloystorm** [comment]
Hi crimzind,

Can I ask you a favor? 

I made another test build, could you try to run it with your Index controller connected and there will be a "vrnodes.txt" file generated in the exe folder. Could you find that file and send it back to me? This will help me diagnose the controller issue.

https://github.com/alloystorm/dvvr/blob/master/files/builds/lwrptest.7z

Thanks very much!

**Comment by crimzind** [comment]
Sorry for the extensive delay in responding, and bad news. No change. :(

**Comment by alloystorm** [comment]
Thanks for the data. 

Based on the info we have made changes in 0.2.4 trying to identify Index controllers, please let us know if it works now.

**Comment by YuichiNyan** [comment]
Works well with my valve controllers, thx!
