### ISSUE TITLE
Bone and texture xps bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#30]
I just discover a bugs on the hips when the model bend down and the texture kind of mess up on the model and it happened on some model.

Link: https://user-images.githubusercontent.com/49305586/74131057-87ed6c80-4bb1-11ea-8d9a-f764c5c030d0.png

**Comment by alloystorm** [comment]
We updated bone structure in r0.5.3, should be able to fix this issue.

**Comment by Terell2018** [comment]
I think i found the problem but i am not sure is that the problem. when i looking into bone structure note i notice that - ( ) (HipMaster) and have no pelvis and it happened on some model. the model with the problem hip is first one and third one. and there nothing wrong with the second one. some model have ├pelvis () (HipMaster) and other have - ( ) (HipMaster).

Bulma - https://github.com/alloystorm/dvvr/files/4345730/generic_item-bones.txt
Kefla - https://github.com/alloystorm/dvvr/files/4345734/Generic_Item-bones.txt
Tracey - https://github.com/alloystorm/dvvr/files/4345742/xps-bones.txt

**Comment by Terell2018** [comment]
i figure out the problem with the texture on the model. it come from the png image and i have to convert the png to tga with the filestar and it fixed.

**Comment by Terell2018** [comment]
I finally fix the hips on the model. what i did was download the XNA Posing Studio and when i look through the list of bone and i find out they was 4 spine spine base, spine lower, spine middle, spine upper and i just rename spine base to spine lower and when i test it out on dvvr it fixed.
