### ISSUE TITLE
Dressing System - Selection then Deselection Causes Freeze

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#300]
**Describe the bug**
When using the Dressing System's Custom options, when activating any options then deselecting them so they are no longer activate at that moment all things freeze & physics freezes.

**To Reproduce**
1. Create a CUSTOM
2. Choose a Texture/Material to enable to Disappear.
3. Check the box, to activate it.
4. Uncheck the box, and watch it make everything freeze, the app DanceXR works but Physics and model(s), will become frozen.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: DanceXR 1.4.9
 

**Additional context**
When attempting to unselect, add more materials, or deactivate a checked box this issue causes various things to freeze also.

**Comment by alloystorm** [comment]
Can you attach the log file? I can't reproduce this.
