### ISSUE TITLE
Use Bottom Bar (Reappear Shortcut in VR)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#308]
**Describe the bug**
Use Bottom Bar, disable it in VR and there seems to be no way to bring it back while still in a VR HMD. I brought it back by manually editing the Config.json file then restarted and now it shows the menu as usual.

**Expected behavior**
Just do that thing that MocuMocuDance VR or Virtamate does, where a certain button brings back the menu or VAMX does this.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: DanceXR 1.5.0

**Comment by alloystorm** [comment]
When you turn it off the menu should appear from your left hand. And you can use thumbstick to navigate and operate the UI. But it is a bit experimental at the moment, mainly around the menu navigation controls still needs a bit more work.
