### ISSUE TITLE
Motion Data Issue - Specific Song

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#309]
**Describe the bug**
A motion & song won't load but, DanceXR will play the MMD motion if loaded as "2" Remix Slot Motion, though the audio is missing then.

**To Reproduce**
1. Attempt to load.... wait... nothing changes.
2. Load any working motion data.
3. Then use the now present "2" (Remix button) to load the motion data "2 Phút Hơn (KAIZ Remix)" and now only the motion movement data works but, not the sound for it.

**Expected behavior**
To work as normal, I'm really not sure, is there a log file to check? If so where do I look for it?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.5.0.

**Additional context**
"Phút Hơn" the special characters "ú" and "ơ" may be the source of the issue, if so could support be added for that? If that is the only issue maybe.

2 Phút Hơn (KAIZ Remix)
[2 Phút Hơn (KAIZ Remix) 2Phut Hon - Hip Sway Dance Motion+Camera by RituPepper.zip](https://github.com/alloystorm/dvvr/files/13760897/2.Phut.H.n.KAIZ.Remix.2Phut.Hon.-.Hip.Sway.Dance.Motion%2BCamera.by.RituPepper.zip)

**Comment by alloystorm** [comment]
This works fine in the latest build.
