### ISSUE TITLE
After loading model the model selection menu stays open so you can load another model

### ISSUE THREAD

**Issue by Chrisc78** [alloystorm/dvvr#313]
After you load a model the model selection  menu should stay open so I can open all four models if I wanted to.
![Screenshot 2023-12-30 051448](https://github.com/alloystorm/dvvr/assets/107079307/41b1356e-9bdc-4d29-8205-436e46f51bc0)

**Comment by Chrisc78** [comment]
Fixed

**Comment by AlexECX** [comment]
Has this been changed again? It doesn't stay on version 2024.8 or the version before (I also tried the Pin button)

**Comment by AlexECX** [comment]
This works as described in VR, but it would be nice for desktop too. Having to navigate folders for every model swap is a bit of a pain if the models are not all in the same folder (so no playlist).
