### ISSUE TITLE
DanceXR Official Webpage - Expanded List of Supported File Formats

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#319]
**Is your feature request related to a problem? Please describe.**
Its difficult to know which file types are currently supported by DanceXR and which features seem to actually use them.

**Describe the solution you'd like**
A small file format support list to be added to the official website, program help section, or maybe add a wiki for other to add to-- with a approve for member editing system-- like for example only people who can verify a legal license of DanceXR as a preregistration condition. 

**Describe alternatives you've considered**
Simple readme file that lists file formats used by end-users of DanceXR, though that may not be useful for Meta Quest HMD users.

**Additional context**
N/A

**Comment by alloystorm** [comment]
This is now in the content library page

https://vrstormlab.com/dancexr/preparecontent.html#supported-formats
