### ISSUE TITLE
Bone and texture bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#32]
I discover a bugs on the arm, leg, hips. and texture are missing except hair and clothes. it happened on some model. it doesn't have any bugs from mmd.

https://user-images.githubusercontent.com/49305586/74698857-23439a80-51cd-11ea-91f9-a9a6e21b3711.png

https://user-images.githubusercontent.com/49305586/74698874-29d21200-51cd-11ea-8956-81263cd9117f.png

https://user-images.githubusercontent.com/49305586/74698893-35bdd400-51cd-11ea-9e0a-9ea3cd552974.png

https://user-images.githubusercontent.com/49305586/74953259-7422e100-53cf-11ea-9bb5-cde889a7579e.png

**Comment by alloystorm** [comment]
This is probably the same issue with https://github.com/alloystorm/dvvr/issues/16
