### ISSUE TITLE
Model's Loading causes VR in-app display stuttering

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#320]
**Describe the bug**
When loading a model during the load - DanceXR no longer has a fluid world framerate, it just causes the stuttering in the displayed HMD video feed.

**To Reproduce**
1. Select Model then click to load them...
2. Witness stuttering as DanceXR tries to process the data to load...
3. Wait for that model to finish loading in.
4. The stuttering stops once model fully loaded.

**Expected behavior**

**Proposed Solution**
Have DanceXR use another processor thread to process loading, so stuttering doesn't occur, with option on how many threads to use/make. Additionally this might help alleviate the longer load process of .zips .

Version: 1.5.1 (December 2023)
OS: Windows 11

**Additional context**
Lots of VR apps seem to suffer from this.

**Comment by alloystorm** [comment]
Yeah but unforturnately that's unavoidable for now. 

This is one of the things that we've been trying to optimize from day one, what we have now is already the best we can do. (until a new magic trick is discoverred)
