### ISSUE TITLE
HDR Support Issues

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#321]
Version: 2024.1
Install Handler: Itch.io App
Issue: HDR ON = Oculus RIft Left Eye (Display Screen) becomes completely blank/black.
Solution: Currently Turn off HDR support and VR Left Eye Display returns as normal.

(EDIT)
Solution: Currently my solution is to Turn off HDR in DanceXR and VR Left Eye Display changes from All (blank) Black then picture returns as normal.

**Comment by alloystorm** [comment]
Currently HDR is for desktop monitors, it might not work properly in VR. Non of the Oculus headsets supports HDR anyways.
