### ISSUE TITLE
Support for One-Boob (Shared Boob Physics)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#323]
**Is your feature request related to a problem? Please describe.**
Some models only have one selectable "Breast" bone not two. So mapping the Breasts Physics to matching "twins" isn't possible.

**Describe the solution you'd like**
A "breast" Sphere enlarger, Sphere into a Capsule or double sphere (merged together), some models have a "pair of breasts" that only have one bone. So a Capsule shape would be useful to solve for this issue.  OR better a way to have a pair of sphere attached to one bone location and a spacing setting for the space between them, just two orbs with space between them.

**Additional context**
Links:
https://www.deviantart.com/lezisell/art/Smite-Aphrodite-redesign-XPS-ONLY-442908255
Use the 1drv.ms link, search for "Afro-Dite".

**Comment by alloystorm** [comment]
Forgot to update this, it should be possible now. You can select only one bone, but don't expect very good result from it.
