### ISSUE TITLE
Model Material does not appear in the Material List after 2024.2

### ISSUE THREAD

**Issue by tasuken** [alloystorm/dvvr#325]
**Describe the bug**
The January version showed individual Materials, but the current version does not show anything but "Group"s.

**To Reproduce**
Load Model and see Material List.
Note that materials are displayed in the "Custom Initial State" of Clothing.

**Expected behavior**
A list of materials is displayed in the Material List.

**Screenshots**

https://github.com/alloystorm/dvvr/assets/54142732/699e3beb-bafa-4376-a4c8-3b7f0e96f5c8

It works in older version [2024.1].
![image](https://github.com/alloystorm/dvvr/assets/54142732/d4afc806-bf7f-4e6c-ac79-09c2cf1fca27)

**Desktop/VR:**
 - OS: Windows
 - Version: Steam
<img width="253" alt="image" src="https://github.com/alloystorm/dvvr/assets/54142732/95fc1505-1ec7-4c43-9d0d-2f3d07c4d38e">

**Additional context**
Since I touched dvvr a few years ago, I discovered DanceXR on Steam and restart it in this year.
This has been very evolving and I'm impressed that the project kept going.

Hopefully this game will become even more popular.

**Comment by alloystorm** [comment]
Check if you have a "Activate Your Copy" item in your system menu. The 2024.2 version requries another activation. Without it many of the features will be blocked. We will make the message more prominent.

**Comment by tasuken** [comment]
Thanks for the quick reply!
