### ISSUE TITLE
Clothing settings are not saved in Preset after 2024.2

### ISSUE THREAD

**Issue by tasuken** [alloystorm/dvvr#326]
**Describe the bug**
Clothing settings are not refrected when load Preset (Actor and Global).

**To Reproduce**

1. Go to Model's Clothing settings.
2. Check the items.
3. Save the Preset.
4. Reset settings.
5. Select a Preset and load the settings.

**Expected behavior**
Change Clothing settings are reflected in the Preset load.

**Screenshots**

https://github.com/alloystorm/dvvr/assets/54142732/6847f702-14e1-4827-847d-8b2d3026726a

**Desktop/VR:**
 - OS: Windows
 - Version: Steam
<img width="253" alt="image" src="https://github.com/alloystorm/dvvr/assets/54142732/95fc1505-1ec7-4c43-9d0d-2f3d07c4d38e">

**Additional context**
It is hard that the presets I created no longer work. (with https://github.com/alloystorm/dvvr/issues/325)
~~I am glad that there are so many version updates, but it is not nice to have such user-created items disabled or the UI changed so often that it makes it difficult to create articles explaining DanceXR.
I used the Steam version, but it would be nice to have a stable version.~~

I just found out how to specify the version in Steam.
It works in older version [2024.1].

**Comment by alloystorm** [comment]
I suspect it's the same issue that the copy is not activated. Try activate it and see if it works.

**Comment by tasuken** [comment]
Understood!
