### ISSUE TITLE
Add Back, Memory of Recently Saved Scene/Preset/Last Entries Field(s)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#328]
**Is your feature request related to a problem? Please describe.**
Prior versions of DanceXR used to allow me to type out a name then save a scene file, then when hitting the "save" floppy icon the text entry scene would show the last entered/loaded scene file name -- which would then allow me to use the "exact" name to overwrite the original file and update it without creating too many excessive nearly similar names as I guess what the file name should have been while in VR as this should be easier when not using VR mode.

**Describe the solution you'd like**
Add a last entry drop-down like in Google's Did You Mean feature or Google's Auto-Complete, or a list of prior recently used text entries.

**Describe alternatives you've considered**
Rolling back to prior DanceXR versions.

**Comment by alloystorm** [comment]
This should be addressed in 2024.4, also the default naming of scene is simplified so should be a lot easier to work with.
