### ISSUE TITLE
Breast bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#33]
i just discover a bugs on the breast on some model when the breast are flat and saggy.

https://user-images.githubusercontent.com/49305586/74700015-5b001180-51d0-11ea-9fdd-ab968d868ce2.png

https://user-images.githubusercontent.com/49305586/74700029-62271f80-51d0-11ea-935d-df51debe5dc1.png

**Comment by alloystorm** [comment]
![image](https://user-images.githubusercontent.com/51807035/75433201-b3d76300-59a3-11ea-89e9-c9be32a26a0e.png)
In the actor settings, set "Joint" to "Locked" should be able to fix this. 
Most of the models are fine with "Auto" setting but some needs to be "Locked"

Let us know if this doesn't solve it.
