### ISSUE TITLE
Motion Override: Leg Pose acting strange due to positon lock and rotation lock not working properly

### ISSUE THREAD

**Issue by Benz10wheel** [alloystorm/dvvr#334]
**Describe the bug**
Leg pose for motion override doesn't seem to work properly also position lock and rotational lock does't work well like older version. Now the upper body sorta slide only leaving the feet sliding on floor

**Comment by alloystorm** [comment]
This should be addressed in 2024.4, let us know if any further issues.

**Comment by Benz10wheel** [comment]
The lock Position and Rotation seem to work better now but I think there might be something wrong with Leg Pose>Open Slider working the same as Foot Rotate Y. The open slider used to widen the space between two knees but now it just rotate the model leg in place.

Also for Hand Pose, the IK Mode can be both good and bad, the IK mode make the elbow move more freely presumably it make hand jpb animations look better between two models. However it can be very weird with some motion due to the freedom that their elbow orientation can change.
