### ISSUE TITLE
2024.3 1221 (sex motion and other messed up)

### ISSUE THREAD

**Issue by TretanJonas** [alloystorm/dvvr#335]
- Sex Overlay are stopped working on this version
- Motion Overwrite are messed up
- Sex Motion 3 remain unpatched (Multiple Sex male + Female actor)

Man i love the new look for Morph AutoUpdate and Facial for Sex Motion 3
about the bug just **no need to rush** them i can wait out while on previous update like 1.3.8 or 2024.2
- Other Thing
if possible/Free time can you give the CowGirl Sex, Sex From Behind abit of update? (im still using it)

i can record the issues and show what i meant but github limit the file for 10MB

**Comment by alloystorm** [comment]
This was addressed in 2024.5, let me know if there are further issues.
