### ISSUE TITLE
[Request] Pause button is too close to the music slider

### ISSUE THREAD

**Issue by tasuken** [alloystorm/dvvr#336]
**Is your feature request related to a problem? Please describe.**
Pause button is too close to the music slider and miss to press.
When I try to pause during playback in VR, I accidentally press the slider and go back to the beginning of the song.
I am not sure if it is because I am using Meta Quest2.
Currently, I use the keyboard to pause, but would like to see it improved if possible.

<img width="171" alt="image" src="https://github.com/alloystorm/dvvr/assets/54142732/5f31ce87-95c8-4ae5-b771-aa0436f50d6c">

**Describe the solution you'd like**
Increase the space between the slider and the pause button or change the position of the start/pause button.

**Comment by alloystorm** [comment]
The whole progress bar is actually one button. When you drag it moves playhead and when you click it pause or play. 
I guess the real issue is the detection of drag vs click, we'll try to increase the threshold a little bit.

**Comment by alloystorm** [comment]
Please let us know if this is better in 2024.6
