### ISSUE TITLE
Gloss is not reflected when selecting Blend mode from Skin Materials.

### ISSUE THREAD

**Issue by tasuken** [alloystorm/dvvr#337]
**Describe the bug**
Select "Blend mode" from "Skin Materials" to change the skin color, the skin color is changed, but the "Gloss" effect disappears.
<img src=https://github.com/alloystorm/dvvr/assets/54142732/d5c88bd3-5999-4e9f-893a-1cba58d74da0  width=50%><img src=https://github.com/alloystorm/dvvr/assets/54142732/20a8a92d-a2d7-4bb0-b3ef-58aef29cba0e  width=50%>

When set from individual Material, "Gloss" is reflected as expected.
<img width="50%" alt="image" src="https://github.com/alloystorm/dvvr/assets/54142732/37af4ec4-9687-4458-b815-4395e5fe8767">

**To Reproduce**
1. Go to "Skin Materials"
2. Set "Gloss" 1.0
3. Select "Surface"
4. Change mode to "Blend"
5. Set Blend value and change color. 

**Expected behavior**
For the convenience of "Skin Materials" category, I would like to see Gloss also changed at once.

**Desktop (please complete the following information):**
![image](https://github.com/alloystorm/dvvr/assets/54142732/a374268b-83bd-4469-99da-af8dbca6bb9f)

**Comment by alloystorm** [comment]
Fixed in 2024.6
