### ISSUE TITLE
Butt Physics (Again...)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#339]
**Is your feature request related to a problem? Please describe.**
Can't get physics to work for butts... please just add a butt physics setting, OR finally add a way to adjust the "spheres" when Breasts AND Butt are chosen together within the Breasts Physics settings.

**Describe the solution you'd like**
Add a Butt Physics Menu option item.

**Describe alternatives you've considered**
Add a Butt Physics Menu option item.

**Additional context**
It be really nice to see simulated butts not be stone chiseled cheeks.

**Comment by alloystorm** [comment]
Soft body physics is now back in 2024.11 and is way better than before.
