### ISSUE TITLE
Bug Fix - Motion Controlled Camera Hampering UI Interactions

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#341]
**Is your feature request related to a problem? Please describe.**
Controlling the camera while in a motion that controls the camera makes it nearly impossible to select really any options unless a user is able to stop a "motion" (Paly/Pause Button Shortcut/Hotkey) though this does not work for Procedural Motions (since the Play/Pause feature is nonexistent for that feature, motion just continues.)

**Describe the solution you'd like**
A way to make while the camera is "moving" about to improve the ability to interact with UI elements. This is mainly an issue when in VR, possibly also non-VR.

Version: March 2024 Itch.io HD

**Comment by alloystorm** [comment]
From 2024.10 when you have UI present the camera motion will be freezed. Hope that solves the issue.
