### ISSUE TITLE
No normal map on xps models

### ISSUE THREAD

**Issue by PSGAPSGA** [alloystorm/dvvr#345]
Hello, 

I'm using Dancer XR PC version & found every xps models don't load normal maps or specular maps, they only use diffuse map. 
Every models I load have proper material setting & looks ok when I load by XNALara XPS viewer.
I'm using latest version from Steam on windows 10.
Do you have any idea? 

Thanks in advance.

**Comment by alloystorm** [comment]
If you can attach a link to one of your models we'll be able to check. 

It is usually related to file path, format and filename encoding etc.
