### ISSUE TITLE
Model melting after 2024.4

### ISSUE THREAD

**Issue by tasuken** [alloystorm/dvvr#347]
**Describe the bug**
Since updating to the 2024.4 version, several models are now melting.

**To Reproduce**
Load Model

**Expected behavior**
No melting

**Screenshots**
![スクリーンショット 2024-05-12 100709](https://github.com/alloystorm/dvvr/assets/54142732/a813360f-7fb7-4445-ba63-748f2b8104d4)

Same scene but 2024.3
![スクリーンショット 2024-05-12 102337](https://github.com/alloystorm/dvvr/assets/54142732/782a24a8-618b-4fe9-89b4-34e03e06fc17)

**Model file example**
[AultKlaudia1.0.zip](https://github.com/alloystorm/dvvr/files/15284751/AultKlaudia1.0.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2024.4

**Additional context**
Thanks again for all your development.
I give feedback sometines but am very satisfied.

**Comment by alloystorm** [comment]
Thanks for the model link. We'll look into that.

**Comment by alloystorm** [comment]
Will be fixed in 2024.6
