### ISSUE TITLE
BVH compatibility fix

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#349]
(reporting the issue from discord, so you can track it :)

Hi !

I have exporte some Bvh motion from vam for a test, and the reading of the BVH itself is working like  charm so I'm super excited ! BUT, for now.. it looks like the "center offset" check is not working on it (it does on the last month's version) AND it's taking this motion to move pinned around the waist, so when it's supposed to squat, well feet goes up instead etc.

Here are some of the BVH I exported for a test.
https://we.tl/t-6ID8Zn87Qd
https://we.tl/t-Tp4JrMiGTO

Could you take a look at this an give a try for a quick fix ? Then I could export so many motions to work with danceXR.
I really love your Mixed Reality version too, so it could be great to fix both VR and MR...

Thanks !

**Comment by hboxgames** [comment]
Here are the new links !
https://we.tl/t-0OcBGBFXGo

**Comment by alloystorm** [comment]
Yes this should be fixed in 2024.7
