### ISSUE TITLE
Texture bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#35]
I discover a bugs when the part of model texture are transparency and invisible. it happened to some of the model.

https://user-images.githubusercontent.com/49305586/74850094-8cc7c400-5307-11ea-9175-f34aaa8136c9.png

https://user-images.githubusercontent.com/49305586/74850118-92bda500-5307-11ea-8a38-a524336c4de6.png

https://user-images.githubusercontent.com/49305586/74866423-dd97e680-5320-11ea-848c-81eb7b9b6996.png

https://user-images.githubusercontent.com/49305586/74866820-7c244780-5321-11ea-95fd-3cde40abac64.png

**Comment by alloystorm** [comment]
If you know which texture it is, you can change its rendering mode to solve the issue.
![image](https://user-images.githubusercontent.com/51807035/75433636-5b549580-59a4-11ea-8fb8-a29e552b539b.png)
Most of the time the program should be able to determine the correct mode but there are exceptions. When this happens you need to manually change render mode.

**Comment by Terell2018** [comment]
I discover a bugs on when the texture are transparent, it happened to some model and i try the opaque, cutoff, alpha none of them isn't working. 

https://user-images.githubusercontent.com/49305586/76894043-bc64e000-6863-11ea-8c9d-5cc6ad8ae9b9.png
