### ISSUE TITLE
Simple content deleter

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#350]
Hi !!

Thank you for the great stuff as always. I am really fond of the Augmentedd reality version for Quest 3, hope it will keep improve :)

By the way, I have a very simple suggestion here.
The thing is, I download thousands of models (actors) and sometime bad ones, but I can't remember what is where, and realize they are actually good or bad when I load them in dvvr. It's getting really messy 

So, it would be AWESOME if we could take stuffs/directories we don't need and put them in the trashcan from the APP !

Do you think this could be achieved ?

Thanks you so much !

**Comment by alloystorm** [comment]
Will think about this. Thanks for the suggestion.

**Comment by alloystorm** [comment]
Available in 2024.9
