### ISSUE TITLE
Motion Override Conflicts with Ragdoll Feet Direction

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#356]
**Describe the bug**
When Motion Override is ACTIVE, and a Motion is played that is 180° facing the opposite of origin forward/front the feet don't adjust properly, it also has some strange effects on Ragdoll (where the feet are stuck always facing origin forward).

**To Reproduce**
See the above.

Version: May or June (2024) for Itch.io version

**Additional context**
My computer is inaccessible at the moment to verify some parts.

**Comment by alloystorm** [comment]
Will re-implement ragdoll feature with a different approach.
