### ISSUE TITLE
Problems with numeric pad menu

### ISSUE THREAD

**Issue by lubomyr** [alloystorm/dvvr#357]
Hi,
I noticed some nasty bug with numeric pad ui. When try to set floating value (for example 0.1), then press enter button, value not changed. When set in numpad UI integer value (for example 0 or 1) works correct. In this case set floating value possible only via slider
I noticed that problem on android version 2024.8, (on windows-beta 2024.8 this problem exists too).
But on quest-version(s) 2024.6 it works correct

Reproduce steps (example)
load any model
in model menu select material -> skin materials -> face gloss -> numpad
defaul value 0.650
change to 0.450 (via numeric pad menu), then press enter ui button
and we can see that this value not changed.

It look like platform related bug, because on quest it works correct. But also possible that can be version related bug in 2024.8 (android, windows-beta)

**Comment by alloystorm** [comment]
I wonder if the native language setting on your system uses "," instead of "." for decimal points?

**Comment by lubomyr** [comment]
Maybe, I don't know.
But you right,  it is really language problem, I tried to change system language on android device to english and then it works correct. Also on quest (where it works) i use english.
Is it possible to make a fix where system language not affect to this ?

**Comment by alloystorm** [comment]
Yes we will fix this in the next update. In fact we already have handling of other decimal formats in other areas but for certain newly updated areas this is currently broken.

**Comment by alloystorm** [comment]
Fixed in 2024.9
