### ISSUE TITLE
When "Twist Correction" is turned on, the model's arms are deformed.

### ISSUE THREAD

**Issue by panapopp** [alloystorm/dvvr#358]
**Describe the bug**
When "Twist Correction" is turned on, the model's arms are deformed.

**To Reproduce**
1. Load Model.
2. Load Audio/Motion.
3. Turn on "Twist Correction".

**Expected behavior**
The model's arms are deformed.
The arms of all models are distorted.
The model's arms are deformed in all VMD files.

**Screenshots**
![1](https://github.com/user-attachments/assets/cafe2a66-5819-495c-ae21-74aae4f73f40)
![2](https://github.com/user-attachments/assets/2b77b540-7204-4fe1-b213-b9c057246a78)

**Desktop (please complete the following information):**
  - OS: Windows10
 - DanceXR Version [2024.8.1350]

**Comment by alloystorm** [comment]
Fixed in 2024.9
