### ISSUE TITLE
Stop button bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#36]
There a problem with stop button from 0.5.2 it keep playing every time i hits stop button.

**Comment by alloystorm** [comment]
![image](https://user-images.githubusercontent.com/51807035/75434067-1715c500-59a5-11ea-84f3-6511a9b7ec90.png)

I see, when you have the player set to repeat single mode (shown in the screenshot), it does restart the audio when you hit stop. We'll fix it. But in the meantime, you can set it to other modes to avoid the issue.
