### ISSUE TITLE
Motion Override Leg Pose Open slider only work with procedural motion but not other song motions.

### ISSUE THREAD

**Issue by Benz10wheel** [alloystorm/dvvr#364]
Build 1350

Motion Override Leg Pose Open slider work with procedural motion 
but open slider only rotate the feet for other song motions.

**To Reproduce**
1. Go to Motion Override>Leg Pose>Left orRight setting> Open
2. Load a song/motion don't use procedural motion
3. change the 'Open' Slider for leg
4. See only foot rotate but not the knee

**Expected**
Knees to open/rotate.

**Comment by alloystorm** [comment]
This should be fixed in 2024.9

**Comment by Benz10wheel** [comment]
Still not fix in 2024.9.1380build

**Comment by Benz10wheel** [comment]
Fixed in 1382 thanks you!
