### ISSUE TITLE
Bug with non-zip music motion folders with an audio file containing the "#" character

### ISSUE THREAD

**Issue by AlexECX** [alloystorm/dvvr#368]
**Describe the bug**
Well this turned out to be a lot simpler and niche than expected for the time I put testing stuff 😅.

Music motion folder that use an audio file containing the `#` character will not load properly. They show as loaded in the Motion menu but not on the actor, and will immediately be unloaded after pressing play. This only occurs with non-zip folder, zip files don't have this issue.

**To Reproduce**
Steps to reproduce the behavior using this example music motion [Mori Calliope_Go-gettersモーション配布.zip](https://github.com/user-attachments/files/16913989/Mori.Calliope_Go-getters.zip):
1. Loading the motion directly from zip works fine
2. Loading the motion after un-zipping the folder will not work properly.

**Expected behavior**
There shouldn't be a difference between loading a motion as zip or as a folder

**Desktop (please complete the following information):**
 - OS: Windows 11    Version	23H2 Build 22631.4317
 - DanceXR: Pro version 2024.11.1434 in desktop mode

**Comment by AlexECX** [comment]
Updated to 2024.11

**Comment by alloystorm** [comment]
The "#" is messing up the Unity audio player, will have to recommend clean up filenames to remove common symbols used in URLs like :, /, \, #, ? etc.
