### ISSUE TITLE
If you check ''Custom Standard Pose''or "T Pose", ''Center Position adjustment'' doesn't work properly.

### ISSUE THREAD

**Issue by panapopp** [alloystorm/dvvr#369]
**Describe the bug**
If you check ''Custom Standard Pose''or "T Pose", ''Center Position adjustment'' doesn't work properly.

**To Reproduce**

explanation video

https://github.com/user-attachments/assets/402548bf-6d0a-43aa-8416-ec3131a4829c

https://github.com/user-attachments/assets/f1d0535b-3304-40c4-adb5-268c11d34675

**Expected behavior**
''Center Position adjustment'' doesn't work properly.

**Desktop (please complete the following information):**
 - OS: Windows10
 - DanceXR: pro HD Version 2024.9.1382

**Comment by Benz10wheel** [comment]
Custom Standard Pose also stop some motion/song from rotating properly. this also apply to Formation>Rotation slider.

**Comment by alloystorm** [comment]
Thanks. This is now fixed in build 1414

**Comment by panapopp** [comment]
Thank you always!!
