### ISSUE TITLE
When I load some models and stages, an error occurrs.

### ISSUE THREAD

**Issue by panapopp** [alloystorm/dvvr#371]
**Describe the bug**
When I load some models and stages, an error occurrs.
This error did not occur on or before "DanceXRproHD 2024.7.1317".

**Screenshots**
![model](https://github.com/user-attachments/assets/7e191b7d-4c62-492e-a044-81fe5cbbc089)
![stage](https://github.com/user-attachments/assets/5d4ad3a3-24b8-43d2-8626-2e9a9670d7fc)

**Log files**
[Player.log](https://github.com/user-attachments/files/17268701/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17268702/Player-prev.log)

**Sample model**
[test.zip](https://github.com/user-attachments/files/17268722/test.zip)

**Desktop (please complete the following information):**
 - OS: Windows10
 - DanceXR: pro HD Version 2024.10.1414

**Comment by comvir** [comment]
I encountered the same crash

**Comment by alloystorm** [comment]
Thanks for the report and the log file. 

Does this happen only for that stage model or does it happen to all?

**Comment by panapopp** [comment]
This error occurs in a few models and a few stages.
I am attaching other models  that crash.

**Sample model and stages**
[test model1.zip](https://github.com/user-attachments/files/17327145/test.model1.zip)
[test stage1.zip](https://github.com/user-attachments/files/17327151/test.stage1.zip)
[test stage2.zip](https://github.com/user-attachments/files/17327152/test.stage2.zip)

**Log files**
[Player.log](https://github.com/user-attachments/files/17327174/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17327177/Player-prev.log)

My English isn't so good so feel free to ask me if there is anything unclear.

**Comment by Nyexxi** [comment]
The problem is the extra model, the airplane, that comes with the main model, you need to fix the pairing bones of the plane or delete the plane itself and the bones related to the plane.

This is without the plane and it's working now
[test.zip](https://github.com/user-attachments/files/17328575/test.zip)

**Comment by panapopp** [comment]
I deleted all the bones in the models. It didn't crash.
But I want to use the model without removing the bones, just like before.
It's hard to find the problem bones.

**Comment by alloystorm** [comment]
Thanks for sharing the model. We'll take a look.

**Comment by AlexECX** [comment]
> It's hard to find the problem bones.

In PMXEditor open File->PMX Info, it will list problems with the model if there are any

Here's a screenshot of your testmodel1
![image](https://github.com/user-attachments/assets/12f8756d-f72f-4b05-b379-fe833407d086)

**Comment by AlexECX** [comment]
It seems like these bones are referencing themselves as their own Parent. I'm not familiar with this particular parameter so can't help with that

![image](https://github.com/user-attachments/assets/90d649fe-b90c-4e7b-ad2b-3c503b26847e)
![Screenshot 2024-10-10 225850](https://github.com/user-attachments/assets/2b94632e-d941-4c0c-bf94-c2c7252e6ec0)

**Comment by alloystorm** [comment]
Tested in the latest build and the Luka model seems working fine. Please try it in 2024.11 and let us know if it is resolved.
