### ISSUE TITLE
Changes made in any materials properties reset after reloading if they are not in a main category.

### ISSUE THREAD

**Issue by Nyexxi** [alloystorm/dvvr#372]
This is all about the latest LW Pro 2024.10.1414 version, the only version I can properly run in VR with my actual hardware and the main one I usually use, so I don't know if there are similar issues in the others versions of the software.

*Bugs*
1. Every change made in any material that is not in a main category (for example in Skin, Hair, Custom 1 or 2, etc...) it reset to default after reloading the same model or the program itself. 
For example, changing the gloss/glow or the colors of a material that is set in an Opaque category but not using the main Opaque category that englobes all opaque materials at the same time it revert to default after reload. This affect as well the stages materials. 

The solution at the moment is to load a preset of the model with all changes done but it's not ideal and it doesn't work for stages and by the way, the stages need this feature as well, to be able to save different presets of a stage will be great.

2. In Skins Materials settings there are three sliders that doesn't work and they worked at least in the version that they were implemented. The subsurface intensity, the thickness and the bump scale. I remember using them when they arrived.

3. In the Beat visualizer options, the radius slider is not working right, instead of reducing or expanding the radius, what it does is tilt it a little.

*Question*
1. How can I use the "Bundle" option in the scene tab? I know what it's for but no how to use it. Where can I found more info or a tutorial about it?

**Comment by alloystorm** [comment]
That bundle issue is fixed in 2024.11, the problem was when you have 0 bundles the save option doesn't show up... 

The subsurface and thickness settings affects the skin effect that light shine through the skin, this will dependent on the light source and the effect is different in LW version. 

The bump scale works if the model has normal map for the skin, if not nothing will happen.
