### ISSUE TITLE
Motion smooth adjustment feature has been removed.

### ISSUE THREAD

**Issue by panapopp** [alloystorm/dvvr#375]
**Describe the bug**
Motion smooth adjustment feature has been removed.
Motion smooth adjustment feature is very useful. I need the smooth adjustment feature.

DanceXRpro Ver.2024.09.1382
![smooth](https://github.com/user-attachments/assets/e8c3d50e-6dfe-45e7-bb19-0f637c44c0a2)

DanceXRpro Ver.2024.10.1414
![smooth02](https://github.com/user-attachments/assets/0b0e96a9-4a35-4e50-a189-4ad0728fe05a)

**Comment by Chrisc78** [comment]
Smooth adjustment is now under Playback Options

**Comment by panapopp** [comment]
That is not what I am looking for. 
I am looking for motion smooth adjustment feature.

**Comment by Chrisc78** [comment]
The latest version of DanceXR had an issue with the smoothness.

![Screenshot_20241021_132342_DanceXR](https://github.com/user-attachments/assets/607d2d2b-a0a1-4790-bc15-954cef2cc790)

If you lower the Global motion scale to 930 I find motions play much better.

**Comment by alloystorm** [comment]
This was removed when we switch to the new motion system. Will consider bringing it back in the future.

**Comment by alloystorm** [comment]
Available in 2024.12
