### ISSUE TITLE
Morph Bug it's keep adding Override and Weight. 2024.10.1414

### ISSUE THREAD

**Issue by TretanJonas** [alloystorm/dvvr#376]
https://github.com/user-attachments/assets/ea657995-a492-41f3-993b-f18edfe5016f

https://github.com/user-attachments/assets/8ae2dd22-9537-446e-b633-f985cca3f194

seem to be every actor with Morph option become like this and the issues all went away after Restarting the DanceXR.
each time i reload the Actor the more Override and Weight option will be added.
this occur in Version 2024.10.1414

**Comment by alloystorm** [comment]
Being fixed in 2024.11
