### ISSUE TITLE
VR Support on Mobile Version via Google Cardboard (With Gamepad Controls)

### ISSUE THREAD

**Issue by Judas87Swiff** [alloystorm/dvvr#377]
**Is your feature request related to a problem? Please describe.**
Currently the mobile version of DanceXR doesn't seem to support VR but, it does support AR Passthrough... so maybe a light weight alternative for quick support is to have DanceXR be able to access Google Cardboard for a cheaper VR mode?

**Describe the solution you'd like**
Add Google Cardboard Support.

**Describe alternatives you've considered**
Maybe make the app PC/Android/iOS (via 3rd Party Store) also support streaming to LookingGlassFactory's displays their LGF Portrait (for example) or Leia's Lume Pad2 Might be similar (Though this part is mainly aimed at the PC version.)

**Additional context**
QUESTION: In relation to AR Passthrough aleady being supported, can AR be accessible if VR support is added? (In a way that allows both in tandem.)

**Comment by alloystorm** [comment]
This probably won't happen. Cardboard is long dead. 

Quest 3S is a much better option, it's cheaper than any capable phone too.
