### ISSUE TITLE
Clothing Simulation Pulling Bug 2024.11

### ISSUE THREAD

**Issue by TretanJonas** [alloystorm/dvvr#379]
This Bug seem interesting. 

it's occur in the Clothing Simulation > Mesh 1/2 > Inner radius + Top / Bottom Anchor Lock. 
the Inner Radius seem to be randomly change the Bug some Higher Value the Bug stopped in Mesh 1/2. some Anchor Bone doesn't have this issues and some are Randomly Bugged in sort of unknown what Bone have and what Bone are not.

the Bug seem to be pulling toward the center part of the Ground the Further the Actor away from the Center it's likely to be more intensive pulling
at first i thought was Actor issues but even the XPS model the Bug remains the same.

(anyway Thanks for update that's solved the Collider Position. now i can set the Collider go further to this Value like -0.250 and 0.250 on some Model or TDA variant that has Butt position lower then it was -0.100. Or maybe i noticed the change abit late)

![Untitled1](https://github.com/user-attachments/assets/60f1f13d-f9bc-49e2-939d-d9437046b397)

![Untitled](https://github.com/user-attachments/assets/04d01547-d7c6-4257-9ba5-adfc67683718)

**Comment by alloystorm** [comment]
Fixed in 2024.12
