### ISSUE TITLE
freezing when loading this background

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#38]
https://drive.google.com/open?id=1ZrQQ-u6RjDnOCYZRiLsGXh_2x_bOzJnx

when loading this stage, everything freezes except the music.  cannot unfreeze.  This stage is fine in all of the older versions of DVVR.  Please help when you have time, but it's not really too important, thanks.

**Comment by alloystorm** [comment]
fixed in the 0.5.3 update
