### ISSUE TITLE
[DVVR 0.5.3] Motion Loading Stuck

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#39]
There a problem with motion loading from dvvr 0.5.3 when i trying to loading a motion. the motion loading got stuck and some motion did loading.

**Comment by alloystorm** [comment]
Can you share the motion file so I can take a look? Thanks

**Comment by pirsqed** [comment]
I've had the same issue with DVVR LW_win_0.5.3_public and DVVR HD_win_0.5.3_private. (Subscribed just to test it. 😂) 

Every motion file that I've tried is hanging. Here's just one example. 

https://drive.google.com/file/d/1Vr_Qku_M_eOLdIkLIZQwGla-XkYanQhk/view?usp=sharing

I've tried this with a bunch of different models, as well. 

I'm using an Index, if that matters. It's also happening in 'desktop' mode.

**Comment by alloystorm** [comment]
Nevermind, we figured it out. 

We added a step to load the setting file for each motion but didn't check if the file exists. So if the motion was not used in DVVR before it will hang. Will upload fixed build in a couple of hours. 

Sorry for the trouble.

**Comment by alloystorm** [comment]
Please download version 0.5.3a
