### ISSUE TITLE
Unable to load models and motions

### ISSUE THREAD

**Issue by Geff-dot** [alloystorm/dvvr#4]
I've been unable to load motions and models, here's some screenshots of my folders, let me know if I'm doing something wrong. Appreciate it, cheers.

-edit-
Not sure what changed but they actually loaded for me now, though I'm seeing a lot of distortion on the models as they move.

![Screenshot (5)](https://user-images.githubusercontent.com/54386366/63483788-60171a80-c452-11e9-8681-a3526321995d.png)
![Screenshot (6)](https://user-images.githubusercontent.com/54386366/63483790-60171a80-c452-11e9-840a-c744332cfea3.png)
![Screenshot (7)](https://user-images.githubusercontent.com/54386366/63483791-60171a80-c452-11e9-9d6e-079095acd99a.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54386366/63483792-60171a80-c452-11e9-9cf0-7d58540dc2a6.png)

**Comment by alloystorm** [comment]
Thanks for the screenshots. 

As of the model distortion, could you attach one of the models that has the issue and we'll see what's going on.

**Comment by alloystorm** [comment]
Closing this since the OP got it worked out.
