### ISSUE TITLE
'Desktop only' mode still opens Steam VR.

### ISSUE THREAD

**Issue by pirsqed** [alloystorm/dvvr#40]
When using the desktop_only.bat, SteamVR is still opened automatically. 

Not a huge deal, as I can just close SteamVR again, but it is annoying when I'm testing stuff.

Thanks for your time.

**Comment by alloystorm** [comment]
Under the new Unity XR plugin system, it is possible to launch the program without starting VR immediately but we found out that this created another issue, Oculus home stopped recognizing the program as a VR application and won't add it to the latest program list, which is a bit inconvenient. 
So for now, the current solution is still the best.

**Comment by TheCatsimator** [comment]
Getting [Opencomposite](url=https://gitlab.com/znixian/OpenOVR) (alternative to SteamVR) to replace the **openvr_api.dll** in DanceViewerVR (Version)/dvvr_data/Plugins/x86 should clear this up for you. It will still launch in VR when you launch the VR version. Just make sure to backup the original DLL just in case.
