### ISSUE TITLE
Certain models softlock DVVR

### ISSUE THREAD

**Issue by kroz07** [alloystorm/dvvr#46]
some models when loaded only display the "loading model" text infinitely making it impossible to return to the menu without restarting the program  

a model this happens with : https://drive.google.com/open?id=1-Et89ty_pAO57CzWADTDWk0Ey5HzdNKD

**Comment by alloystorm** [comment]
Thanks for the upload, will have a look.

**Comment by alloystorm** [comment]
It loads now in 0.6.2 but there are still issues with this model. We will need to investigate further.
