### ISSUE TITLE
Please allow skydomes in the future

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#47]
I have a lot of stages but I don't use them in dvvr because it currently doesn't allow skydomes.  It would be awesome if we could use them in the future.

**Comment by alloystorm** [comment]
Skydome is now supported in 0.6.2, please have a try and let us know what you think.

**Comment by chengsta** [comment]
I tried it, it works for stages that have multiple pmx files.  But is there anyway to just upload a jpeg/bmp file?
