### ISSUE TITLE
[DVVR 0.6] Stages not showing up

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#48]
When i try to loading a stages. the stages didn't show up and that only thing i see is dark screen and when i try to close the dvvr when i hits the red button dvvr won't close and it happened when i try to loading a stages. it didn't get stuck, it just the stages didn't show up.

**Comment by chengsta** [comment]
I have the same exact problem too!  I'm sure there are others with the same problem and they just don't bother to report!

**Comment by alloystorm** [comment]
I can confirm this is a bug but there is a quick workaround to address this before the proper fix. 

You can move your content folder further away from your executables folder and it should work fine. Either to a different drive or a couple of levels up.

**Comment by alloystorm** [comment]
Please find further description in the other issue post: https://github.com/alloystorm/dvvr/issues/49

**Comment by alloystorm** [comment]
Fixed in 0.6a
