### ISSUE TITLE
Loading last scene bug

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#52]
when you select the option to 'load last scene' and reset the program, it starts up and TRIES to load the last scene, but instead it's stuck loading forever.  
Now I use this because I have a pimax, but no controllers (shitty fucking company, but great vr headset).  and there is no way to interact with the tab with no vr controllers while in VR.  so I just get the scene right in desktop mode, then go into vr mode.  But in this version, it is broken.

**Comment by alloystorm** [comment]
Fixed in 0.6b, published on Patreon in the original 0.6 posts. Let me know if it works for you.
