### ISSUE TITLE
.DDS texture bug 

### ISSUE THREAD

**Issue by kroz07** [alloystorm/dvvr#53]
Models that use .DDS textures apply them incorrectly (either backwards upside down or both) other textures appear correctly. attempts to convert  the .DDS to .PNG files in external programs appears to cause DVVR to "give up" on loading the model almost instantly 

example of model before attempted conversion
https://drive.google.com/open?id=1w-p6pCd7heJYds1YJL3mSoOpB9Ge0CEH

after
https://drive.google.com/open?id=1CkWku0ozclsvqWphipG4Go3Jc5q81fNB

**Comment by alloystorm** [comment]
Thanks a lot. 

Will do some research on this. We had this issue on TGA format before so it should not be too difficult to fix if we can find the right definition of the format.

**Comment by alloystorm** [comment]
0.6.1 has added texture settings to allow flipping textures. This should solve the problem

**Comment by kroz07** [comment]
Thanks!
