### ISSUE TITLE
Nolo controllers can't interact with menu

### ISSUE THREAD

**Issue by witchaelf** [alloystorm/dvvr#54]
When using my Nolo controllers I can't "click" anything in the menu. Other buttons work (opening/closing menu, play/pause, etc), but I can't actually use the menu.

I believe it's somewhat related to the following issue https://github.com/alloystorm/dvvr/issues/3

I have tried manually setting presets via desktop mode, but none of them allowed me to click on buttons in the menu.

vrnodes.txt:

```
Pimax 5K Plus - Head
34F484D44
Pimax 5K Plus Head
Unknown

OpenVR Controller(Nolo_Controller) - Left
45B052762
Pimax 5K Plus LeftHand
Unknown

OpenVR Controller(Nolo_Controller) - Right
5159770AC
Pimax 5K Plus RightHand
Unknown

Nolo_Tracker S/N nolo_base_station_01
7B962C614
Pimax 5K Plus TrackingReference
Unknown

OpenVR Controller(XInput Controller)
8430A77DF
Pimax 5K Plus HardwareTracker
Unknown
```

Tried versions 0.5 and 0.6, same problem.

If it helps, the Nolo controllers behave much like the Vive controllers and have a very similar button layout. 2 grip buttons, menu button, trackpad and a trigger.

Thanks for your time.

**Comment by alloystorm** [comment]
Thanks for the input, will have a look at this but since we don't have the hardware it might take a few back & forth to get it to work. Will update this thread once we have a test build for you.

**Comment by witchaelf** [comment]
No problem, happy to help test :)

**Comment by alloystorm** [comment]
Hi, I'm wondering if the latest build works better for you? 

We switched to a different input platform which might provide better controller compatibility.

**Comment by witchaelf** [comment]
Yep, works perfectly now. Thanks very much!
