### ISSUE TITLE
Pmx model Normal Map

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#57]
Are there any plans to apply Normal Map to the pmx model?

It does not have to be automatic.

Please consider the method of manually specifying from the item of texture.

Thanks for the development.　:)

**Comment by alloystorm** [comment]
Fixed in 0.6.2

Normal map support has been added a long time ago but there was some shader issue with previous versions that prevented it from showing.

**Comment by IngenVR** [comment]
![normal_1](https://user-images.githubusercontent.com/58618176/83160024-a1ef9280-a141-11ea-9e4d-d58bbca7729f.png)
Thank you for development!
But I couldn't find a way to apply the normal map.
Please tell me how to do it.

**Comment by alloystorm** [comment]
Sorry for being unresponsive to this. 

To be honest, we don't really know the standard for normal maps for PMX models, but from observing some of the models it seems a naming convention is used. The current logic is, we take the file name of a texture map, append it with "-n", eg face.png -> face-n.png. If that file exists, we'll load it as a normal map.

**Comment by alloystorm** [comment]
If you have a better idea of how normal maps work in PMX, please let us know so we can implement it properly.

**Comment by IngenVR** [comment]
![hair00texandN](https://user-images.githubusercontent.com/58618176/85939652-4ab42c00-b952-11ea-82a6-07eac9bd9c37.png)
Left texture name=hair00
Right normal map name=hair00_n

I am supposed to put the the texture file and the normal map file in the same folder, right?
however,The normal map does not apply...
Am I doing it wrong?

**Comment by IngenVR** [comment]
Sorry.
I don't know how the normal map is acting in pmx either.

I think it would be easier and better if you could select the normal map from the texture settings as shown in the image below.
![000000](https://user-images.githubusercontent.com/58618176/85946630-a1385f00-b980-11ea-9a34-05369648fde6.jpg)

**Comment by alloystorm** [comment]
Thanks, will consider adding UI for editing texture maps. 

In your previous example, if you change the base map file name to hair00_d then it should work under current implementation.
Left texture name=hair00
Right normal map name=hair00_n

**Comment by IngenVR** [comment]
I tried several times, but it didn't work.
I'll wait for the new UI.
Thanks.
