### ISSUE TITLE
ver.6.1 hand motion bug

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#58]
It seems that wrist motion is not applied in version0.6.1.
The same problem occurs if I change the model, so it seems to be a problem specific to version0.6.1.
motion download:[https://bowlroll.net/file/183096](https://bowlroll.net/file/183096)
![0002](https://user-images.githubusercontent.com/58618176/80363879-d7ddf480-88bf-11ea-8543-4d9e808cbbb0.jpg)

**Comment by alloystorm** [comment]
Fixed in 0.6.2

**Comment by alloystorm** [comment]
Noticed another hand motion issue in 0.6.2, will fix now.

**Comment by IngenVR** [comment]
thank you updating! :)
