### ISSUE TITLE
Smarter bone mapper

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#59]
A while ago when I trying to tell you that I discover a bugs that some XPS model is not load into DVVR and when I looking at some Patreon comments that someone say that XPS model not display and i now understanding why some XPS model not load into DDVR because it don't have no standard bone and I was just wonder, when do you going to start working on the smarter bone mapper.

**Comment by alloystorm** [comment]
Thank you for the reminder. 

We now have a clearer plan. Instead of trying to let the program decide which bone is which, we'll implement a manual mapping UI for the user to create mapping if the default mapper fails. We'll include this in the next poll.
