### ISSUE TITLE
Some models not loading

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#6]
Hello, you fixed my last issue and I really appreciate it!  But now I'm going to bring another issue, and I hope I'm not bugging you too much.  But only about 75% of my models load.  The others don't.  I believe they may all be having the same issue.  So if you can get this one to work, then the rest probably will too, thanks!
https://drive.google.com/open?id=1UJIZj1EhidLJQFktNe37gFzxACNAxxdB

**Comment by alloystorm** [comment]
It seems working fine, at least on Mac. Will verify that on PC later. 

A couple of things you can check
1) The model is not too deep down in the folder structure, there might be an issue if the path is too long
2) There are no special characters in the folder name etc.

**Comment by alloystorm** [comment]
You are right, it doesn't load on PC...

The error message says "UnauthorizedAccessException: Access to the path "D:\dvvr\content\actors\Tda China Dress Rin by Evelyn-sama (Hot!) - Copy\sph\C4.png" is denied."

I looked into the folder and it seems those files are set to read-only and hidden. After removing those flags it loads just fine.

Not sure why Unity is unable to read hidden files but they should work if you remove those flags in explorer.
