### ISSUE TITLE
Skydome and accessories

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#61]
Hello, I don't know how feasable it is, but it would be awesome to have skydomes in DVVR just the way MMD has them.  Some stages just feel like something is missing.  

Also, some stages come in pieces so you need to load them all.  But DVVR can only allow one to load, so the stages are usually incomplete.  Please allow us to load multiple stages.  thanks!

**Comment by alloystorm** [comment]
It is now supported in 0.6.2. Please have a try and let us know any suggestions you have. Thanks.
