### ISSUE TITLE
Cannot select menu items with Oculus Rift controllers

### ISSUE THREAD

**Issue by thatibukikid** [alloystorm/dvvr#63]
Hello,

I've had this issue for a while and I can't seem to figure it out. Whenever I boot the DVVR in VR mode, I can open and close the menu without issues but when trying to select anything else on the menu the menu slides down as if its being dragged away each time. Is there something I can do to prevent this?

**Comment by alloystorm** [comment]
We've changed input system in the 0.6.3 release, you can try the new version and see if it solves your problem. 

You can try to run it without headset connected, so it is in desktop mode, then go to settings -> options and select oculus in the input settings. Then close the settings UI and quit the program then connect your headset and see if it works.
