### ISSUE TITLE
Boobs melting

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#68]
Hello, on a few of my models, when the dance begins, their boobs start melting and sagging all the way down to the floor very slowly.  Here is a link to a model.
https://drive.google.com/file/d/184_xamoeuFKs0py9-DElOIjO9IC_tCJ9/view?usp=sharing

Load model, load motion, and press play.  Please help fix this issue whenever you have time, thanks again.

![sakura boob melt](https://user-images.githubusercontent.com/54456572/85952273-99030400-b92d-11ea-9388-8cabe99c2620.jpg)

It'd be a real shame to not be able to have her work in your program.

**Comment by alloystorm** [comment]
You can try open actor settings -> Joint, either change linear motion to "locked" or increase linear spring value and see if that helps.

**Comment by chengsta** [comment]
hello, changing linear motion spring value up and down didn't help.  but putting it on 'locked fixed it'.  but now the hair is stiffer and doesn't flow as much.  oh well, good enough.

**Comment by alloystorm** [comment]
Hi, can you grant me access to the model file so I can look into what is causing this issue? Thanks

**Comment by chengsta** [comment]
https://drive.google.com/file/d/184_xamoeuFKs0py9-DElOIjO9IC_tCJ9/view?usp=sharing

here you go.  sorry about google being so dumb.  I hope you have access now.
________________________________
