### ISSUE TITLE
Dome cannot be loaded

### ISSUE THREAD

**Issue by sakurajosui** [alloystorm/dvvr#69]
Build 0.6.3, from "Dome" menu, sky dome cannot be loaded.   Build 0.6.2 works fine.

**Comment by alloystorm** [comment]
Could you re-download the build and see if it works? There was an issue with dome & stages and we released a fix without changing the version number.

**Comment by sakurajosui** [comment]
Stage or dome can be loaded from "Stage", but dome cannot be loaded from "Dome".

**Comment by sakurajosui** [comment]
0.6.3a works fine.  Thanks.
