### ISSUE TITLE
Camera motion in VR

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#7]
I know, we talked about this a few days ago.  However I really really want this to be an optional feature for people who like being the camera zipping everywhere.  You don't have to drop everything just to work on this.
However, I am willing to donate $200 whenever you do.  Just tell me where to send the money.

**Comment by alloystorm** [comment]
Thank you very much for your offer, let's discuss the solution first. 

Basically in VR the headset tracking controls your position and orientation in the virtual world, it might be a bit tricky to take over the camera completely. What if we map only the position of the camera track and allow the headset to control the orientation? It will be a bit like sitting in a spaceship that flys everywhere but you can still look around. Whereas the mocu camera mode is a bit like sticking a pair of binocular on your face and it turns by itself while you couldn't move at all. 

As of the donation, we'll have a think about it. Thanks again for your generosity.

**Comment by alloystorm** [comment]
Alright, I only used it in mmd for like 2 seconds a long time ago and never touched it again. Maybe they changed it later or I remembered it wrong. Anyway, that should be doable.

**Comment by alloystorm** [comment]
I'm using windows mixed reality btw.

**Comment by alloystorm** [comment]
We have this implemented in 0.2.4, looking forward to your feedback! Thanks.

**Comment by chengsta** [comment]
thanks, I'll check it out this weekend.  Let me know where to drop off the payment.

**Comment by chengsta** [comment]
Okay, I tried it and the camera movement is very buggy.  in non-vr mode, it moves like it should.  But then when I put on my headset, the camera barely moves 2 inches left or right when its supposed to move a lot more.  Also, for some reason when I put it in camera mode, it brings me 10 feet high into the air, and there is no way to bring me back down unless i reset.  It happens for all songs.

**Comment by alloystorm** [comment]
Oops, we forgot to offset the HMD position. 

Now fixed in 0.2.5, please let us know if it solves the issue for you.

**Comment by chengsta** [comment]
I just tried it, and it works now.  But when the dance was done, even if I get out of camera mode, I seem to have randomly shifted either left or right and the model is not center anymore.  Is there a reset center button?  Also, I'm sure you're aware that a lot of models randomly have their eyes turn white (Looking in the back of the head) during motions....but if not, I just thought I'd let you know.
