### ISSUE TITLE
Normal maps no longer working in ver 0.6.3b

### ISSUE THREAD

**Issue by raivaru** [alloystorm/dvvr#71]
After finally fixing the normal maps to work correctly in version 0.6.2, it seems like they're now completely broken in version 0.6.3b.

**Problem**

- Normal maps don't work at all with models that had no problems before. 
- Both XPS and pmx files are affected. 
- Changing the normal map value in texture options does nothing.
- Changing material type from skin to standard does not help.
- Texture flipping also no longer works

Normal maps were working correctly in versions:

DanceViewerVR LW_win_0.6.2_private
DanceViewerVR HD_win_0.6.2_private

Tested versions that have the problem:

DanceViewerVR LW_win_0.6.3b_private
DanceViewerVR HD_win_0.6.3b_private

**Comment by alloystorm** [comment]
Fixed in 0.6.3c

**Comment by alloystorm** [comment]
Closed since we believe it is fixed in 0.6.3c, if the problem persists let us know again.
