### ISSUE TITLE
DVVR no longer saves changes done in model config

### ISSUE THREAD

**Issue by raivaru** [alloystorm/dvvr#75]
When you change any settings of a model, DVVR doesn't save the changes when you close the program or replace the model. It does not create a new json file or save over the old one. DVVR still loads the old settings from a json files if it's present, but if you try to change the old settings, the changes are not saved to the json file. Deleting the old json file does not help. I'm having the problem with both XPS and PMX files.

While writing this bug report and testing the problem, I noticed that if you remove the model using the trashcan icon the program will still create/save the changes to a json file. I haven't done any extensive testing with a lot of models. So I'm not sure if this solution works with all models.

**Problem present in the versions**

 - DanceViewerVR HD_win_0.7_private
 - DanceViewerVR LW_win_0.7_private

**Current behavior**

When you change a models settings and afterwards either close the program or replace the model, the software **does not** create or overwrite a json file with the changes.

**Expected behavior**

When you change a models settings and afterwards either close the program or replace the model, the software either creates or overwrites a json file with the changes.

**Comment by alloystorm** [comment]
Thanks. Currently it saves when you close the actor settings UI, we will refine this logic and make it more reliable.

**Comment by alloystorm** [comment]
Fixed in 0.7.1b, download can be found in the 0.7.1 release posts.
