### ISSUE TITLE
[DVVR 0.7] Morph bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#78]
![Screenshot (1)](https://user-images.githubusercontent.com/49305586/92394551-bd2e4e80-f0ef-11ea-8726-b97a77f4bda5.png)

I discovery a bugs about morph that is not working with some of models.

**Comment by alloystorm** [comment]
Which version is this? There were problems with material morphs in 0.7 but they've been fixed in 0.7.1

**Comment by Terell2018** [comment]
I am using version 0.7

**Comment by alloystorm** [comment]
Releasing the public version of 0.7.1 now. Should be able to solve your issue.
