### ISSUE TITLE
Some XPS models not loading

### ISSUE THREAD

**Issue by Hectorhammett** [alloystorm/dvvr#80]
**Describe the bug**
Some models fail to load, without showing any message

**To Reproduce**
1. Here is a model that fails to load on DVVR but not on XNALARA:
https://www.deviantart.com/dddkhakha1/art/Aerith-Gainsborough-Final-Fantasy-7-Remake-840010774

2. Go to actors and heat load
3. Select the model
4. No model appears nor an error message

**Expected behavior**
I expected to see the model or at least an error whether that'd be a error on a type of texture or something else.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
That is not the only model that fails to load. I have been playing with some models and some of those also fail to load while they do load on XNALARA. Although I am a noob modding models so I might be doing something wonky with the textures so I don't think that could be of much help.

Thanks so much! What a fantastic viewer you guys have!

**Comment by alloystorm** [comment]
The bone mapper should now solve this issue.
