### ISSUE TITLE
Cannot switch camera anymore in 7.2b

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#83]
So in other previous versions, I was able to switch camera using the 'C' button.  I know, I know, I already checked to see if controller setup was set correctly.  Set input option 'Switch camera' to 'C'.  I doublechecked, and it is correct.  

It works with previous versions.  when I load 7.2.b it no longer works.

**Comment by alloystorm** [comment]
Will look into it.

**Comment by alloystorm** [comment]
Fixed in 0.7.2c, please check the Patreon page for the latest download.
