### ISSUE TITLE
No positional tracking in VR (7.2c)

### ISSUE THREAD

**Issue by raivaru** [alloystorm/dvvr#86]
There doesn't seem to be positional tracking in VR in version 7.2c. The problem does not seem to be in my system, since positional tracking still works in previous version including 7.2b. Tried in both current and fresh installation of DVVR 7.2c.

Camera is set to freefly. Tried switching from free -> auto -> free but that did not help.

The menu seems to be able to tell that the vr headset is moving, since I can still get closer or further away from it, but the world and models stay at the same distance/height when the headsets position changes in the real world. Rotation tracking still works, but since there is no positional tracking it looks a bit wonky.

**Versions**   DanceViewerVR HD_win_0.7.2c_private & DanceViewerVR LW_win_0.7.2c_private
**OS**           Win 10 pro 64 bit
**Headset**   Valve Index

**Comment by alloystorm** [comment]
Looking into it.

**Comment by alloystorm** [comment]
This was a bug introduced with the camera change in the last version. Fixed now in 0.7.3.
