### ISSUE TITLE
custom lighting settings 7.3

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#87]
-freezes when you rename and save a custom lighting setting, and try to load it.
-Doesn't save point/spotlight settings, seems to want to go back to spotlight everytime i reload.  
-Also, checking the box to make the lighting invisble unchecks itself after reload, it doesn't save that setting either.

Other light settings seem to save just fine.

this is all on a BRAND NEW folder as recommended, and i made sure it wasn't 'read only'

**Comment by alloystorm** [comment]
Should be fixed now.
