### ISSUE TITLE
Model bugging on latest version

### ISSUE THREAD

**Issue by jmew1989** [alloystorm/dvvr#90]
Hi !

Again, thank you for amazing works so far !

I was testing out the new private version, which has great features btw..
Then tried out one of my previous scenes with this model, and it didn't work right.
DL :  https://we.tl/t-yEHxvkm3o6
Actually, it's loading in, and reading motions etc without problem. BUT, the root(or should I say hips) isn't following the rest which makes it akward and buggy.
I wonder why this is happening since it is a model that was working perfectly in previous versions.

Thanks in advance !!

**Comment by alloystorm** [comment]
Thanks, I downloaded the model and can see what you mean. Will investigate further.

**Comment by alloystorm** [comment]
This model actually has 3 "center" bones, the first one seems to be the right one to use. 

I've made a change to only use the first bone when there are duplicate names. However, I'm not sure if this change is going to cause trouble with other models. I guess we'll see. 

The latest builds already include this change. 0.7.3.52 & 0.7.3.54 uploaded to Patreon already.

**Comment by jmew1989** [comment]
Thanks for the fast move !!
