### ISSUE TITLE
DLSS integration feature request

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#93]
Hello, i'm not sure how hard it is to make DVVR DLSS compatible, but it would totally be awesome if you can implement it.  It would improve performance by up to 50% from what I've seen.  I know it won't be done overnight, but if you can just keep it in the back of your mind that would be awesome.

**Comment by alloystorm** [comment]
Will investigate this.

**Comment by alloystorm** [comment]
DLSS is still not available in Unity. Will keep an eye on it.

**Comment by alloystorm** [comment]
DLSS is available now in Unity. Will try it out in the next version.

**Comment by alloystorm** [comment]
Unity 2021.2 which has DLSS support is still in beta and it's having a bit issue with our project. We may be able to test it out once it comes out of beta.

**Comment by alloystorm** [comment]
Good news that we've got DLSS working and it works in VR. I'm seeing around 20-30% performance boost. 

However it's unity support is till in beta and currently has a few bugs. We have some workarounds for the issues but there are a few limitations at the moment. Will publish more details when the next release is out.

**Comment by alloystorm** [comment]
Full DLSS and FSR support is now available in 1.1.3
