### ISSUE TITLE
Accessory and props feature request

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#95]
Hello again, I would like to request the ability to add accessories and props (props are usually in '.x' format, while accessories are usually in regular .pmx format in MMD).  There are some dances that require dance poles, and I hope I can import dance poles some day.  And then there are some dances that require the dancer to hold a fan.  And I hope someday we are able to import a fan, as well as attach it to a hand, and load movements (open/close/spin/flip etc) some day.

thanks.

**Comment by Chrisc78** [comment]
I was just thinking it would be nice to be able to load Accessorys and attach them to the model or to attach them to the players hand in VR mode so I could use a fan or a dildo or something, that would be awesome

**Comment by alloystorm** [comment]
Delivered in version 1.3.3
