### ISSUE TITLE
Version checker

### ISSUE THREAD

**Issue by jmew1989** [alloystorm/dvvr#96]
Hey, I've been switching between version according to what works better and stability. Then I just realised there suddenly is a "version checker" which prevents me from using previous versions.
Could you get rid of it ?

Also, was wondering a side thing for MMD models ! I noticed we can pretty much put the collision to none or very low for XNA models, and I was wondering if the same thing could be implemented for MMD models, since it's sometime very buggy and maybe choosing either we use collision or not would make it cool !

Thanks a lot

**Comment by jmew1989** [comment]
OH btw one of the reasons I was switching versions (among others) is that I noticed in the latest one, that loading a scene will make most "reflection" effect not applied visually until we reload textures manually(P.I.T.A.)

**Comment by chengsta** [comment]
yea, its not saving background textures again.  gotta reload it manually again.
