### ISSUE TITLE
Doublechecking the issue

### ISSUE THREAD

**Issue by jmew1989** [alloystorm/dvvr#97]
Ok don't really want to doublepost but it was irritating so just want to be sure this is solved and the message communicated.

The latest version is quite broken to me here and there(like stretching monstrous physics on XPS models). But I would just wait for future improvement and use previous versions that worked great for me, meanwhile.

Sincerely hope that you will understand and not force us to stop supporting you for such dumb reason.

Thanks for the great work so far

**Comment by Eliols123** [comment]
They will stop doing the expiry date for future builds. But I believe you can set the date back to the release month of the build, then you should be able to use that version again.
