### ISSUE TITLE
Some motion files are not loaded

### ISSUE THREAD

**Issue by AhatLi** [alloystorm/dvvr#99]
I am using DanceViewerVR HD_win64_0.8.73_private version.
Some motion files do not load.
As a result of a simple test, I found that it was not due to the file name and path.
There are many motions that I want to use, but there are too many motion files that cannot be used.

It leaves a link of one of the motion files that cannot be used.
https://bowlroll.net/file/165076

Thank you

**Comment by AhatLi** [comment]
It was a problem with my method of use.
The motion directory structure was changed to'motion' and'camera', so motion became available.

**Comment by alloystorm** [comment]
Sounds like you got it sorted, so closing this now. If I understand you incorrectly, then feel free to report again with examples. Thank you.
